### ISSUE TITLE
Broken tags?

### ISSUE THREAD

**Issue by Tosh022402** [AstralOrdana/Spelunkery#1]
Something is wrong with spelunky´s mineable block tags, trying to mine a log with an axe and its takes too long, as if i was just punching it, removing the mod fixes this issue

Using forge 43.2.0

**Comment by AstralOrdana** [comment]
unable to reproudce this issue, check your log to make sure its not caused by some other mod

**Comment by Kawatt** [comment]
I can replicate it with fabric too
Here are the logs: 
[latest.log](https://github.com/AstralOrdana/Spelunkery/files/10372388/latest.log)

**Comment by AstralOrdana** [comment]
fixed for version 0.1.2
