### ISSUE TITLE
Raw Salt blocks in the world can light up, and will crash client and server if other light sources are placed on them.

### ISSUE THREAD

**Issue by KajesLorian** [AstralOrdana/Spelunkery#100]
**Describe the bug:**
I had a salt lamp sitting on a regular block of salt in-world, and when I pick it up with my paxel a bunch of the salt blocks lit up as if they were glowstone. I tried to place the salt lamp back on it and my game crashed. I repeated it and the same thing happened. On the third try I found I could place regular blocks on the lit salt just fine, but placing a torch on the lit block caused the entire server to crash, needing a restart. I can no longer log on without crashing the server.

**Versions:**
Minecraft version:1.19.2
Spelunkery version:1.19.2-0.2.4-forge
Moonlight Lib version: 1.19.2-2.2.43-forge
Supplementaries: 1.19.2-2.3.20
Fabric API / QSL / Forge version: 43.2.8

**Other mods:**
[ModList.txt](https://github.com/AstralOrdana/Spelunkery/files/12210211/ModList.txt)

**Logs:**
[latest.log](https://github.com/AstralOrdana/Spelunkery/files/12210217/latest.log)
[debug.log](https://github.com/AstralOrdana/Spelunkery/files/12210219/debug.log)

**To Reproduce:**
1. Place or remove a light source from a salt block (And salt blocks connected should light up.
2a. Place salt lamp on lit up salt block (client crash) or
2b. Place torch on lit up salt block (server crash)

**Expected behavior:**

**Screenshots:**
If applicable, add screenshots to help explain your problem. https://screenshot.help/

**Additional info:**
[crash-2023-07-30_17.34.18-client.txt](https://github.com/AstralOrdana/Spelunkery/files/12210223/crash-2023-07-30_17.34.18-client.txt)
[crash-2023-07-30_22.03.47-server.txt](https://github.com/AstralOrdana/Spelunkery/files/12210233/crash-2023-07-30_22.03.47-server.txt)

**Comment by AstralOrdana** [comment]
do you have any salt lamp blocks placed in the area?

**Comment by KajesLorian** [comment]
I do. There is one about 3 blocks away sitting on some of the glowing salt blocks. There is also the one in my inventory.

**Comment by AstralOrdana** [comment]
k, pretty sure thats the source of the crash, i'm planning to put out a bug fix update in the next few days and this should be resolved then

**Comment by KajesLorian** [comment]
Okay

**Comment by AstralOrdana** [comment]
fixed for 0.2.5
