### ISSUE TITLE
Crash after Startup with Moonlight

### ISSUE THREAD

**Issue by pewblaze** [AstralOrdana/Spelunkery#102]
**Describe the bug:**
When starting the game it crashes instantly due to an error with moonlight. 
I know that ive got a lot of mods, & im not sure if you can fix it - but maybe you can understand the crash log ^^" 
Without spelunkery i can start the game just fine. 

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version: 1.20.1
Spelunkery version: spelunkery-1.20.1-0.3.1-fabric
Moonlight Lib version: moonlight-1.20-2.7.2-fabric
Fabric API / QSL / Forge version: fabric-api-0.86.1+1.20.1

**Other mods:**
Listed in the crash report:
https://gist.github.com/pewblaze/339245edc7a947a2c4e94fd235ebe7f3

**Logs:**
*Even if the game does not crash they may be useful!*
Please provide the following logs:
From .minecraft/logs :  "latest.log" as well as "debug.log" if it exists. From .minecraft : "launcher_log" as well as a
file that starts with "hs_err" if it exists. Note: Double check that the logs are from the correct time. ex, don't give
us a log from a month ago because you forgot to check the date.

I only got the crash and latest.log
Sorry i didnt find the other ones.
https://gist.github.com/pewblaze/339245edc7a947a2c4e94fd235ebe7f3

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Start the game 
2. Crashes

**Expected behavior:**
Starting the game without an error ^^

**Screenshots:**
If applicable, add screenshots to help explain your problem. https://screenshot.help/

**Additional info:**
Add any other information that might be needed.

**Comment by SiverDX** [comment]
i think its the same issue as here https://github.com/AstralOrdana/Spelunkery/issues/97
where a config gets accessed before it has been initialized / loaded

**Comment by NerjalNosk** [comment]
Also, fixed by #108, only needs to be released (should happen soon)
