### ISSUE TITLE
Mine-O-Mite broken with Realistic Explosion Physics

### ISSUE THREAD

**Issue by SuperiorGhoul42** [AstralOrdana/Spelunkery#104]
When the realistic explosion physics mod is loaded, the Mine-O-Mite block (all 9 variations) when ignited explodes and jumps up in the air instead of being destroyed. They can then be continuously relit, creating infinite explosions.

**Versions**
Minecraft version: 1.19.2
Spelunkery version: 0.2.5
Moonlight Lib version: 2.2.43
Forge version: 43.2.21

**Mods:**
spelunkery-1.19.2-0.2.5-forge.jar
RealisticExplosionPhysics-1.19.2-1.0.0.jar

**Steps to reproduce:**
1. Download both mods
2. Place down Mine-O-Mite and ignite
3. Wait for it to explode

**Expected behavior**
It should explode and the Mino-O-Mite block be destroyed.

**Comment by AstralOrdana** [comment]
support for that mod is not planned
