### ISSUE TITLE
spelunkery:noise_stripes_end not generating

### ISSUE THREAD

**Issue by Shuben103** [AstralOrdana/Spelunkery#107]
**Describe the bug:**
The feature spelunkery:noise_stripes_end does not generate, likely due to an error in its .json file.
When browsing through the mod's files, I noticed that although the configured feature spelunkery:noise_stripes_end does not specify generation height, obsidian and crying obsidian only generates on the bottom of end islands, and their shapes don't really match noise stripes in the Overworld either. Upon further inspection, I noticed that the biome specification used in the file is #minecraft:has_end_city, which is not a valid tag. This may be causing these noise stripes to fail to generate.

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version: 1.20.1
Spelunkery version: 0.3.1
Moonlight Lib version: 2.7.2
Fabric API / QSL / Forge version: Fabric API 0.86.1-1.20.1

**Other mods:**
![image](https://github.com/AstralOrdana/Spelunkery/assets/141729150/5f289fef-8588-4b41-a56a-187a5c7bb18e)

**Logs:**
*Even if the game does not crash they may be useful!*
Please provide the following logs:
From .minecraft/logs :  "latest.log" as well as "debug.log" if it exists. From .minecraft : "launcher_log" as well as a
file that starts with "hs_err" if it exists. Note: Double check that the logs are from the correct time. ex, don't give
us a log from a month ago because you forgot to check the date.

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1.
2.
3.

**Expected behavior:**
Huge veins of obsidian generating throughout the outer end islands, resulting in large belts of obsidian visible on the upper surfaces of the islands similar to that of salt block and dirt belts in the Stony Peaks biome in the overworld.

**Screenshots:**
If applicable, add screenshots to help explain your problem. https://screenshot.help/

**Additional info:**
Add any other information that might be needed.

**Comment by AstralOrdana** [comment]
fixed for next update
