### ISSUE TITLE
Crash On Startup

### ISSUE THREAD

**Issue by Blunder-G** [AstralOrdana/Spelunkery#11]
Exit Code: 1 Crash, on startup

Minecraft version: 1.19.2
Spelunkery version: 0.1.4
Moonlight Lib version: 2.1.30
Fabric API / QSL / Forge version: Forge 43.2.3

Mod list: 
[modlist.txt](https://github.com/AstralOrdana/Spelunkery/files/10472153/modlist.txt)

Log file: 
[latest.log](https://github.com/AstralOrdana/Spelunkery/files/10472163/latest.log)

Debug file: 
[debug.log](https://github.com/AstralOrdana/Spelunkery/files/10472164/debug.log)

**Comment by Drezkil** [comment]
It's said on debug file that's a conflict with dontDropCompass.

**Comment by AstralOrdana** [comment]
for now, dont use DDYC with spelunkery since spelunkery has all the features of it anyway
