### ISSUE TITLE
Crash during game

### ISSUE THREAD

**Issue by ChromaPIE** [AstralOrdana/Spelunkery#112]
**Describe the bug:**
The game crashes after a few seconds of wandering in world.

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version: 1.20.1
Spelunkery version: 0.3.1
Moonlight Lib version: 2.8.2
Fabric API / QSL / Forge version: 0.87.0

**Other mods:**
Shown in log provided below.

**Logs:**
https://mclo.gs/9qgX7zs

**Comment by ChromaPIE** [comment]
problem's gone for good, prolly fixed by the latest moonlight lib update i guess?

**Comment by ChromaPIE** [comment]
No it's still here.

**Comment by AstralOrdana** [comment]
disable the better sculk patches in the config

**Comment by ChromaPIE** [comment]
okay i'll try it rn. btw does it work as a temp workaround or a worldgen mod conflict thats not actually a problem on spelunkery?

**Comment by SiverDX** [comment]
You can try to set `allowThreadedFeatures = false` for C2ME instead, it seems to pop up in there as well
