### ISSUE TITLE
Potential Feature replacement bug return (Fabric 1.20.1)

### ISSUE THREAD

**Issue by Ultimushadow** [AstralOrdana/Spelunkery#113]
**Describe the bug:**
As stated in other bug reports, the improved sculk feature seems to be causing issues when generating. This is only confirmed in singleplayer, as I didn't have time to throw it on a hosted server for testing. I tested with and without Concurrent Chunk Management - With CCM resulted in an actual crash, linked below. Without CCM, the server simply froze and never recovered. After some investigating, I discovered others had had this issue and that a fix was implemented in a previous version. I also saw you recommended disabling the feature. Once I did so, the issues stopped. The issues also stopped when I removed Spelunkery entirely. 

**Versions:**
Minecraft version: 1.20.1
Spelunkery version: 0.3.1
Moonlight Lib version: 2.8.4
Fabric API / QSL / Forge version: Fabric API 0.87.0

**Other mods:**
It's probably best to just check the log/crash report. There are many.

**Logs:**
Log: [2023-08-19-5.txt](https://github.com/AstralOrdana/Spelunkery/files/12385836/2023-08-19-5.txt)
Crash Report: [crash-2023-08-19_06.34.53-server.txt](https://github.com/AstralOrdana/Spelunkery/files/12385839/crash-2023-08-19_06.34.53-server.txt)

**To Reproduce:**
1. Load up the game and enter a world
2. Fly in a single direction until the game freezes
3. Load up the game again with CCM installed
4. Fly in a single direction until the game crashes
5. Disable Spelunkery or Sculk feature and repeat

**Expected behavior:**
The report says it's trying to place a feature in a chunk that doesn't exist, but that may be caused by CCM, I can't confirm that's the actual issue. If it is, I would assume the game should only be generating features in chunks that exist. If this is not the base cause then I would expect the game to skip any features causing issues and make a note in the log, or actually crash rather than just freezing for eternity.

**Additional info:**
This is obviously tested on my computer with many other mods installed which leaves a lot of room for something else to be helping this issue happen - however, it's definitely the sculk patches that are dealing the final blow as I have encountered no crashing or lagging issues with them gone. There is plenty of lag due to Spelunkery's other generated features but it does not cause an end of function like the sculk seems to. 
If you want me to look further into this before engaging with the issue I can test the mods in other environments. I would have done this already but I have a lot of mods acting up lately and it's getting harder to pinpoint issues.

**Comment by AstralOrdana** [comment]
consider disabling the modified sculk veins if they are giving you issues

**Comment by Ultimushadow** [comment]
Yes, I've already done this and will continue to do so until a fix if possible

**Comment by AstralOrdana** [comment]
the modified veins have been removed
