### ISSUE TITLE
Large coal veins can't spawn in 1.19.2 Forge due to biome modifier using empty tag

### ISSUE THREAD

**Issue by mintynora** [AstralOrdana/Spelunkery#115]
The swamp_modifier in Forge uses the tag "#minecraft:has_swamp_hut", which is not a valid tag. Vanilla has a similar biome tag, "#minecraft:has_structure/swamp_hut". Honestly you can just use "minecraft:swamp" as mangrove swamps don't generate witch huts.

**Versions:**
Minecraft version: 1.19.2
Spelunkery version: 0.2.2 (issue is present in newer versions too though)
Moonlight Lib version: 2.2.34
Fabric API / QSL / Forge version: 43.2.3

**Expected behavior:** Biome modifier should use a valid tag so that coal veins can spawn :(

**Additional info:**
See https://github.com/AstralOrdana/Spelunkery/blob/main/forge/src/main/resources/data/spelunkery/forge/biome_modifier/swamp_modifier.json

**Comment by AstralOrdana** [comment]
fixed for 0.2.6
