### ISSUE TITLE
Crash with Aurora's Decorations (1.19.2 Fabric)

### ISSUE THREAD

**Issue by comp500** [AstralOrdana/Spelunkery#116]
**Describe the bug:**
Launching the game with Spelunkery and Aurora's Decorations causes the `CommonConfigs` to break (or be called too early?): `NullPointerException: Cannot invoke "java.util.function.Supplier.get()" because "com.ordana.spelunkery.configs.CommonConfigs.PORTAL_DESTRUCTION_SOUND" is null`

**Versions:**
Minecraft version: 1.19.2
Spelunkery version: 1.19.2-0.2.5
Moonlight Lib version: 1.19.2-2.2.44
QSL version: 4.0.0-beta.30+0.76.0-1.19.2
Quilt Loader version: 0.20.0-beta.15

**Other mods:**
Aurora's Decorations 1.0.0-beta.12+1.19
MixinTrace 2.0.0+1.19.2 (private build, I'm rewriting it)

**Logs:**
Crash report: [crash-2023-08-21_14.25.40-client.txt](https://github.com/AstralOrdana/Spelunkery/files/12396413/crash-2023-08-21_14.25.40-client.txt)
Log: [latest.log](https://github.com/AstralOrdana/Spelunkery/files/12396416/latest.log)

**To Reproduce:**
1. Launch the game
2. ???
3. It crashes

**Expected behavior:**
I expected the game to launch without crashing 🙃

**Screenshots:**
None

**Additional info:**
None

**Comment by NerjalNosk** [comment]
Fixed by #108 (thought non-fatal at that time, because mixed up in a lot of error logs), only awaiting to be published

**Comment by AstralOrdana** [comment]
fixed for 0.2.6
