### ISSUE TITLE
1.20 crash

### ISSUE THREAD

**Issue by artizarra** [AstralOrdana/Spelunkery#118]
I keep getting the "Game crashed while loading" error. I've tried using it with no other mods enabled, and then only with moonlight lib and supplementary mod (most recent versions of each) and the same thing happened each time so I don't think it's an incompatibility issue. This is one of my favorite mods ever and I'm so happy it updated to 1.20 so I'd really like to be able to use it :(

**Comment by EndilCrafter** [comment]
Did you install from CurseForge? If it does, then please install from Modrinth.

**Comment by lilKdoggie** [comment]
I too have this issue, I tried downloading from Modrinth and it did not help, still crashing

**Comment by NerjalNosk** [comment]
Did you know? Saying "something doesn't work" without any details doesn't help solving an issue.
And just as well, this repository actually offers an issue template, that actually helps the developers to identify the real issue. Even of you don't like it, wiping it out when creating your issue will only make your issue be purely ignored, because unhelpful.

**Comment by EndilCrafter** [comment]
> I too have this issue, I tried downloading from Modrinth and it did not help, still crashing

Did you install correct version?
Spelunkery 1.20.1-0.3.1
moonlight-1.20-2.8.7 (latest)

**Comment by TrueDevron** [comment]
I am also having this issue

**Comment by lilKdoggie** [comment]
> > I too have this issue, I tried downloading from Modrinth and it did not help, still crashing
> 
> Did you install correct version? Spelunkery 1.20.1-0.3.1 moonlight-1.20-2.8.7 (latest)
> 
> ![image](https://user-images.githubusercontent.com/135924661/263101363-2b4233af-557c-40ad-a61d-6d9e17cff32d.png)

I was using the lastest forge version this morning for both mods.
There was an update for it on forge today while I was at work and it seems to work now.

I can give more tech info if needed, and I encourage the others who had this issues from CurseForge to go update and try it again!
