### ISSUE TITLE
Crash on startup 1.20.1 Latest Forge

### ISSUE THREAD

**Issue by GermanArtur** [AstralOrdana/Spelunkery#119]
create-1.20.1-0.5.1.d.jar
create-structures-0.1.1-1.20.1-FORGE.jar
moonlight-1.20-2.8.7-forge.jar
nocube's_create_compact_exp_1.0.3_forge_1.20.1.jar
spelunkery-1.19.2-0.2.6-forge.jar
supplementaries-1.20-2.5.26.jar
suppsquared-1.20-1.1.10.jar

debug log: https://pastebin.com/85eqBKgn
latest.log: https://pastebin.com/nsS5gQYg
crash report: -

**Comment by AstralOrdana** [comment]
you're using a 1.19 version of spelunkery on 1.20
