### ISSUE TITLE
Add option to disable Bottles o´ Portal fluid 

### ISSUE THREAD

**Issue by Tosh022402** [AstralOrdana/Spelunkery#12]
It can break progression in some modpacks as they provide a different way of teleportation
Also other mods may increase generation of crying obsidian or add recipes to craft it, making it really easy to obtain

If not possible, maybe there is a way to change which block you need to right click to get Bottles o´ Portal fluid?

**Comment by AstralOrdana** [comment]
Added config option to make portal fluid obtained from charged respawn anchors instead of crying obsidian
