### ISSUE TITLE
Mod Compatibility with Galosphere, as well as Sulfur And Potassium - More Gunpowder

### ISSUE THREAD

**Issue by Numerosityy** [AstralOrdana/Spelunkery#122]
**Feature:**

Describe what the new feature should be.  Generally, the more information you provide, the faster we can decide on whether it is something we can/will do.
Compatibility with Galosphere, as well as Sulfur And Potassium - More Gunpowder
(Add nuggets, rough versions of existing materials, etc. matching the format of other existing materials)

Not much else to say, just would be nice to see

**Comment by AstralOrdana** [comment]
you want... sulfur nuggets?

**Comment by Numerosityy** [comment]
I mean yeah... its just nice to have the same type of items for modded ores
It would probably follow the format of gemstones since sulfur forms crystals irl

**Comment by AstralOrdana** [comment]
not planned
