### ISSUE TITLE
Loot does not drop

### ISSUE THREAD

**Issue by EndilCrafter** [AstralOrdana/Spelunkery#124]
When I mined blocks or killed mobs, those loots do not drop.
But some ores (diamond, emerald, lapis, redstone, nether gold and deepslate ores) do.
I tried with only Spelunkery (and Moonlight), but nothing changed.

Minecraft version:1.20.1
Spelunkery version:0.3.2
Moonlight Lib version:2.8.12
Forge version:47.1.44

**Comment by lilKdoggie** [comment]
I too am having this issue with my modpack that includes Spelunkery.
I did testing and only when spelunkery is added does this issue appear, and when just it's Spelunkery (and Moonlight) it also happens.

If any other info could be handy, I can try my best to supply, just ask.

MC Vers: 1.20.1
Spelunkery Vers: 0.3.2
Moonlight Lib Vers: 2.8.12
Forge Vers: 47.143

**Comment by FynnWaelsing** [comment]
I was having the same issue as above. Downgrading to Spelunkery version 0.3.1 fixed it, so the recent issue appears to be the problem.

**Comment by ewsmith** [comment]
seems like #92 has slithered back into the code base

**Comment by GermanArtur** [comment]
I have the same issue

moonlight-1.20-2.8.13-forge.jar
spelunkery-1.20.1-0.3.2-forge.jar

**Comment by AstralOrdana** [comment]
sorry about that, fixed for 1.20.1-0.3.3
