### ISSUE TITLE
Add tremors

### ISSUE THREAD

**Issue by PolyframeX** [AstralOrdana/Spelunkery#128]
**Feature:**

So basically, tremors would make it to where rocks (a 2d rock texture) and/or stalagtite peices will fall from the ceiling, this event can happen at random, and wouldn't break any blocks. This would spice up the expirence a little bit by adding some variety to what can happen inside of a cave. Obviously the rocks and stalagities will deal some damage to the player if hit.

**Alternatives:**

Diffrent methods could be such as just breaking blocks, however I don't see this as a great way to implement a concept such as this.

**Additional info:**

This could be triggered somehow with maybe a specific occurrence, such as explosions.

**Comment by AstralOrdana** [comment]
not currently within scope
