### ISSUE TITLE
Crush 0.3.2 when loading chunk the world on Quilt 1.20.1

### ISSUE THREAD

**Issue by mairangh** [AstralOrdana/Spelunkery#129]
**Describe the bug:**
A crash when loading the world. When i re-join the world, everything is fine.

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version: 1.20.1
Spelunkery version: 0.3.2
Moonlight Lib version: 2.7.2
Quilt version: 0.19.5

**Other mods:**
The list in the crush-report
[crash-2023-08-31_12.38.06-server.txt](https://github.com/AstralOrdana/Spelunkery/files/12484950/crash-2023-08-31_12.38.06-server.txt)

**Logs:**
[2023-08-31-3.log](https://github.com/AstralOrdana/Spelunkery/files/12484897/2023-08-31-3.log)

**To Reproduce:**
1. launched the game
2. Uploaded the world.
3. I wrote the locate command and found a biome of stone peaks.
4. Teleported away.
5. I saw chunks that were not being loaded
6. Crush

**Expected behavior:**
Uploaded chunk :)

**Comment by NerjalNosk** [comment]
How about updating [Moonlight Lib](https://modrinth.com/mod/moonlight/version/1.20-2.8.13) to its latest version?

**Comment by mairangh** [comment]
> Как насчет обновления [Moonlight Lib](https://modrinth.com/mod/moonlight/version/1.20-2.8.13) до ее последней версии?

I'll try and let you know if there are still failures
