### ISSUE TITLE
Modified Create crushing recipe give the wrong stone type

### ISSUE THREAD

**Issue by nicolhaq** [AstralOrdana/Spelunkery#13]
**Describe the bug:**
Some Create crushing recipe give the wrong stone type:
sandstone lapis ore -> cobblestone,
deepslate redstone ore -> calcite,
andesite emerald ore -> cobblestone,
deepslate emerald ore -> andesite,
deepslate diamond ore -> smooth basalt,

**Versions:**
Minecraft version: 1.19.2
Spelunkery version: 1.4
Moonlight Lib version: 2.2.0
Forge version: 43.2.3

**Other mods:**
Create: 0.5.0.h
JEI: 11.4.2.1007
Immersive Weathering: 1.2.5

**Expected behavior:**
sandstone lapis ore -> sandstone,
deepslate redstone ore -> cobbeled deepslate,
andesite emerald ore -> andesite,
deepslate emerals ore -> cobbeled deepslate,
deepslate diamond ore -> cobbeled deepslate,

**Screenshots:**
![image](https://user-images.githubusercontent.com/6973373/214730811-9a8450b9-5abc-4160-8802-a6092f73fae5.png)
![image](https://user-images.githubusercontent.com/6973373/214730703-f09498d2-cdf0-4c69-a1c7-1db04ac1a604.png)
![image](https://user-images.githubusercontent.com/6973373/214730962-d101e439-71a7-4a28-984d-fe64db00bd98.png)
![image](https://user-images.githubusercontent.com/6973373/214731086-7ed9a680-41eb-4c28-9a49-c2b843b4e13b.png)
![image](https://user-images.githubusercontent.com/6973373/214731248-a107985c-aa25-4c53-9c93-0ed3da311952.png)

**Comment by AstralOrdana** [comment]
fixed for next version
