### ISSUE TITLE
Crash on startup - 1.20.1-neoforge-47.1.76

### ISSUE THREAD

**Issue by GermanArtur** [AstralOrdana/Spelunkery#132]
latest log - https://pastebin.com/Lp8j3hs8
crash report - https://pastebin.com/khUmmNfL

"mod has failed to load correctly"
![image](https://github.com/AstralOrdana/Spelunkery/assets/64424996/322719c0-6ece-40dd-9329-ba9a5ecc5f53)

moonlight-1.20-2.8.16-forge.jar
spelunkery-1.20.1-0.3.3-forge.jar

**Comment by Hahahavana** [comment]
Crash seems to be specific to version 0.3.3, version 0.3.2 seems to load fine. Standard forge has the same CONSTRUCT 1 related crash.

**Comment by AstralOrdana** [comment]
resolved in 0.3.4
