### ISSUE TITLE
Natural chests generate empty

### ISSUE THREAD

**Issue by xaphlactus** [AstralOrdana/Spelunkery#133]
**Describe the bug:**
A clear and concise description of what the bug is. Include as much information as you can. Images are often helpful, especially screenshots of the F3 debug menu.
**_When generating any new world - with or without other mods - all naturally generating loot chests spawn empty.
Upon searching the logs, ore stone drops is named as the culprit as far as I can understand, to quote from 1 of the excessively many errors:
'[03Sep2023 21:30:38.479] [Worker-Main-1/ERROR] [net.minecraftforge.common.ForgeHooks/]: Couldn't parse element loot_tables:minecraft:chests/village/village_snowy_house
java.lang.NullPointerException: Cannot invoke "java.util.function.Supplier.get()" because "com.ordana.spelunkery.configs.CommonConfigs.ORE_STONE_DROPS" is null'_**

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version: **_1.20.1_**
Spelunkery version: **_0.3.2 (see note at bottom)_**
Moonlight Lib version: **_2.8.16_**
Fabric API / QSL / Forge version: **_Forge 47.1.0_**

**Other mods:**
List all mods that you're using; could be in the form of a list of the filenames, a crash report list, a screenshot of
the mods folder, etc. Just make sure all mods used are known!
**_None - I have culled the issue down to just this mod (+ Moonlight Lib as dependency)_**

**Logs:**
*Even if the game does not crash they may be useful!*
Please provide the following logs:
From .minecraft/logs :  "latest.log" as well as "debug.log" if it exists. From .minecraft : "launcher_log" as well as a
file that starts with "hs_err" if it exists. Note: Double check that the logs are from the correct time. ex, don't give
us a log from a month ago because you forgot to check the date.

[latest.log](https://github.com/AstralOrdana/Spelunkery/files/12509495/latest.log)
(this log is from when I had a full modlist, but the bug obviously persisted when I removed them all - in case there's any confusion there)

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. **_load minecraft_**
2. **_generate new world_**
3. **_check any natural loot chest_**

**Expected behavior:**
**_natural loot (i.e. apples and saplings in village house chest)_**

**Screenshots:**
If applicable, add screenshots to help explain your problem. https://screenshot.help/

**Additional info:**
Add any other information that might be needed.
**_I am using Spelunkery version 0.3.2 as the 0.3.3 version simply crashes for me (forge says it failed to load correctly, "java.lang.reflect.InvocationTargetException: null"). Again, this is with only spelunkery and moonlight lib, though that's probably a separate report.
-->I also tested this with a fresh install of minecraft to be certain no other mod data persisted. 0.3.3 still crashed, and loot chests were still empty with 0.3.2._**

**Comment by AstralOrdana** [comment]
this issue was resolved in 0.3.3, unfortunately it also introduced a new crash bug that i am working on at present and has already been reported

**Comment by xaphlactus** [comment]
Oh jeez I somehow missed that changelog, thanks for such a quick reply!
