### ISSUE TITLE
Portal Fluid Ocean config not functional - possibly result of other mods

### ISSUE THREAD

**Issue by AngelTechnic** [AstralOrdana/Spelunkery#134]
When this version of Spelunkery released, I was intrigued as to how it worked, so I loaded up my pack after updating to generate the new config, then I closed and edited the portal fluid ocean to "true" before reloading and creating a new world. However, once I entered the End (using commands), the fluid ocean was not present. This may have something to do with a mod/datapack I have, Nullscape, which changes the physical dimensions of the End.

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version: 1.20.1
Spelunkery version: 1.20.1-0.3.4
Moonlight Lib version: 1.20-2.8.16
Fabric API / QSL / Forge version: Quilt Loader version 0.20.2, QSL version 7.2.1+0.88.0-1.20.1

**Other mods:**
Present within attached latest.log

**Logs:**
*Even if the game does not crash they may be useful!*
Attached latest.log, no other relevant logs.

**To Reproduce:**

1. Generate a new world after loading the mods and setting the configs.
2. Enter the End, I use a command to teleport myself into there "/execute in minecraft:the_end run tp 0 100 0"
3. Go to y=0 in the End.

**Expected behavior:**
There should be a flat plane of portal fluid at the bottom of the End.

**Screenshots:**
If applicable, add screenshots to help explain your problem. https://screenshot.help/

**Additional info:**
Again, I feel like this may be a result of Nullscape changing the physical dimensions of the End, as it boosts the height of the dimension. However, I can use a /fill command to place portal fluid blocks there myself.
[latest.log](https://github.com/AstralOrdana/Spelunkery/files/12528082/latest.log)

**Comment by AstralOrdana** [comment]
the ocean is only present in the outer end

**Comment by AngelTechnic** [comment]
wait really? that would have been nice to know, i expected to see it surrounding the main end island

**Comment by AstralOrdana** [comment]
working as intended
