### ISSUE TITLE
Portal fluid texture bug with Iris

### ISSUE THREAD

**Issue by vukkax** [AstralOrdana/Spelunkery#135]
**Describe the bug:**
When using Iris alongside Spelunkery the texture of the portal fluid seems to bug in some specific cases such as in a 3x3 pool of it.

**Versions:**
Minecraft version: 1.20.1
Spelunkery version: 0.3.4
Moonlight Lib version: 2.8.17
Fabric API / QSL / Forge version:  QFAPI 7.2.1 and QSL 6.1.1

**Other mods:**
![image](https://github.com/AstralOrdana/Spelunkery/assets/108903683/207a2f46-3703-4886-af7f-8bbca9e8ea21)

**Logs:**
[latest.log](https://github.com/AstralOrdana/Spelunkery/files/12539925/latest.log)

**To Reproduce:**
1. Open new instance of Minecraft with Iris and Spelunkery
2. Build 3x3 pool of dimensional fluid
3. Texture bugs :(

**Expected behavior:**
The texture not bugging.

**Screenshots:**
![image](https://github.com/AstralOrdana/Spelunkery/assets/108903683/85738ce3-264e-4c8e-a3d7-57d5b4988a5f)

**Additional info:**

**Comment by newtrogicNexus** [comment]
Issue occurs with Oculus on forge as well.

**Comment by FrenzoGonzo** [comment]
Is this fixed yet? I'm getting this issue with oculus

**Comment by steve-the-player** [comment]
> Is this fixed yet? I'm getting this issue with oculus

It's tagged Fixed but unreleased. That means this fix should be in one of the next few updates where they release a big batch of bug fixes all at once

**Comment by Corn-on-the-Orb** [comment]
Is this issue still not fixed? its been almost a year now?

**Comment by meeprdib** [comment]
See the comment right above yours

**Comment by AstralOrdana** [comment]
fixed in 0.3.6
