### ISSUE TITLE
Cannot disable m'ores

### ISSUE THREAD

**Issue by donkeyrat** [AstralOrdana/Spelunkery#136]
**Describe the bug:**
Disabling the "enable_mores" config setting causes the game to crash.

**Versions:**
Minecraft version: 1.20.1
Spelunkery version: 0.3.4
Moonlight Lib version: 2.8.17
Fabric API / QSL / Forge version: Quilt 0.20.2

**Other mods:**
Irrelevant since I've tested with and without other mods

**Logs:**
[crash-2023-09-08_17.57.06-client.txt](https://github.com/AstralOrdana/Spelunkery/files/12564328/crash-2023-09-08_17.57.06-client.txt)
[latest.log](https://github.com/AstralOrdana/Spelunkery/files/12564327/latest.log)

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Set the "enable_mores" configuration setting to false.
2. Observe that the game crashes.

**Expected behavior:**
The game should not crash.

**Comment by AstralOrdana** [comment]
fixed for 0.3.5
