### ISSUE TITLE
World and chunk gen lags

### ISSUE THREAD

**Issue by moninformateur** [AstralOrdana/Spelunkery#137]
**Describe the bug:**
With the latest versions of Spelunkery, worldgen and every few times a new chunk is generated creates a lot of lags, seemingly because of the "large emerald vein" feature.

This line is in the logs when the lag happens:

`Detected setBlock in a far chunk [-5, -7], pos: MutableBlockPos{x=-80, y=162, z=-102}, status: minecraft:features, currently generating: ResourceKey[minecraft:worldgen/placed_feature / spelunkery:large_emerald_vein]`

**Versions:**
Minecraft version: 1.20.1
Spelunkery version: 1.20.1-0.3.4
Moonlight Lib version: 1.20-2.8.18
Fabric API / QSL / Forge version: 47.1.3

**Other mods:**
<details>
  <summary>Mod used screenshot</summary>
  ![image](https://github.com/AstralOrdana/Spelunkery/assets/79221061/12818a83-9e93-40b1-9b1e-d97b8a800f02)
</details>

**Logs:**
This happens at worldgen: Logline [5935](https://mclo.gs/0sdLfrF#L5935).

Then again with new chunk created, at loglines [6647](https://mclo.gs/0sdLfrF#L6647), [6801](https://mclo.gs/0sdLfrF#L6801)

**Expected behavior:**
Spelunkery does not cause abnormal chunk gen lag

**Comment by marc-cwm** [comment]
I'm also having this issue, I can fly around and it seems to occur consistently on vein generation.  The client is still mostly responsive but chunk generation seems to just stop and block interaction stops happening.  Unfortunately, it looks like creating an option to disable the veins and workaround this error may have been overlooked.  

The amount of lag was lessened, but I was able to replicate this with other mods removed.

**Comment by AstralOrdana** [comment]
this was not overlooked, a massive amount of work has gone into optimizing the naturally performance intensive noise-based stone generation but despite that, a config option to disable the veins is also included

the log spam from the emeralds has hopefully been fixed for 0.3.5 but documentation on the causes of that error in particular are not very helpful so it may persist in some cases

**Comment by LeKripiY** [comment]
Hello, I am using 0.3.5 of Spelunkery along with other mods for my modpack, it seems that this issue is still present. The mod spams my logs with errors about generating emerald veins, and then my server timeouts. I haven't found any way to disable emerald vein generation for now.
