### ISSUE TITLE
no xp loss on death

### ISSUE THREAD

**Issue by nicolhaq** [AstralOrdana/Spelunkery#14]
**Describe the bug:**
on death spawn xp orb but do not lose any xp after respawn

Versions:
Minecraft version: 1.19.2
Spelunkery version: 1.4
Moonlight Lib version: 2.2.0
Forge version: 43.2.4

Other mods:
JEI: 11.4.2.1007

**To Reproduce:**
die with some xp

**Expected behavior:**
lose all xp on death

**Comment by AstralOrdana** [comment]
already fixed for next upcoming release
