### ISSUE TITLE
Conk fungus doesn't drop when mined

### ISSUE THREAD

**Issue by mintynoura** [AstralOrdana/Spelunkery#142]
I'm not sure why this is happening. The loot tables and everything seem valid, and all the other fungi drop just fine.

Minecraft version: 1.20.1
Spelunkery version: 1.20.1-0.3.4
Moonlight Lib version: 1.20-2.8.42
Fabric API / QSL / Forge version: 7.2.2+0.88.1-1.20.1

**Other mods**: None (tested on a fresh instance)

**Logs**: They don't show any errors related to conk fungus, or any loot tables at all for that matter

**To Reproduce:**

1. Place conk fungus on a wall
2. Mine it in survival mode
3. Discover that nothing drops

**Expected behavior:** Conk fungus should drop when mined 

**Additional info:** It can still drop when the block it's attached to is broken

**Comment by AstralOrdana** [comment]
fixed for 0.3.5
