### ISSUE TITLE
Large coal veins don't seem to generate in fabric version

### ISSUE THREAD

**Issue by mintynoura** [AstralOrdana/Spelunkery#145]
Tested on a single-biome swamp world. No large coal veins spawn. I'm really not sure why, i couldn't find anything wrong in the repo :(

**Versions**:
Minecraft version: 1.20.1
Spelunkery version: 1.20.1-0.3.4
Moonlight Lib version: 1.20-2.8.42
QFAPI version: 7.3.1+0.89.3-1.20.1
Quilt version: 0.21.0-beta.4

**Other mods:** 
None, tested on fresh instance

**Logs:**
Don't seem to say anything about worldgen. No mention of large_coal_vein or anything

**To Reproduce:**

1. Create a single-biome swamp world 
2. Search for large coal veins. I used the /fill command to replace blocks with air
3. Discover that no coal veins generate

**Expected behavior:**
Large coal veins should generate. I tested the forge version of the mod using the same seed and setup, and found multiple veins pretty quickly

**Screenshots:**

![image](https://github.com/AstralOrdana/Spelunkery/assets/107040228/44d48431-a700-484a-9063-209d47101042)

this is after removing most blocks that weren't deepslate coal ore

**Additional info:**
im sobbing and crying because i can't collect all the rocks

**Comment by AstralOrdana** [comment]
fixed for 0.3.5
