### ISSUE TITLE
[1.19.2] Diamond Grindstone Doesn't Polish Rough Gems

### ISSUE THREAD

**Issue by CactusDuud** [AstralOrdana/Spelunkery#147]
**Describe the bug:**
Diamond grindstone doesn't convert rough gems into their polished forms. Using a rough gem on the grindstone just opens the UI

**Versions:**
Minecraft version: 1.19.2
Spelunkery version: 1.19.2-0.2.5 & 1.19.2-0.2.6
Moonlight Lib version: 1.19.2-2.2.45
Fabric API: 0.76.1+1.19.2

**Other mods:**
<details>
<summary>Mods:</summary>
	- accurateblockplacement 1.2
	- advanced-tooltips 1.6.0+1.19
	   \-- advanced-tooltips-core 1.6.0
	- advdebug 2.3.0
	- almostunified 1.19.2-0.7.0
	- amecs 1.3.8+mc.1.19-rc2
	- andromeda 0.9.2-1.19.2
	   |-- dark-matter-analytics 1.1.0-1.19.2
	   |-- dark-matter-analytics-crashes 1.1.0-1.19.2
	   |-- dark-matter-analytics-mixpanel 1.1.0-1.19.2
	   |-- dark-matter-base 1.1.0-1.19.2
	   |-- dark-matter-content 1.1.0-1.19.2
	   |-- dark-matter-glitter 1.1.0-1.19.2
	   |-- dark-matter-minecraft 1.1.0-1.19.2
	   \-- dark-matter-mirage 1.1.0-1.19.2
	- angling 1.0.1
	- antighost 1.19.1-fabric0.58.5-1.1.5
	   \-- crowdin-translate 1.4+1.19
	- appleskin 2.4.1+mc1.19
	- architects_palette 3.0.0
	- architectury 6.5.85
	- artifacts 7.1.1+fabric
	   |-- expandability 6.0.0
	   \-- step-height-entity-attribute 1.0.0
	- auditory 0.0.4-1.19.x
	- authme 4.2.0
	- auto_third_person 2.1
	- autotag-convention 2.0.0+1.19
	   \-- autotag 2.0.0+1.19
	- backpacked 2.2.7
	- balm-fabric 4.6.0
	- bclib 2.1.7
	- beautify 1.1.1+fabric-1.19.2
	   |-- cardinal-components-base 5.0.2
	   |-- cardinal-components-entity 5.0.2
	   \-- cardinal-components-world 5.0.2
	- better_climbing 2
	- betterbeds 1.2.0
	- betterdeserttemples 1.19.2-Fabric-2.2.2
	   \-- org_reflections_reflections 0.10.2
	- betterdungeons 1.19.2-Fabric-3.2.1
	- betterend 2.1.6
	- betterendisland 1.19.2-Fabric-1.0
	- betterfortresses 1.19.2-Fabric-1.0.6
	- betterjungletemples 1.19.2-Fabric-1.0.1
	- bettermineshafts 1.19.2-Fabric-3.2.0
	- betternether 7.1.4
	- betteroceanmonuments 1.19.2-Fabric-2.1.1
	- betterpotionvisuals 1.0.0
	- bettersafebed 4
	- betterthirdperson 1.9.0
	- betterwitchhuts 1.19.2-Fabric-2.1.0
	- biomemakeover 1.19.2-1.6.4
	- blahaj 0.2.0
	- bookshelf 16.3.20
	- bosses_of_mass_destruction 1.4.6-1.19.2
	   |-- maelstrom_library 1.3-1.19-pre1
	   \-- multipart_entities 1.2-1.19-pre1
	- brewinandchewin fabric-2.3.1+1.19.2
	   \-- mm 2.3
	- bushierflowers 0.0.1-1.19.2
	- byg 2.0.1.4
	- cardinal-components 5.0.2
	   |-- cardinal-components-base 5.0.2
	   |-- cardinal-components-block 5.0.2
	   |-- cardinal-components-chunk 5.0.2
	   |-- cardinal-components-entity 5.0.2
	   |-- cardinal-components-item 5.0.2
	   |-- cardinal-components-level 5.0.2
	   |-- cardinal-components-scoreboard 5.0.2
	   \-- cardinal-components-world 5.0.2
	- chat_heads 0.10.22
	- chatpatches 192.2.1
	- chickensshed 1.3.6
	- choicetheorems_overhauledvillagefriendsandfoesaddon_mr 1.1
	- chunksfadein 3.0.12-1.19
	   |-- com_moandjiezana_toml_toml4j 0.7.2
	   \-- crowdin-translate 1.4+1.19
	- citresewn 1.1.2+1.19.2
	   \-- citresewn-defaults 1.1.2+1.19.2
	- clean_tooltips 1.3
	- cloth-config 8.3.103
	   \-- cloth-basic-math 0.6.1
	- clumps 9.0.0+14
	- collective 6.66
	- combatroll 1.1.5+1.19
	- connectiblechains 2.1.4+1.19.2
	- continents 1.1.3
	- continuity 2.0.2+1.19
	- convenientdecor 0.2.0
	- corgilib 1.0.0.34
	   |-- com_electronwill_night-config_core 3.6.6
	   \-- com_electronwill_night-config_toml 3.6.6
	- coyote_time 1.0.0
	- create 0.5.1-c-build.1160+mc1.19.2
	   |-- com_google_code_findbugs_jsr305 3.0.2
	   |-- flywheel 0.6.9-6
	   |-- forge_tags 3.0
	   |-- milk 1.0.51
	   |    \-- dripstone_fluid_lib 2.0.1
	   |-- porting_lib_accessors 2.1.1096+1.19.2
	   |-- porting_lib_base 2.1.1096+1.19.2
	   |    |-- mm 2.3
	   |    |-- porting_lib_attributes 2.1.1096+1.19.2
	   |    |-- porting_lib_common 2.1.1096+1.19.2
	   |    |-- porting_lib_constants 2.1.1096+1.19.2
	   |    |-- porting_lib_lazy_registration 2.1.1096+1.19.2
	   |    |-- porting_lib_loot 2.1.1096+1.19.2
	   |    |-- porting_lib_model_generators 2.1.1096+1.19.2
	   |    |-- porting_lib_model_loader 2.1.1096+1.19.2
	   |    \-- porting_lib_models 2.1.1096+1.19.2
	   |-- porting_lib_entity 2.1.1096+1.19.2
	   |    \-- porting_lib_constants 2.1.1096+1.19.2
	   |-- porting_lib_extensions 2.1.1096+1.19.2
	   |    |-- porting_lib_attributes 2.1.1096+1.19.2
	   |    |-- porting_lib_common 2.1.1096+1.19.2
	   |    \-- porting_lib_constants 2.1.1096+1.19.2
	   |-- porting_lib_fake_players 2.1.1096+1.19.2
	   |-- porting_lib_networking 2.1.1096+1.19.2
	   |-- porting_lib_obj_loader 2.1.1096+1.19.2
	   |    |-- porting_lib_attributes 2.1.1096+1.19.2
	   |    |-- porting_lib_common 2.1.1096+1.19.2
	   |    |-- porting_lib_constants 2.1.1096+1.19.2
	   |    \-- porting_lib_model_loader 2.1.1096+1.19.2
	   |-- porting_lib_transfer 2.1.1096+1.19.2
	   |    |-- porting_lib_attributes 2.1.1096+1.19.2
	   |    |-- porting_lib_common 2.1.1096+1.19.2
	   |    \-- porting_lib_constants 2.1.1096+1.19.2
	   |-- reach-entity-attributes 2.3.0
	   \-- registrate-fabric 1.1.58-MC1.19.2
	- create_enchantment_industry 1.0.1.b
	   \-- create_dragon_lib 1.0.1
	- create_renewableores_mr 1
	- createutilities 0.1.3+1.19.2
	- crittersandcompanions 1.19.2-2.0.1
	- cryingghasts 3.1
	- ctov 3.2.6c
	- ctov_beautifyaddon_mr 1.0
	- cull-less-leaves 1.0.6
	   \-- conditional-mixin 0.3.0
	- culturaldelights 0.14.10+1.19.2
	   \-- terraform-wood-api-v1 4.2.0
	- davespotioneering fabric-1.19.2-1.4.2
	   \-- cloth-client-events-v0 4.0.65
	- dawn 3.5.0
	- debugify 2.8.0
	- decorative_blocks 3.1.1
	- diagonalfences 4.2.6
	- diagonalwindows 4.0.2
	- doubledoors 5.0
	- dummmmmmy 1.19.2-1.7.2
	- dungeons_andtaverns_mr 2.0.2
	- dungeons_arise 2.1.56
	- dynamic_fps 3.2.1
	- earthtojavamobs 1.10.1
	- easyanvils 4.0.11
	- easymagic 4.3.3
	- easyshulkerboxes 4.4.1
	- ecologics 2.1.11
	- elytraslot 6.1.1+1.19.2
	- emi 1.0.23+1.19.2+fabric
	- emi_loot 0.6.5+1.19
	- emiffect 0.1.5+mc1.19.2
	- emitrades 1.0.2+mc1.19.2
	- enchancement 1.19-14
	   |-- cardinal-components-base 5.0.2
	   |-- cardinal-components-entity 5.0.2
	   |-- cardinal-components-world 5.0.2
	   |-- midnightlib 1.0.0
	   \-- step-height-entity-attribute 1.0.0
	- enchantmentsplus 1.2.0+1.19.2
	   \-- reach-entity-attributes 2.3.0
	- enchdesc 13.0.14
	- enderscape 0.4.1-1.19.2
	- endrem 5.2.0
	- ends_delight 1.19.2-1.0
	- enhanced_attack_indicator 1.0.4+1.19
	- enhancedblockentities 0.7.2+1.19.2
	   \-- advanced_runtime_resource_pack 0.6.2
	- entity_model_features 1.0.2
	- entity_texture_features 4.5.1
	   \-- org_apache_httpcomponents_httpmime 4.5.10
	- entityculling 1.6.1-mc1.19.2
	- everycomp 1.19.2-2.5.11
	- expandeddelight 0.2.5
	- explosiveenhancement 1.2.2-1.19.2
	- extended_drawers 1.4.5+mc.1.19.2
	   |-- graphlib 0.3.6+1.19.2
	   \-- mconfig 1.2.0+mc.1.19-rc1
	        \-- de_poiu_apron_apron 2.1.1
	- extraalchemy 1.9.0
	- extrasounds 2.3.1+1.19.2-1.19.1
	   |-- advanced_runtime_resource_pack 0.6.2
	   \-- soundcategories 1.2.4+1.19
	- fabric-api 0.76.1+1.19.2
	   |-- fabric-api-base 0.4.15+8f4e8eb390
	   |-- fabric-api-lookup-api-v1 1.6.14+93d8cb8290
	   |-- fabric-biome-api-v1 9.1.1+16f1e31390
	   |-- fabric-block-api-v1 1.0.2+e415d50e90
	   |-- fabric-blockrenderlayer-v1 1.1.25+cafc6e8e90
	   |-- fabric-client-tags-api-v1 1.0.5+b35fea8390
	   |-- fabric-command-api-v1 1.2.16+f71b366f90
	   |-- fabric-command-api-v2 2.2.1+413cbbc790
	   |-- fabric-commands-v0 0.2.33+df3654b390
	   |-- fabric-containers-v0 0.1.42+df3654b390
	   |-- fabric-content-registries-v0 3.5.2+7c6cd14d90
	   |-- fabric-convention-tags-v1 1.3.0+4bc6e26290
	   |-- fabric-crash-report-info-v1 0.2.8+aeb40ebe90
	   |-- fabric-data-generation-api-v1 5.3.9+413cbbc790
	   |-- fabric-dimensions-v1 2.1.35+0d0f210290
	   |-- fabric-entity-events-v1 1.5.4+9244241690
	   |-- fabric-events-interaction-v0 0.4.34+562bff6e90
	   |-- fabric-events-lifecycle-v0 0.2.36+df3654b390
	   |-- fabric-game-rule-api-v1 1.0.24+b6b6abb490
	   |-- fabric-item-api-v1 1.6.6+b7d1888890
	   |-- fabric-item-groups-v0 0.3.39+9244241690
	   |-- fabric-key-binding-api-v1 1.0.25+5c4fce2890
	   |-- fabric-keybindings-v0 0.2.23+df3654b390
	   |-- fabric-lifecycle-events-v1 2.2.4+1b46dc7890
	   |-- fabric-loot-api-v2 1.1.13+83a8659290
	   |-- fabric-loot-tables-v1 1.1.16+9e7660c690
	   |-- fabric-message-api-v1 5.0.7+93d8cb8290
	   |-- fabric-mining-level-api-v1 2.1.24+33fbc73890
	   |-- fabric-models-v0 0.3.21+c6af733c90
	   |-- fabric-networking-api-v1 1.2.12+def3f86d90
	   |-- fabric-networking-v0 0.3.29+df3654b390
	   |-- fabric-object-builder-api-v1 4.2.2+d8ef690890
	   |-- fabric-particles-v1 1.0.14+4d0d570390
	   |-- fabric-recipe-api-v1 1.0.2+413cbbc790
	   |-- fabric-registry-sync-v0 0.9.33+9244241690
	   |-- fabric-renderer-api-v1 1.2.1+1adbf27790
	   |-- fabric-renderer-indigo 0.8.0+1adbf27790
	   |-- fabric-renderer-registries-v1 3.2.24+df3654b390
	   |-- fabric-rendering-data-attachment-v1 0.3.19+6e0787e690
	   |-- fabric-rendering-fluids-v1 3.0.11+4d0d570390
	   |-- fabric-rendering-v0 1.1.27+df3654b390
	   |-- fabric-rendering-v1 1.12.1+d8ef690890
	   |-- fabric-resource-conditions-api-v1 2.1.2+aae9039d90
	   |-- fabric-resource-loader-v0 0.8.4+edbdcddb90
	   |-- fabric-screen-api-v1 1.0.32+4d0d570390
	   |-- fabric-screen-handler-api-v1 1.3.8+1cc24b1b90
	   |-- fabric-sound-api-v1 1.0.2+c4f28df590
	   |-- fabric-textures-v0 1.0.24+aeb40ebe90
	   |-- fabric-transfer-api-v1 2.1.6+413cbbc790
	   \-- fabric-transitive-access-wideners-v1 1.3.3+08b73de490
	- fabric-language-kotlin 1.10.10+kotlin.1.9.10
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.10
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.10
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.10
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.10
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.22.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.0
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.0
	- fabrication 3.3.17+1.19
	   \-- lib39-deferral 1.1.1
	- fabricloader 0.14.22
	- fallingtrees 0.6-beta
	   \-- org_joml_joml 1.10.5
	- farmersdelight 1.19.2-1.3.10.1
	- farmersrespite 2.2.5
	   \-- porting_lib 2.1.815+1.19.2
	        \-- serialization_hooks 0.3.26
	- fast-portals 1.0.2
	- fastback 0.7.4+1.19.2
	   |-- com_googlecode_javaewah_javaewah 1.1.13
	   |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	   |-- net_i2p_crypto_eddsa 0.3.0
	   |-- org_apache_sshd_sshd-common 2.8.0
	   |-- org_apache_sshd_sshd-core 2.8.0
	   |-- org_eclipse_jgit_org_eclipse_jgit 6.2.0.202206071550-r
	   |-- org_eclipse_jgit_org_eclipse_jgit_ssh_apache 6.2.0.202206071550-r
	   |-- packet_tweaker 0.3.0+1.18.2
	   \-- server_translations_api 1.4.17+1.19.2
	        \-- packet_tweaker 0.3.0+1.18.2
	- fastquit 2.1.0+1.19-1.19.2
	- ferritecore 5.0.3
	- firespreadtweaks 2.3
	- flamearrows 1.19.2-11
	- flowerymooblooms 1.0.0
	- footprintparticle 0.4.0-mc1.19.2
	- forgeconfigapiport 4.2.11
	- framework 0.6.16
	   \-- org_javassist_javassist 3.29.2-GA
	- friendsandfoes 1.8.10
	   \-- com_github_llamalad7_mixinextras 0.2.0-rc.5
	- furnish 23
	- galosphere 1.19.2-1.3.0
	   \-- midnightlib 1.0.0
	- geckolib3 3.1.40
	   \-- com_eliotlash_mclib_mclib 20
	- geophilic 1.19-2.0.0b
	- grabbymobs 1.1
	- grapplemod 1.19.2-v1.7
	- graveyard 2.3.2
	- hardcorerevival 9.0.2
	- harvestwithease 6.0.1.4-final
	- herdspanic 1.0.6
	- immediatelyfast 1.2.6+1.19.2
	   |-- com_github_llamalad7_mixinextras 0.2.0-rc.5
	   \-- net_lenni0451_reflect 1.2.4
	- immersive_weathering 1.19.2-1.2.10
	- immersivesnow 1.3.0
	- indium 1.0.9+mc1.19.2
	- integrated_api 1.2.7+1.19.2
	- integrated_stronghold 1.0.2+1.19.2
	- interactic 0.1.11+1.19
	- inventoryprofilesnext 1.10.8
	- invmove 0.8.4
	- invmovecompats 0.3.0
	- iris 1.6.10
	   |-- io_github_douira_glsl-transformer 2.0.0-pre13
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- item_obliterator 1.2.0
	- jade 8.7.3
	- java 17
	- kiwi 8.3.4
	- krypton 0.2.1
	   \-- com_velocitypowered_velocity-native 3.1.2-SNAPSHOT
	- kubejs 1902.6.2-build.33
	- kubejs_create 1902.2.4-build.37
	- lambdabettergrass 1.3.0+1.19
	- lambdynlights 2.2.0+1.19.2
	   |-- pride 1.1.2+1.19
	   \-- spruceui 4.1.0+1.19.2
	- lazydfu 0.1.3
	- leashmod 1.0.5
	- leavemybarsalone 4.0.0
	- leavesbegone 4.0.1
	- libipn 4.0.0
	- lithium 0.11.1
	- logbegone 1.0.6
	- lootify 0.1.2+1.19
	- make_bubbles_pop 0.2.0-fabric
	- mcda 2.4.4
	- mcdar 1.5.3-1.19
	- mcdw 5.0.13-1.19
	   |-- enchant_giver 1.3.0
	   \-- reach-entity-attributes 2.3.0
	- mcwbridges 2.1.0
	- mcwroofs 2.2.4b
	- mcwwindows 2.2.0
	- memoryleakfix 1.1.2
	- microbloat 1.0.1
	- mindfuldarkness 4.0.9
	- minecraft 1.19.2
	- missingwilds 1.2.0-beta.2
	- mixin-conflict-helper 1.2.0
	- mixintrace 1.1.1+1.17
	- mobs_attempt_parkour 0.3-1.19-pre1
	- modelfix 1.8
	- modernfix 5.8.1+mc1.19.2
	- modmenu 4.2.0-beta.2
	- monsters_in_the_closet 1.0.3+1.19
	- moonlight 1.19.2-2.2.45
	- morepotions 1.0.2
	- mousewheelie 1.13.0+mc1.19.2
	   |-- amecsapi 1.5.1+mc22w17a
	   |-- coat 1.0.0-beta.20+mc22w17a
	   |-- tweed4_annotated 1.3.1+mc22w17a
	   |-- tweed4_base 1.7.1+mc22w17a
	   |-- tweed4_data 1.2.1+mc22w17a
	   |-- tweed4_data_hjson 1.1.1+mc22w17a
	   |-- tweed4_tailor_coat 1.1.3+mc22w17a
	   |-- tweed4_tailor_lang_json_descriptions 1.1.0+mc22w17a
	   \-- tweed4_tailor_screen 1.1.4+mc22w17a
	- mr_ctov_bygcompat 1.0
	- mr_ctov_farmersdelightcompat 2.1
	- mr_edf_remastered 4.3
	- musicnotification 1.0.0
	   \-- libgui 6.4.0+1.19
	        |-- jankson 4.1.1+j1.2.1
	        \-- libninepatch 1.1.0
	- musketmod 1.4.6
	- mutantmonsters 4.0.6
	- naturalist 3.0.4
	- neat 1.19-32-FABRIC
	   \-- fiber 0.23.0-2
	- nethersdelight 1.0.1
	   \-- disable_custom_worlds_advice 3.0
	- noenchantcap 2.2.4
	- opaccreatesupport 1.3.0
	- openpartiesandclaims 0.20.0
	- optigui 2.1.5
	   |-- optiglue 2.1.5-mc.1.19
	   |-- org_apache_commons_commons-text 1.10.0
	   \-- org_ini4j_ini4j 0.5.4
	- ostoverhaul 0.2.6
	- overflowingbars 4.0.1
	- overweight_farming 1.19.2-2.0.2-fabric
	   |-- midnightlib 1.0.0
	   |-- playerabilitylib 1.6.0
	   |-- reach-entity-attributes 2.3.0
	   \-- terraform-wood-api-v1 4.2.0
	- owo 0.9.3+1.19
	   \-- blue_endless_jankson 1.2.1
	- paginatedadvancements 2.2.1-1.19
	- passablefoliage 1.19-fabric-5.0.2
	- patchouli 1.19.2-77-FABRIC
	   \-- fiber 0.23.0-2
	- pehkui 3.7.8+1.14.4-1.20.1
	   \-- kanos_config 0.4.1+1.14.4-1.19.4
	- pettable 1.3.1
	- pickupnotifier 4.2.4
	- ping-wheel 1.5.1
	- player-animator 1.0.2
	- pressalttomeow 1.0.3
	- projectile_damage 3.2.1+1.19
	- promenade 2.7.1
	   \-- terraform-shapes-api-v1 4.0.0
	- puzzleslib 4.4.3
	   |-- cardinal-components-base 5.0.2
	   |-- cardinal-components-block 5.0.2
	   |-- cardinal-components-chunk 5.0.2
	   |-- cardinal-components-entity 5.0.2
	   \-- cardinal-components-world 5.0.2
	- qolfixes 2.0.7-1.19
	- raised 3.0.0
	- ratsmischief 1.4.0
	- reacharound 1.1.2
	- realisticbees 3.3
	- realisticfirespread 1.19-2
	- reeses-sodium-options 1.6.4+mc1.19.2-build.93
	- rhino 1902.2.2-build.280
	- rottencreatures 1.0.1
	   \-- reach-entity-attributes 2.3.0
	- rrls 1.19.2-3.1.1-fabric
	- scaffoldingdropsnearby 3.0
	- seamless 2.1.1
	- seasons 2.3+1.19
	- seasonsbygcompat 1.0-2.0.1.1
	- seasonsdelightcompat 1.0-1.3.9
	- seasonsextras 1.2-BETA+1.19
	- sihywtcamd 1.7.2+1.19
	- skeletalremains 1.3.3.2
	   \-- omega-config 1.3.0+1.19.2
	- skinlayers 1.5.2-mc1.19.1
	- sleep_tight 1.19.2-1.0.23
	- sleepwarp 2.0.0+1.19.2
	- sliceanddice 2.3.2
	- slimyboyos 5.0.0.5
	- smarterfarmers 1.19.2-1.7.1
	- smoothboot 1.19-1.7.1
	- smoothswapping 0.9.2
	- snowrealmagic 5.1.2
	- sodium 0.4.4+build.18
	- soulfired 3.2.0.1
	- sound_physics_remastered 1.19.2-1.2.1
	- spellbound 1.13.0
	   |-- mm 2.3
	   \-- modify-drops-api 0.4.0.2
	- spelunkery 1.19.2-0.2.5
	- spiceoffabric 1.6.2+mc1.19.2
	   |-- capsaicin 1.3.3+mc1.19.2
	   |-- coat 1.0.0-beta.20+mc22w17a
	   |-- tweed4_annotated 1.3.1+mc22w17a
	   |-- tweed4_base 1.7.1+mc22w17a
	   |-- tweed4_data 1.2.1+mc22w17a
	   |-- tweed4_data_hjson 1.1.1+mc22w17a
	   |-- tweed4_tailor_coat 1.1.3+mc22w17a
	   |-- tweed4_tailor_lang_json_descriptions 1.1.0+mc22w17a
	   \-- tweed4_tailor_screen 1.1.4+mc22w17a
	- stackdeobfuscator 1.4.1+03a1fe4
	   |-- dev_booky_common_ 1.4.1+03a1fe4
	   \-- net_fabricmc_mapping-io 0.3.0
	- starlight 1.1.1+fabric.ae22326
	- stylisheffects 4.3.4
	- supermartijn642configlib 1.1.8+a
	- supermartijn642corelib 1.1.15
	- supplementaries 1.19.2-2.3.24
	- terrablender 2.0.1.166
	- things 0.3.0+1.19
	   \-- reach-entity-attributes 2.3.0
	- tlc 1.0.0
	- toastmanager 1.0.1
	- toms_storage 1.5.9
	- tooltipfix 1.1.1-1.19
	- tradingpost 4.2.0
	- travelerstitles 1.19.2-Fabric-3.1.0
	- trinkets 3.4.2
	- twilightforest 4.2.357
	   |-- here-be-no-dragons 1.0.0
	   |-- javax_annotation_javax_annotation-api 1.3.2
	   |-- mm 2.3
	   \-- reach-entity-attributes 2.3.0
	- ubesdelight 0.1.4
	- universalenchants 4.2.15
	   \-- extensibleenums 4.0.0
	- vc_gliders 1.1.3
	   |-- cardinal-components-base 5.0.2
	   |-- cardinal-components-entity 5.0.2
	   \-- palladiumcore 1.19.2-1.4.1.1
	- vectorientation 1.0.1a
	- villagernames 5.2
	- visuality 0.5.6
	- visualworkbench 4.2.4
	- vmp 0.2.0+beta.7.30
	- weakerspiderwebs 3.2
	- wwfix 1.0.0
	- xaerominimap 23.8.4
	- xaeroworldmap 1.36.0
	- yet-another-config-lib 2.2.0-for-1.19.2
	- yigd 1.4.9
	- yippee 1.3.1-fabric
	- ysns 1.0.1
	- yungsapi 1.19.2-Fabric-3.8.9
	- yungsextras 1.19.2-Fabric-3.1.0
	- yuushya 2.1.1
	- zoomify 2.9.0
	   |-- dev_isxander_settxi_settxi-core 2.10.5
	   |-- dev_isxander_settxi_settxi-gui 2.10.5
	   |-- dev_isxander_settxi_settxi-kotlinx-serialization 2.10.5
	   \-- settxi-gui-yacl 2.10.5
</details>

**Logs:**
The following appears the first time I open the menu in latest.log:
`[17:26:23] [Render thread/ERROR]: Sound cannot be found in registry: extrasounds:item.place.spelunkery.rough_diamond
[17:26:23] [Render thread/ERROR]: Sound cannot be found in registry: extrasounds:item.place.spelunkery.rough_diamond
[17:26:25] [Render thread/ERROR]: Sound cannot be found in registry: extrasounds:item.select.spelunkery.rough_diamond
[17:26:31] [Render thread/WARN]: Unable to parse entry curios:curios_container: No matches found in registry minecraft:menu
[17:26:31] [Render thread/WARN]: Unable to parse entry tconstruct:*: No matches found in registry minecraft:menu
[17:26:31] [Render thread/WARN]: Unable to parse entry mekanism:*: No matches found in registry minecraft:menu`

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Place diamond grindstone
2. Get rough gem
3. Attempt to right click rough gem onto grindstone

**Expected behavior:**
Get a polished gem and xp.

**Comment by CactusDuud** [comment]
I've tried a separate save with just Spelunkery and Extra Sounds and that doesn't seem to cause the same bug.

**Comment by AstralOrdana** [comment]
incompat determined to be with kubejs, moved to issue https://github.com/AstralOrdana/Spelunkery/issues/151
