### ISSUE TITLE
Stone Stripes Features generation incompatible with William Wyther's Expanded Ecosphere

### ISSUE THREAD

**Issue by AzrannAVANA** [AstralOrdana/Spelunkery#150]
**Describe the bug:**
With Stone Stripes Features enabled and WWEE installed (with blobs generation on), no andesite/diorite/... blobs nor stripes generate besides granite. Most likely due to Wyther's having a custom Underground biome.

**Versions:**
Minecraft version: 1.20.1
Spelunkery version: 1.20.1-0.3.4
Moonlight Lib version: forge_1.20-2.8.67
Forge version: 1.20.1-47.2.1

**Other mods:**
[Modlist.txt](https://github.com/AstralOrdana/Spelunkery/files/13629120/Modlist.txt)
Isn't it all already in the latest.txt?

**Logs:**
Please provide the following logs:
From .minecraft/logs :  "latest.log" as well as "debug.log" if it exists. From .minecraft : "launcher_log" as well as a
file that starts with "hs_err" if it exists. Note: Double check that the logs are from the correct time. ex, don't give
us a log from a month ago because you forgot to check the date.
File too big to upload, contact if truly necessary

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Install WWEE, Spelunkery and Moonlight Lib
2. Set WWEE config setting Remove ore blobs to false
3. Generate a world and observe that all stone variants have not generated.

**Expected behavior:**
Spelunkery's stone stripes should generate in the the world.

**Screenshots:**
![image](https://github.com/AstralOrdana/Spelunkery/assets/112041895/a8d19214-c9ce-489b-974c-f35a60854c99)

**Additional info:**
The modlist is VERY extensive, but I suppose WWEE and Spelunkery are responsible for the lack of Andesite in worldgen

**Comment by AstralOrdana** [comment]
fixed for 0.3.5
