### ISSUE TITLE
[Mod Compatibility] Raw Nugget and M'ores Support for Galosphere Silver

### ISSUE THREAD

**Issue by DJChaos42** [AstralOrdana/Spelunkery#151]
**Feature:**

When Galosphere is installed, Raw Silver Nuggets and Silver Ore Variants should be enabled in the same way that they are when Oreganized is installed.

**Alternatives:**

Having a way to forcibly enable silver and other compatibility content via a config or tag even when the mods they're intended for aren't installed could be a useful tool for pack developers.

For a more extensive alternative, maybe an inverted "forge:tag_empty" condition could be used to detect whether to enable things like recipes and ore generation instead of only relying on "forge:mod_loaded"? That probably wouldn't work for things like altering loot tables for specific mods' blocks though.

**Additional info:**

The alternatives listed might be a bit too much to be realistic. Honestly I'm just hoping for more compatibility between two really cool underground-themed mods!

**Comment by AstralOrdana** [comment]
galosphere support is not planned
