### ISSUE TITLE
Grindstone polishing does not work when KubeJS is installed

### ISSUE THREAD

**Issue by armuell** [AstralOrdana/Spelunkery#152]
**Describe the bug:**
When KubeJS is installed, right clicking either a grindstone or diamond grindstone with a rough resource opens the grindstone ui instead of polishing the gem.

**Versions: **
Minecraft version: 1.20.1
Fabric version: 0.15.1

Spelunkery version: 0.3.4
Moonlight Lib version: 2.8.68
Fabric API version: 0.91.0
Architectury version: 9.1.12
Rhino version: 2001.2.2-build18
KubeJS version: 2001.6.4-build114

**Other mods:**
Only the mods listed above were installed

**Logs:**
*Even if the game does not crash they may be useful!*
[latest.log](https://github.com/AstralOrdana/Spelunkery/files/13678599/latest.log)

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Hold Rough Cinnabar in your main hand
2. Right Click while looking at either a Grindstone or Diamond Grindstone
3. The GUI for the Grindstone will open

**Expected behavior:**
The Cinnabar to be polished and the Grindstone GUI to not be opened

**Comment by neutralboolean** [comment]
Is there any update on this or is this something that needs to be addressed from the KubeJS side?

**Comment by Shywizz** [comment]
Has this been released yet ?

Im willing to bet a script or two on the KubeJS side could be used as a hotfix for this but proper compatibility would be appreciated.

**Comment by AstralOrdana** [comment]
fixed for 0.3.11

**Comment by neutralboolean** [comment]
Cheers!
