### ISSUE TITLE
Spring Water can't burrow Packed Mud 

### ISSUE THREAD

**Issue by bucketBrian** [AstralOrdana/Spelunkery#155]
**Describe the bug:**
Packed Mud will be naturally generated as large stripes in desert. Therefore it should be also seens as "natural block" to Spring Water.

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version: 1.20.1
Spelunkery version: 0.3.5
Moonlight Lib version: 2.8.67
Fabric API / QSL / Forge version: 47.2.5

**Other mods:**
none

**Logs:**
Not needed

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. create a boiling Spring Water.
2. put the Packed Mud on the top of the Spring Water
3. 

**Expected behavior:**
Spring Water burrow through the Packed Mud, As what it should do to the other natural blocks (even terracottas are works.)

**Screenshots:**
Not needed

**Additional info:**

**Comment by AstralOrdana** [comment]
no, its working as intended as the spring water uses the `OVERWORLD_CARVER_REPLACEABLES` tag
