### ISSUE TITLE
Magnetic Compass Never Stops Being Drawn Toward Magnetite

### ISSUE THREAD

**Issue by CraftyZombie** [AstralOrdana/Spelunkery#156]
**Describe the bug:**
- Default config makes the range of Magnetic Compass's attraction to a Magnetite Block 64 blocks.
- Attraction only begins within a 30 block range.
- Attraction never ends, even when going more than 64 blocks away in the X and Z directions.
- When a new Magnetite Block is closer, the Magnetic Compass plays a sound, but it still remains attracted to the old Magnetite Block instead of the new one.

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version: 1.20.1
Spelunkery version: 1.20.1-0.3.4
Moonlight Lib version: 1.20-2.8.67
Fabric API / QSL / Forge version: Forge 47.2.17

**Other mods:**
Only Moonlight Library and Spelunkery are installed.

**Logs:**
[debug.log](https://github.com/AstralOrdana/Spelunkery/files/13721948/debug.log)
[latest.log](https://github.com/AstralOrdana/Spelunkery/files/13721949/latest.log)
*launcher_log and hs_err do not exist.

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Install specified versions.
2. Create new world.
3. Obtain a Magnetic Compass.
4. Place down a Magnetite Block.
5. Try to leave the range specified in the config. The Magnetic Compass will not return to normal.
6. Place down a new Magnetite Block. The attraction will not switch.
7. Break that new Magnetite Block and give yourself another compass. Notice that upon returning to the original block, attraction will not start until around 30 blocks away.

**Expected behavior:**
- I expected that Magnetite Block attraction from the Magnetic Compass would begin and end at 64 blocks distance, as specified in the common config. 
- I also expected that placing a new Magnetite Block that was closer to the compass would change its attraction.

**Comment by AstralOrdana** [comment]
this is just the nature of game events, hence why the shift-right click function of the magnetic compass is to clear the current magnetite

**Comment by CraftyZombie** [comment]
I'm confused. This is or isn't _intended_ behavior of the mod? 

If the magnetic compass doesn't automatically refresh its magnetite attraction, then this effectively removes the purpose/appeal of the Lodestone block, does it not?
