### ISSUE TITLE
Z-fighting on channels/sluices

### ISSUE THREAD

**Issue by donkeyrat** [AstralOrdana/Spelunkery#157]
**Describe the bug:**
There is z-fighting on the insides of wooden and stone channels and sluices. Might wanna tweak the model a bit.

**Comment by TutorialGuy** [comment]
I can't find any information at all on channels and sluices from this mod. JEI shows some activity between sluice, water and for example dirt or gravel and we get a result, but I can't find any information how exactly to do it.

**Comment by steve-the-player** [comment]
> I can't find any information at all on channels and sluices from this mod. JEI shows some activity between sluice, water and for example dirt or gravel and we get a result, but I can't find any information how exactly to do it.

https://github.com/AstralOrdana/Spelunkery/issues/231#issuecomment-2185151853

**Comment by AstralOrdana** [comment]
unfortunately, due to their symmetry its not possible
