### ISSUE TITLE
Feature Request: Config for disabling recovery compasses staying in inventories upon death

### ISSUE THREAD

**Issue by donkeyrat** [AstralOrdana/Spelunkery#159]
Self-explanatory.

**Comment by AstralOrdana** [comment]
use the item tag

**Comment by TheVillain-Inc** [comment]
Sorry but I'm confused; 'use the item tag'

Not sure what you mean by this, but I also need to disable this feature as its causing issues with other mods that touch the Recovery Compass.

**Comment by tehgreatdoge** [comment]
You need to remove the recovery compass from the #spelunkery:keep_on_death item tag.

**Comment by TheVillain-Inc** [comment]
for the life of me I cant get that to happen. 

{
  "remove": 

  "values": [
      "minecraft:recovery_compass"
  ]
}


with matching directory to the spelunkery json that adds 'keep on death' to the recovery compass. Also cannot find any working examples to examine :(

**Comment by AstralOrdana** [comment]
thats not a valid tag
https://minecraft.wiki/w/Tag#JSON_format

**Comment by AstralOrdana** [comment]
```
{
  "replace": true,
  "values": [
  ]
}

**Comment by TheVillain-Inc** [comment]
Sigh. 
Was looking at forge documentation and got my wires crossed for functions. 

Thankyou for helping me on this,  I may never get the last 40 minutes of my life back - but I learned something. Appreciate your time
