### ISSUE TITLE
Nethernite Charm crash?

### ISSUE THREAD

**Issue by itsdinkd** [AstralOrdana/Spelunkery#16]
**Describe the bug:**
Can't really tell exactly what happened as I found this from 2 days ago in my packs dedicated server in crash reports. looks like it involved Netherite Charm

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version: 1.19.2
Spelunkery version: 0.1.4
Moonlight Lib version: 2.1.31 
Supplementary: 2.2.44
Fabric API / QSL / Forge version:: 0.71

**Other mods:**
in crash report

**Logs:**
*Even if the game does not crash they may be useful!*
https://gist.github.com/itsdinkd/3de9225a8fe75e292f4049609ac37a24

**Comment by AstralOrdana** [comment]
More information on how this crash occurred is needed

**Comment by itsdinkd** [comment]
https://github.com/itsdinkd/AQM2/issues/151

**Comment by AstralOrdana** [comment]
can this be replicated in the newest version?

**Comment by itsdinkd** [comment]
unable to launch latest version in aqm2.
https://gist.github.com/itsdinkd/27dac03811e35f95306d6289389c2c9c

**Comment by AstralOrdana** [comment]
fixed for next update

**Comment by itsdinkd** [comment]
Can you port the fix to fabric please? currently seeing 0.1.6 only out for forge. also this should probably remain opened until I can test Netherite Charm on latest version

**Comment by AstralOrdana** [comment]
the source of the problem was determined and fixed for 0.1.7

**Comment by itsdinkd** [comment]
Got it. any plans on releasing that update for fabric today? I'm trying to get this modpack update out and would rather not update two times back to back if possible

**Comment by AstralOrdana** [comment]
commenting on a closed feature request is about the worst way to ask for an update that I can imagine
https://www.curseforge.com/minecraft/mc-mods/spelunkery/files/all

**Comment by itsdinkd** [comment]
Too bad this isn't a feature request

**Comment by AstralOrdana** [comment]
mfw someone makes a typo and their statement is completely invalidated

**Comment by itsdinkd** [comment]
Saying a "feature request" is a typo for a "issue" is hilarious. Just say you made a mistake.

**Comment by itsdinkd** [comment]
Either way good luck with your downloads you just lost your biggest dependency

**Comment by AstralOrdana** [comment]
I linked the downloads page because I had already published an update before you even asked

**Comment by AstralOrdana** [comment]
I mark issues as fixed when I fix them, I'm sorry that I can't account for every modpack's schedule. I develop the pack literally on my own so people constantly bugging me for etas can get annoying

**Comment by KaedeInSpace** [comment]
> 

At this point you are just harassing and not productive. Rather it is not helping the process of the issue resolved, so please refrain from spamming like so as it is not helpful.

**Comment by Wolfen198** [comment]
> 

So you lost literally all of your mod team, over half your playerbase for your server because of your bullying, and you decide instead of looking back and figuring out how badly you fucked up, you're now bullying even _more_ people.  You really are pathetic.

**Comment by Wolfen198** [comment]
Astral, just so you know, Dink lost his entire moderator team and the majority of his players specifically due to behavior like this.  This is just his attempt to feel better about himself by bullying you.  He's as two faced as they come.
