### ISSUE TITLE
Disabling M'ores makes important tags not load

### ISSUE THREAD

**Issue by ElRichiRicon** [AstralOrdana/Spelunkery#162]
**Describe the bug:**
Tags like "minecraft:mineable/pickaxe" stop loading if M'ores are disabled. This makes the game near unplayable in survival.

**Versions:**
Minecraft version: 1.20.1
Spelunkery version: 0.3.5
Moonlight Lib version: 2.8.81
Forge version: 47.2.19

**Other mods:**
![image](https://github.com/AstralOrdana/Spelunkery/assets/45831667/25bc5169-d7c0-4545-91c9-adc16a1a91f1)

**Logs:**
[latest.log](https://pastebin.com/nAvHRMMT)

I think this part is important:

[13ene2024 22:08:01.957] [Worker-Main-7/ERROR] [net.minecraft.tags.TagLoader/]: Couldn't load tag minecraft:mineable/pickaxe as it is missing following references: spelunkery:andesite_coal_ore (from spelunkery-1.20.1-0.3.5-forge.jar), 

...and then lists all of the other m'ores.

Also, the log is filled with something about loot tables and makes the file too big. I cut most of them.

**To Reproduce:**
1. Disable m'ores in the config
2. Start the game
3. Try to mine stone

**Comment by AstralOrdana** [comment]
fixed in 0.3.6
