### ISSUE TITLE
Lapis lazuli shard recipe conflict with vanilla blue dye recipe

### ISSUE THREAD

**Issue by Abbie5** [AstralOrdana/Spelunkery#164]
**Describe the bug:**
A clear and concise description of what the bug is. Include as much information as you can. Images are often helpful, especially screenshots of the F3 debug menu.

1 lapis lazuli in a crafting table produces blue dye in vanilla, but with spelunkery it produces 9 lapis lazuli shards, making it impossible to obtain blue dye from lapis lazuli

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version: 1.20.1
Spelunkery version: 1.20.1-0.3.5
Moonlight Lib version: 1.20-2.8.84
Fabric API / QSL / Forge version: 0.91.0+1.20.1

**Other mods:**
List all mods that you're using; could be in the form of a list of the filenames, a crash report list, a screenshot of
the mods folder, etc. Just make sure all mods used are known!

emi 1.1.0+1.20.1+fabric

**Logs:**
*Even if the game does not crash they may be useful!*
Please provide the following logs:
From .minecraft/logs :  "latest.log" as well as "debug.log" if it exists. From .minecraft : "launcher_log" as well as a
file that starts with "hs_err" if it exists. Note: Double check that the logs are from the correct time. ex, don't give
us a log from a month ago because you forgot to check the date.

https://0x0.st/H0Dm.txt

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. put a lapis lazuli in a crafting table
2. observe
3. 

**Expected behavior:**

blue dye in the output slot

**Screenshots:**
If applicable, add screenshots to help explain your problem. https://screenshot.help/

![image](https://github.com/AstralOrdana/Spelunkery/assets/43531981/55106e42-553a-4491-bade-c5a3816600fd)

**Additional info:**
Add any other information that might be needed.

**Comment by AstralOrdana** [comment]
use of the polymorph mod allows you to switch between conflicting recipes, in a future version blue dye will be obtained by grinding lapis lazuli

**Comment by AstralOrdana** [comment]
added for 0.3.10
