### ISSUE TITLE
Using a bottle o'dimensional tears in the Nether or End will remove all your experience levels; they are restored with a relog

### ISSUE THREAD

**Issue by jonathansharpe** [AstralOrdana/Spelunkery#165]
**Describe the bug:**
When using a Bottle o'Dimensional Tears to teleport you back to your spawnpoint in either the Nether or the End, all your experience levels are gone. However, upon logging out and back into the game, the levels are back.

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version: 1.20.1
Spelunkery version: 1.20.1-0.3.5
Moonlight Lib version: 1.20-2.8.82
Fabric API / QSL / Forge version: Fabric

**Other mods:**
(copied from the log)
`- amecs 1.3.10+mc.1.20.1
	   \-- amecsapi 1.4.0+mc1.20-pre1
	- animatica 0.6+1.20
	- another_furniture 1.20.1-3.0.1
	- antighost 1.20-fabric0.83.0-1.1.5
	   \-- crowdin-translate 1.4+1.19.3
	- appleskin 2.5.1+mc1.20
	- architectury 9.1.12
	- artifacts 9.2.0
	   |-- cardinal-components-base 5.2.2
	   |-- cardinal-components-entity 5.2.2
	   |-- expandability 9.0.0
	   \-- step-height-entity-attribute 1.2.0
	- athena 3.1.1
	- barteringstation 8.0.0
	- bclib 3.0.14
	   \-- wunderlib 1.1.5
	- bedspreads 6.2.0+1.20.1
	- bettercombat 1.8.3+1.20.1
	- betterdeserttemples 1.20-Fabric-3.0.3
	   \-- org_reflections_reflections 0.10.2
	- betterdungeons 1.20-Fabric-4.0.3
	- betterend 4.0.11
	- betterfortresses 1.20-Fabric-2.0.5
	- betterjungletemples 1.20-Fabric-2.0.4
	- bettermineshafts 1.20-Fabric-4.0.4
	- betternether 9.0.10
	- betteroceanmonuments 1.20-Fabric-3.0.4
	- betterstrongholds 1.20-Fabric-4.0.3
	- betterwitchhuts 1.20-Fabric-3.0.3
	- botarium 2.3.1
	   \-- team_reborn_energy 3.0.0
	- chesttracker 1.1.23
	   |-- libgui 8.0.0+1.20
	   |    |-- jankson 5.0.1+j1.2.2
	   |    \-- libninepatch 1.2.0
	   \-- whereisit 1.14.17
	- chipped 3.0.1
	- chunkloaders 1.2.8+a
	- citresewn 1.1.3+1.20
	   \-- citresewn-defaults 1.1.3+1.20
	- cloth-config 11.1.118
	   \-- cloth-basic-math 0.6.1
	- comforts 6.3.4+1.20.1
	   \-- spectrelib 0.13.14+1.20.1
	        |-- com_electronwill_night-config_core 3.6.5
	        \-- com_electronwill_night-config_toml 3.6.5
	- continuity 3.0.0-beta.4+1.20.1
	- create 0.5.1-d-build.1161+mc1.20.1
	   |-- com_google_code_findbugs_jsr305 3.0.2
	   |-- flywheel 0.6.9-1
	   |-- milk 1.2.60
	   |    \-- dripstone_fluid_lib 3.0.2
	   |-- porting_lib_accessors 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    \-- porting_lib_gametest 2.1.1127+1.20
	   |-- porting_lib_base 2.1.1127+1.20
	   |    |-- porting_lib_attributes 2.1.1127+1.20
	   |    |-- porting_lib_common 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    |-- porting_lib_gametest 2.1.1127+1.20
	   |    |-- porting_lib_lazy_registration 2.1.1127+1.20
	   |    \-- porting_lib_utility 2.1.1127+1.20
	   |-- porting_lib_brewing 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    \-- porting_lib_gametest 2.1.1127+1.20
	   |-- porting_lib_client_events 2.1.1127+1.20
	   |    |-- mm 2.3
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    \-- porting_lib_gametest 2.1.1127+1.20
	   |-- porting_lib_entity 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    |-- porting_lib_gametest 2.1.1127+1.20
	   |    \-- porting_lib_mixin_extensions 2.1.1127+1.20
	   |-- porting_lib_extensions 2.1.1127+1.20
	   |    |-- porting_lib_attributes 2.1.1127+1.20
	   |    |-- porting_lib_common 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    \-- porting_lib_gametest 2.1.1127+1.20
	   |-- porting_lib_fake_players 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    \-- porting_lib_gametest 2.1.1127+1.20
	   |-- porting_lib_models 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    |-- porting_lib_gametest 2.1.1127+1.20
	   |    \-- porting_lib_model_loader 2.1.1127+1.20
	   |-- porting_lib_networking 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    \-- porting_lib_gametest 2.1.1127+1.20
	   |-- porting_lib_obj_loader 2.1.1127+1.20
	   |    |-- porting_lib_attributes 2.1.1127+1.20
	   |    |-- porting_lib_common 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    |-- porting_lib_gametest 2.1.1127+1.20
	   |    \-- porting_lib_model_loader 2.1.1127+1.20
	   |-- porting_lib_tags 3.0
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    \-- porting_lib_gametest 2.1.1127+1.20
	   |-- porting_lib_tool_actions 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    \-- porting_lib_gametest 2.1.1127+1.20
	   |-- porting_lib_transfer 2.1.1127+1.20
	   |    |-- porting_lib_core 2.1.1127+1.20
	   |    \-- porting_lib_gametest 2.1.1127+1.20
	   |-- reach-entity-attributes 2.4.0
	   \-- registrate-fabric 1.3.62-MC1.20.1
	        |-- porting_lib_data 2.1.1090+1.20
	        \-- porting_lib_model_generators 2.1.1090+1.20
	             \-- porting_lib_model_materials 2.1.1090+1.20
	- create_enchantment_industry 1.2.11
	   \-- create_dragon_lib 1.4.1
	- create_new_age 1.1.1
	- createdeco 2.0.0-fabric-1.20.1
	- cull-less-leaves 1.3.0
	- delightfulcreators 1.1.8
	- distanthorizons 2.0.1-a
	   |-- fabric-api-base 0.4.30+7abfd51577
	   |-- fabric-events-interaction-v0 0.6.1+e91849a877
	   |-- fabric-lifecycle-events-v1 2.2.21+b3afc78b77
	   |-- fabric-networking-api-v1 1.3.10+eeb8eb3677
	   |-- fabric-rendering-v1 3.0.7+b3afc78b77
	   \-- fabric-resource-loader-v0 0.11.9+132c48c177
	- dummmmmmy 1.20-1.8.13
	- dungeons_arise 2.1.57
	- dynamic_fps 3.3.2
	- easyanvils 8.0.1
	- easymagic 8.0.1
	- emi 1.0.30+1.20.1+fabric
	- emi_enchanting 0.1.0+1.20.1
	- emi_loot 0.6.5+1.20.1
	- emiffect 1.1.2+mc1.20.1
	- emitrades 1.2.1+mc1.20.1
	   \-- org_quiltmc_parsers_json 0.2.1
	- entity_model_features 1.2.1
	- entity_texture_features 5.1.2
	   \-- org_apache_httpcomponents_httpmime 4.5.10
	- entityculling 1.6.2-mc1.20.1
	- essentialgui 1.9.1+1.20.1
	- everycomp 1.20-2.6.23
	- extended_drawers 2.1.1+mc.1.20.1
	   |-- config_toolkit 1.0.0
	   |    |-- io_determann_shadow-api-17 0.1.1
	   |    \-- net_fabricmc_javapoet 0.1.0
	   |-- graphlib 1.4.0+1.20
	   |    |-- kmodlib-overlay 0.2.12+1.20
	   |    \-- libnetworkstack 0.10.0
	   \-- noindium 1.1.0+1.20
	- extendedgears 2.1.0-1.20.1-0.5.1.c-fabric
	- extra-mod-integrations 0.4.2+1.20.1
	- fabric-api 0.91.0+1.20.1
	   |-- fabric-api-lookup-api-v1 1.6.35+4d8536c977
	   |-- fabric-biome-api-v1 13.0.12+215bbe9677
	   |-- fabric-block-api-v1 1.0.10+92a0d36777
	   |-- fabric-block-view-api-v2 1.0.0+92a0d36777
	   |-- fabric-blockrenderlayer-v1 1.1.40+b3afc78b77
	   |-- fabric-client-tags-api-v1 1.1.1+97bb207577
	   |-- fabric-command-api-v1 1.2.33+f71b366f77
	   |-- fabric-command-api-v2 2.2.12+b3afc78b77
	   |-- fabric-commands-v0 0.2.50+df3654b377
	   |-- fabric-containers-v0 0.1.63+df3654b377
	   |-- fabric-content-registries-v0 4.0.10+57aed33f77
	   |-- fabric-convention-tags-v1 1.5.4+a1a980da77
	   |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe77
	   |-- fabric-data-generation-api-v1 12.3.3+d7b148e077
	   |-- fabric-dimensions-v1 2.1.53+8536527b77
	   |-- fabric-entity-events-v1 1.5.22+b3afc78b77
	   |-- fabric-events-lifecycle-v0 0.2.62+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.39+ae9f657a77
	   |-- fabric-item-api-v1 2.1.27+b3afc78b77
	   |-- fabric-item-group-api-v1 4.0.11+d7b148e077
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da77
	   |-- fabric-keybindings-v0 0.2.34+df3654b377
	   |-- fabric-loot-api-v2 1.2.0+96dfa95977
	   |-- fabric-loot-tables-v1 1.1.44+9e7660c677
	   |-- fabric-message-api-v1 5.1.8+d7b148e077
	   |-- fabric-mining-level-api-v1 2.1.49+b3afc78b77
	   |-- fabric-model-loading-api-v1 1.0.2+709a987177
	   |-- fabric-models-v0 0.4.1+9386d8a777
	   |-- fabric-networking-v0 0.3.50+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.2+4ee0bc6077
	   |-- fabric-particles-v1 1.1.1+201a23a077
	   |-- fabric-recipe-api-v1 1.0.20+b3afc78b77
	   |-- fabric-registry-sync-v0 2.3.2+4df89eb277
	   |-- fabric-renderer-api-v1 3.2.0+39a511ba77
	   |-- fabric-renderer-indigo 1.5.0+39a511ba77
	   |-- fabric-renderer-registries-v1 3.2.45+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.36+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.27+b3afc78b77
	   |-- fabric-rendering-v0 1.1.48+df3654b377
	   |-- fabric-resource-conditions-api-v1 2.3.7+29de845d77
	   |-- fabric-screen-api-v1 2.0.7+b3afc78b77
	   |-- fabric-screen-handler-api-v1 1.3.29+b3afc78b77
	   |-- fabric-sound-api-v1 1.0.12+b3afc78b77
	   |-- fabric-transfer-api-v1 3.3.3+c81d263177
	   \-- fabric-transitive-access-wideners-v1 4.3.0+6c31357e77
	- fabric-language-kotlin 1.10.17+kotlin.1.9.22
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.22
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.23.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.2
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.2
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.2
	- fabricloader 0.15.3
	   \-- mixinextras 0.3.2
	- farmersdelight 1.20.1-1.4.3
	- ferritecore 6.0.1
	- forgeconfigapiport 8.0.0
	- garnished 1.5.1-hotfix-1+1.20.1
	   \-- terraform-wood-api-v1 7.0.1
	- geckolib 4.4
	   \-- com_eliotlash_mclib_mclib 20
	- iceberg 1.1.11
	- illagerinvasion 8.0.3
	   \-- extensibleenums 7.0.1
	- immediatelyfast 1.2.8+1.20.4
	   \-- net_lenni0451_reflect 1.3.1
	- immersive_melodies 0.1.0+1.20.1
	- infinitybuttons 4.0.1-mc1.20.1
	- inmis 2.7.2-1.20.1
	   \-- omega-config 1.2.3-1.18.1
	- inmisaddon 1.0.4
	- inventoryprofilesnext 1.10.9
	- jade 11.7.0
	- jadeaddons 5.2.3
	- java 17
	- jei 15.2.0.27
	- keep_some_inventory 1.3.0
	- kubejs 2001.6.4-build.127
	- lambdynlights 2.3.2+1.20.1
	   |-- pride 1.2.0+1.19.4
	   \-- spruceui 5.0.0+1.20
	- lazydfu 0.1.3
	- leavesbegone 8.0.0
	- legendarytooltips 1.4.4
	- libipn 4.0.1
	- lithium 0.11.2
	- lootr 0.7.29.75
	- malilib 0.16.3
	- memoryleakfix 1.1.5
	- minecraft 1.20.1
	- minihud 0.27.0
	- mobcaptains 3.1.1
	- modmenu 7.2.2
	- moonlight 1.20-2.8.82
	- naturalist 4.0.3
	- nnvf 0.1.3_1.20
	- numismatic-overhaul 0.2.12+1.20.1
	   \-- stacc 1.7.0
	- optigui 2.1.7
	   |-- optiglue 2.1.7-mc.1.19.3
	   |-- org_apache_commons_commons-text 1.10.0
	   \-- org_ini4j_ini4j 0.5.4
	- origins 1.10.0
	   \-- apoli 2.9.0
	        |-- additionalentityattributes 1.3.0+1.20.0
	        |-- calio 1.11.0
	        \-- playerabilitylib 1.8.0
	- owo 0.11.2+1.20
	   \-- blue_endless_jankson 1.2.2
	- player-animator 1.0.2-rc1+1.20
	- polymorph 0.49.1+1.20.1
	   |-- cardinal-components-block 5.2.1
	   |-- cardinal-components-item 5.2.1
	   \-- spectrelib 0.13.14+1.20.1
	        |-- com_electronwill_night-config_core 3.6.5
	        \-- com_electronwill_night-config_toml 3.6.5
	- pottery 1.0.1
	- prism 1.0.5
	- puzzleslib 8.1.13
	   \-- puzzlesaccessapi 8.0.7
	- railways 1.5.1+fabric-mc1.20.1
	   \-- mm 2.3
	- reinfbarrel 2.4.1+1.20
	   \-- reinfcore 3.1.2+1.20
	- reinfchest 2.4.2+1.20
	   \-- reinfcore 3.1.2+1.20
	- reinfshulker 2.5.0+1.20
	   \-- reinfcore 3.1.2+1.20
	- resourcefullib 2.1.20
	   |-- com_teamresourceful_bytecodecs 1.0.2
	   \-- com_teamresourceful_yabn 1.0.3
	- rhino 2001.2.2-build.18
	- searchables 1.0.2
	- searchlight 1.1.11
	- simplemagnets 1.1.10
	- simplyswords 1.51.5-1.20.1
	   \-- spruceui 5.0.0+1.20
	- smoothswapping 0.9.3.1
	- spelunkery 1.20.1-0.3.5
	- suggestion_tweaker 1.20-1.5.1
	- supermartijn642configlib 1.1.8+a
	- supermartijn642corelib 1.1.16
	- supplementaries 1.20-2.7.23
	   \-- mixinsquared 0.1.1
	- toms_storage 1.6.5
	- tooltipfix 1.1.1-1.20
	- trade_cycling 1.20.1-1.0.10
	- tradingpost 8.0.1
	- travelerstitles 1.20-Fabric-4.0.1
	- trinkets 3.7.1
	- tweakeroo 0.17.1
	- weaponmaster 3.0.5
	- wwoo 2.0.0
	- xaerominimap 23.9.3
	- xaeroplus 1.20.1
	   \-- net_lenni0451_lambdaevents 2.4.0
	- xaeroworldmap 1.37.2
	- yet_another_config_lib_v3 3.2.1+1.20
	   |-- com_twelvemonkeys_common_common-image 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_common_common-io 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_common_common-lang 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-core 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0-SNAPSHOT
	   \-- org_quiltmc_parsers_gson 0.2.1
	- yungsapi 1.20-Fabric-4.0.2
	   \-- org_javassist_javassist 3.29.2-GA
	- yungsbridges 1.20-Fabric-4.0.3
	- yungsextras 1.20-Fabric-4.0.3
	- zoomify 2.11.2
	   |-- com_akuleshov7_ktoml-core-jvm 0.4.1
	   |-- dev_isxander_settxi_settxi-core 2.10.6
	   \-- dev_isxander_settxi_settxi-kotlinx-serialization 2.10.6
`

**Logs:**
*Even if the game does not crash they may be useful!*
Please provide the following logs:
https://mclo.gs/TUl8NUs

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Log into your Minecraft world
2. Ensure you have some experience and a Bottle o'Dimensional Tears
3. Enter the Nether or End
4. Consume the Bottle o'Dimensional Tears
5. Upon teleportation back to your spawnpoint, you'll notice your levels are gone
6. Exit the world
7. Log back into the world
8. Your levels are now back

**Expected behavior:**
I expected my experience levels to be retained immediately upon teleportation back to my spawnpoint.

**Comment by AstralOrdana** [comment]
this is an issue with vanilla
