### ISSUE TITLE
Progression Reborn Compat

### ISSUE THREAD

**Issue by fluffyxox** [AstralOrdana/Spelunkery#167]
**Feature:**

Progression Reborn replaces metal ore drops (Iron, Gold, Copper) with raw nuggets that behave identically to Spelunkery's raw nuggets. (9 in craft grid makes raw ore, smelting nuggets makes vanilla)
However, the ore variants added by Spelunkery such as Diorite Iron Ore, drop raw ore. I would like the two mods to work together, replacing raw metal drops with raw nuggets.
From my perspective, it'd be smartest to replace M'ores drops with Prog Reborn metal nuggets, then have the create copper nugget compat implemented on Prog Reborn's side.

**Alternatives:**

This is the most plausible method I can think of, other than seeing if it can be implemented from Prog Reborns's side

**Additional info:**

Any other info should go here.  With more complicated features, it is geneally worth mentioning even the smallest of details you wish to see if the suggestion is approved and implemented.

**Comment by Rebel459** [comment]
Adding to this, for consistency's sake you'd also need m'ores variants for Nether Rose Ore

**Comment by AstralOrdana** [comment]
not planned
