### ISSUE TITLE
Create Dimensional Tears Bottle Unequivalent Filling & Emptying

### ISSUE THREAD

**Issue by Stereo528** [AstralOrdana/Spelunkery#168]
**Describe the bug:**
When filling a bottle via Spout it takes 333mb/27000 droplets to fill, however if you were to empty the same bottle, you would only get 111mb/9000 droplets in return. 

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version:1.20,1
Spelunkery version:0.3.5
Moonlight Lib version:2.8.82
Fabric API / QSL / Forge version:QSL 7.2.2 (FAPI 0.88.1)

**Other mods:**
Create, EMI

**Logs:**
irrelevant

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Empty a Bottle O'Dimensional Tears fluid via Item Drain from Create
2. Move the fluid into a Spout with a depot/belt under it
3. place the empty bottle under the Spout, and it will not fill the bottle
Looking at the fluid behavior will reveal you only have 111mb instead of the 333mb needed

**Expected behavior:**
You should be given 333mb into the create system to immediately pour back into the bottle or onto a piece of obsidian

**Screenshots:**
![javaw_aNrHIO2mDQ](https://github.com/AstralOrdana/Spelunkery/assets/52116771/75a63276-6f29-4aef-9d2a-88ae7320d7bf)
![javaw_Tkrttajs6s](https://github.com/AstralOrdana/Spelunkery/assets/52116771/15e4e63c-4dd3-45da-9084-5381fbe09b3e)

**Additional info:**
According to Commit 08e93a1 (titled 0.3.4) Was the change from mb in Create recipes to Droplets, however in this change all recipes went from being equivalent (250mb) to being 9000 droplets in the emptying recipe, and 27000 droplets in all other recipes. I do not believe this to be intentional, but if it is could there be an explanation?

**Comment by AstralOrdana** [comment]
fixed in a previous update
