### ISSUE TITLE
XP yields for rough gemstone polishing feels overtuned

### ISSUE THREAD

**Issue by itsNordLord** [AstralOrdana/Spelunkery#17]
Polishing a single rough gemstone rewards over half of an experience level beyond level 30 _in addition_ to the experience gained for mining the ore. Even without fortune, mining trivial amounts of lazurite or cinnabar and polishing it completely dwarfs any other form of experience gathering in the game. 

I am not certain if this is a bug, perhaps the experience yield was accidentally tripled (because polishing one rough lazurite yields 3 lapis lazuli)?

Experience gains for polishing Diamonds or Emeralds could feel appropriate for their rarity, but surely not Lazurite or Cinnabar at least.

**Additional info:**
Context is the latest releases of the mod and its dependencies:
- Fabric: 1.19.2
- Fabric Loader: 0.14.13
- Fabric API: 0.73.0
- Moonlight: 2.2.2
- Spelunkery: 0.1.4

**Comment by AstralOrdana** [comment]
I caught this a while ago and was one of the first things I fixed for the next upcoming version, appreciate the report thought
