### ISSUE TITLE
[1.19.2] Mekanism Support

### ISSUE THREAD

**Issue by Smellsin** [AstralOrdana/Spelunkery#171]
Could there possibly be support for Mekanism's various ores? I've been trying to create a progression-based modpack that would utilize some of their ores into Create, but there does not seem to be any support for them from this mod. Not too big of an issue obviously, but would be great to see as Mekanism has risen up to being one of the more adopted tech mods besides Create.

**Comment by AstralOrdana** [comment]
not planned
