### ISSUE TITLE
Disable Magnetic Compass 'Coordinate Telling' in Dimensions Where Compasses Don't Function

### ISSUE THREAD

**Issue by CraftyZombie** [AstralOrdana/Spelunkery#172]
**Feature:**

As it stands, the Magnetic Compass can tell you your coordinates in dimensions where compasses don't work properly. It would make more sense if that function was disabled in these dimensions. After all, the 'North Indicator' breaks there.

**Alternatives:**

If not a default behavior, this could be a config option. 
Perhaps there could even be a middle ground where the compass reports false coordinates.

**Additional info:**

N/A

**Comment by AstralOrdana** [comment]
not planned
