### ISSUE TITLE
ImmersiveWeathering Crash when world creating

### ISSUE THREAD

**Issue by damikdevil** [AstralOrdana/Spelunkery#174]
**Describe the bug:**
A clear and concise description of what the bug is. Include as much information as you can. Images are often helpful, especially screenshots of the F3 debug menu.

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version: 1.20.1
Spelunkery version: ImmersiveWeathering
Moonlight Lib version: last
Fabric API / QSL / Forge version: last Forge

**Other mods:**
List all mods that you're using; could be in the form of a list of the filenames, a crash report list, a screenshot of
the mods folder, etc. Just make sure all mods used are known!

**Logs:**
*Even if the game does not crash they may be useful!*
Please provide the following logs:
From .minecraft/logs :  "latest.log" as well as "debug.log" if it exists. From .minecraft : "launcher_log" as well as a
file that starts with "hs_err" if it exists. Note: Double check that the logs are from the correct time. ex, don't give
us a log from a month ago because you forgot to check the date.
[latest.log](https://github.com/AstralOrdana/Spelunkery/files/14095399/latest.log)

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1.
2.
3.

**Expected behavior:**

**Screenshots:**
![image](https://github.com/AstralOrdana/Spelunkery/assets/119647711/fb771d6a-1264-46cc-822c-b5e799648fdc)

If applicable, add screenshots to help explain your problem. https://screenshot.help/

**Additional info:**
Add any
[crash-2024-01-30_15.12.13-client.txt](https://github.com/AstralOrdana/Spelunkery/files/14095406/crash-2024-01-30_15.12.13-client.txt)
 other information that might be needed.

**Comment by AstralOrdana** [comment]
this looks to be an issue with the `immersive_weathering:small_plants` but it is likely some sort of mod incompat because this issue cannot be replicated in isolation

**Comment by AstralOrdana** [comment]
WAIT NO invalid bug report this is the spelunkery issues page
