### ISSUE TITLE
[Forge 1.20.1] Crash during startup with Spectrum (via Sinytra Connector)

### ISSUE THREAD

**Issue by unilock** [AstralOrdana/Spelunkery#179]
**Describe the bug:**
The game crashes during startup when Spelunkery is installed alongside [Spectrum](https://modrinth.com/mod/spectrum) using [Sinytra Connector](https://modrinth.com/mod/connector).

**Versions:**
Minecraft version: `1.20.1`
Spelunkery version: `0.3.5`
Moonlight Lib version: `2.9.7`
NeoForge version: `47.1.99`

**Other mods:**
- Cloth Config: [`cloth-config-11.1.118-forge.jar`](https://modrinth.com/mod/cloth-config/version/11.1.118+forge)
- Connector: [`Connector-1.0.0-beta.36+1.20.1.jar`](https://modrinth.com/mod/connector/version/1.0.0-beta.36+1.20.1)
- Forgified Fabric API: [`fabric-api-0.91.0+1.10.8+1.20.1.jar`](https://modrinth.com/mod/forgified-fabric-api/version/0.91.0+1.10.8+1.20.1)
- Patchouli: [`Patchouli-1.20.1-84-FORGE.jar`](https://modrinth.com/mod/patchouli/version/1.20.1-84-forge)
- Revelationary: [`revelationary-1.3.7+1.20.1.jar`](https://modrinth.com/mod/revelationary/version/1.3.7+1.20.1)
- Spectrum: [`spectrum-1.7.6-deeper-down.jar`](https://modrinth.com/mod/spectrum/version/1.7.6)
- Trinkets: [`trinkets-3.7.1.jar`](https://modrinth.com/mod/trinkets/version/3.7.1)

**Logs:**
[crash-2024-02-08_17.24.33-client.txt](https://gist.github.com/unilock/2f3f64cedce5e72f710b60f2d583f584#file-crash-2024-02-08_17-24-33-client-txt)  
[debug.log](https://gist.github.com/unilock/2f3f64cedce5e72f710b60f2d583f584#file-debug-log)

**To Reproduce:**

1. Install NeoForge (or Forge 47.1.3) + Sinytra Connector + Spectrum + Spelunkery + dependencies
2. Start the game
3. The game crashes during startup

**Expected behavior:**
The game starts.

**Screenshots:**
N/A

**Additional info:**
The issue seems to be caused by this mixin:
https://github.com/AstralOrdana/Spelunkery/blob/73a8b0421de91cd624883b46195c1439b5c82b79/common/src/main/java/com/ordana/spelunkery/mixins/NetherPortalSoundMixin.java#L21-L27

During Spectrum's block registration, [it calls `Block#getSoundType`](https://github.com/DaFuqs/Spectrum/blob/6b892514a927b04b02aed3308b0ed64f7c7c72c0/src/main/java/de/dafuqs/spectrum/registries/SpectrumBlocks.java#L1142). This fires Spelunkery's mixin, which tries to access Spelunkery's config, which then fails to initialize itself due to Forge not having finalized its mod list yet.

I expect this would happen with any mod that calls `Block#getSoundType` during mod initialization, so I don't think this is a Connector / Spectrum-specific issue.

**Comment by AstralOrdana** [comment]
will be fixed for 0.3.6
