### ISSUE TITLE
First Person Mod Bugs with Immersive Weather

### ISSUE THREAD

**Issue by HeuristikV64** [AstralOrdana/Spelunkery#18]
**Describe the bug:**
When I look down, the head doesn't tilt forward while crouching, which it is supposed to do.
And when I turn off Immersive Weather, the bug is gone.

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Version 1.19.2 Forge

**Logs:**
No Logs available, game does not crash

Please provide the following logs:
[latest.log]
(https://github.com/AstralOrdana/Spelunkery/files/10544082/latest.log)

[debug.log]
(https://github.com/AstralOrdana/Spelunkery/files/10544084/debug.log)

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Use IW
2. Use First Person Mod

**Expected behavior:**
Head won't tilt forward when crouching, makes it impossible to see your feet and look down.

**Screenshots:**
https://www.youtube.com/watch?v=PTzOL-hx8P0

**Comment by AstralOrdana** [comment]
This is not the issue tracker for immersive weathering

**Comment by HeuristikV64** [comment]
Kinda is you moron

Ordana ***@***.***> schrieb am Di., 31. Jan. 2023, 18:45:

**Comment by AstralOrdana** [comment]
hm okay
![image](https://user-images.githubusercontent.com/62686557/219114551-d851bbea-d33e-4d27-84e9-9772eef3bbf6.png)
