### ISSUE TITLE
Configure Rarity of Ores and Ore Veins

### ISSUE THREAD

**Issue by Mangraz** [AstralOrdana/Spelunkery#180]
Even in vanilla minecraft, many ores spawn somewhat to frequently, making caving a quickly done task. Large ore veins as generated by Spelunky makes caving even more of a breeze. So being able to adjust spawn frequencies would be great!

**Comment by SiverDX** [comment]
you can do this with datapacks
example location for large lapis veins:

https://github.com/AstralOrdana/Spelunkery/blob/1.20.1/common/src/main/resources/data/spelunkery/worldgen/configured_feature/large_lapis_vein.json

https://github.com/AstralOrdana/Spelunkery/blob/1.20.1/common/src/main/resources/data/spelunkery/worldgen/placed_feature/large_lapis_vein.json

**Comment by Mangraz** [comment]
Thanks for pointing me in that direction. It's not very ergonomic, but I'll make sense of it.

**Comment by AstralOrdana** [comment]
terrain feature customization is done via datapacks now
