### ISSUE TITLE
Conk fungus generates on logs in structures

### ISSUE THREAD

**Issue by thcrt** [AstralOrdana/Spelunkery#184]
When a structure such as a village is generated, log blocks often have Conk Fungus attached to them. Presumably, villagers wouldn't  be too keen to live in rotting houses. 

**Further info:**
<details>
<summary>Versions</summary>
 <table>
  <tr>
    <th>Minecraft</th>
    <td><code>1.20.1</code></td>
  </tr>
  <tr>
    <th>Spelunkery</th>
    <td><code>1.20.1-0.3.5</code></td>
  </tr>
  <tr>
    <th>Fabric API</th>
    <td><code>0.91.1+1.20.1</code></td>
  </tr>
</table> 
</details>
<details>
  <summary>Other mods</summary>
<pre>
Mods:
  [✔] AdaptiveTooltips-1.3.0-fabric-1.20.2
  [✔] AdditionalAdditions-6.0.1
  [✔] AdvancementPlaques-1.20.1-fabric-1.4.11
  [✔] Armorful-2.0.2+1.20
  [✔] AttributeFix-Fabric-1.20.1-21.0.4
  [✔] BarteringStation-v8.0.0-1.20.1-Fabric
  [✔] BetterAnimationsCollection-v8.0.0-1.20.1-Fabric
  [✔] BetterBeacons-Fabric-1.20.1-2.0.0
  [✔] BetterThirdPerson-Fabric-1.20-1.9.0
  [✔] BetterTotemOfUndying-Fabric-1.20.4-2.0.1
  [✔] BetterTridents-v8.0.1-1.20.1-Fabric
  [✔] Bookshelf-Fabric-1.20.1-20.1.9
  [✔] Bountiful-6.0.3+1.20.1-fabric
  [✔] CerbonsAPI-Fabric-1.20.1-1.1.0
  [✔] Clumps-fabric-1.20.1-12.0.0.3
  [✔] Companion-1.20-fabric-5.1.0
  [✔] CompletionistsIndex-v8.0.0-1.20.1-Fabric
  [✔] Controlling-fabric-1.20.1-12.0.2
  [✔] CosmeticArmor-1.20-1.6.0
  [✔] Couplings-1.9.4+1.20
  [✔] CreativeCore_FABRIC_v2.11.16_mc1.20.1
  [✔] DEUF_Refabricated-MC1.20.1-1.1.0
  [✔] DeathKnell-Fabric-1.20.1-10.0.4
  [✔] Debugify-1.20.1+2.0
  [✔] DungeonsArise-1.20.1-2.1.57-fabric-release
  [✔] EasyAnvils-v8.0.1-1.20.1-Fabric
  [✔] EasyMagic-v8.0.1-1.20.1-Fabric
  [✔] EquipmentCompare-1.20.1-fabric-1.3.8
  [✔] FallingTree-1.20.1-4.3.4
  [✔] FauxCustomEntityData-fabric-1.20.1-6.0.1
  [✔] ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric
  [✔] Highlighter-1.20.1-fabric-1.1.6
  [✔] Iceberg-1.20.1-fabric-1.1.18
  [✔] ImmediatelyFast-Fabric-1.2.10+1.20.4
  [✔] InventoryProfilesNext-fabric-1.20-1.10.9
  [✔] ItemBorders-1.20.1-fabric-1.2.0
  [✔] ItemPhysic_FABRIC_v1.7.0_mc1.20.1
  [✔] Jade-1.20-fabric-11.7.0
  [✔] Kambrik-6.1.1+1.20.1-fabric
  [✔] Kiwi-1.20.1-fabric-11.5.4
  [✔] LeaveMyBarsAlone-v8.0.0-1.20.1-Fabric
  [✔] LevelTextFix-Fabric-1.20.1-7.0.2
  [✔] Log-Begone-Fabric-1.20.1-1.0.8
  [✔] MapTooltip-fabric-1.20-3.0.0
  [✔] MaxHealthFix-Fabric-1.20.1-12.0.2
  [✔] MindfulDarkness-v8.0.3-1.20.1-Fabric
  [✔] MixinConflictHelper-1.2.0
  [✔] MouseTweaks-fabric-mc1.20-2.25
  [✔] NaturesCompass-1.20.1-2.2.3-fabric
  [✔] Neat-1.20-35-FABRIC
  [✔] NetherChested-v8.0.3-1.20.1-Fabric
  [✔] Nullscape_1.20.4_v1.2.4
  [✔] PickUpNotifier-v8.0.0-1.20.1-Fabric
  [✔] Prism-1.20.1-fabric-1.0.5
  [✔] PuzzlesLib-v8.1.16-1.20.1-Fabric
  [✔] Searchables-fabric-1.20.1-1.0.2
  [✔] SelfishVillager-0.2.0+sha.c219fe2
  [✔] SlotCycler-v8.0.1-1.20.1-Fabric
  [✔] SmoothScrollingRefurbished+1.20-1.1.2
  [✔] Soulbound-Fabric-0.6+1.20.1
  [✔] StackDeobfuscatorFabric-1.4.2+bf1fc22
  [✔] SuperBetterGrass-1.5.2+1.20.1
  [✔] Survival-Tooltips-1.0.0+1.20.1
  [✔] Tips-Fabric-1.20.1-12.0.4
  [✔] TradingPost-v8.0.2-1.20.1-Fabric
  [✔] TravelersTitles-1.20-Fabric-4.0.2
  [✔] VisualWorkbench-v8.0.0-1.20.1-Fabric
  [✔] YeetusExperimentus-Fabric-2.3.0-build.4+mc1.20.1
  [✔] YungsApi-1.20-Fabric-4.0.3
  [✔] YungsBetterDesertTemples-1.20-Fabric-3.0.3
  [✔] YungsBetterDungeons-1.20-Fabric-4.0.3
  [✔] YungsBetterEndIsland-1.20-Fabric-2.0.5
  [✔] YungsBetterJungleTemples-1.20-Fabric-2.0.4
  [✔] YungsBetterMineshafts-1.20-Fabric-4.0.4
  [✔] YungsBetterNetherFortresses-1.20-Fabric-2.0.5
  [✔] YungsBetterOceanMonuments-1.20-Fabric-3.0.4
  [✔] YungsBetterStrongholds-1.20-Fabric-4.0.3
  [✔] YungsBetterWitchHuts-1.20-Fabric-3.0.3
  [✔] YungsExtras-1.20-Fabric-4.0.3
  [✔] alternate-current-mc1.20-1.7.0
  [✔] antique-atlas-1.1.4+1.20
  [✔] antique-fwaystones-1.1.0+1.19
  [✔] appleskin-fabric-mc1.20.1-2.5.1
  [✔] architectury-9.1.13-fabric
  [✔] artifacts-fabric-9.2.2
  [✔] autotag-2.0.2+1.20
  [✔] badpackets-fabric-0.4.3
  [✔] balm-fabric-1.20.1-7.2.1
  [✔] bbs-1.20.1-0.1.3-fabric
  [✔] better-clouds-1.3.14+1.20.1
  [✔] better_log4j_config-1.2.0-fabric
  [✔] betterstats-3.8+fabric-1.20.1
  [✔] blame-log-0.4.0-1.18
  [✔] blur-3.1.0
  [✔] bundle-recipe-v1.0.0
  [✔] cloth-config-11.1.118-fabric
  [✔] collective-1.20.1-7.30
  [✔] comforts-fabric-6.3.5+1.20.1
  [✔] compacthelpcommand-1.20.1-2.5
  [✔] ctov-3.4.2
  [✔] deeper-oceans-mc1.20-v1.0.1a
  [✔] diamond-in-the-rough-1.20.1-1.1.1
  [✔] disenchanter-0.1.8+1.20
  [✔] dragonloot-1.1.4
  [✔] dynamic-fps-3.3.3+minecraft-1.20.0
  [✔] eating-animation-1.20+1.9.5
  [✔] emi-1.1.0+1.20.1+fabric
  [✔] emi_enchanting-0.1.0+1.20.1
  [✔] emi_loot-0.6.5+1.20.1
  [✔] emitrades-fabric-1.2.1+mc1.20.1
  [✔] enchantedshulkers-mc1.20.1-v1.2.3
  [✔] enchantmentcompat-1.2.1+1.20
  [✔] enhancedblockentities-0.9+1.20
  [✔] entity_model_features_fabric_1.20.1-1.2.3
  [✔] entity_texture_features_fabric_1.20.1-5.2.3
  [✔] entityculling-fabric-1.6.2-mc1.20.1
  [✔] environmentz-2.0.8
  [✔] expanded_tooltips-1.20.1-1.1.0-fabric
  [✔] experienced_crops-1.20.1-1.1.0-fabric
  [✔] fabric-api-0.91.1+1.20.1
  [✔] fabric-end-remastered-5.2.4
  [✔] fabric-language-kotlin-1.10.17+kotlin.1.9.22
  [✔] fastback-0.15.6+1.20.1-fabric
  [✔] fastpaintings-1.20-1.2.4-fabric
  [✔] ferritecore-6.0.1-fabric
  [✔] fzzy_core-0.4.2+1.20.1
  [✔] gear_core-0.3.7+1.20.1
  [✔] guarding-2.4.0
  [✔] heracles-fabric-1.20.1-1.1.9
  [✔] herdspanic-1.0.7
  [✔] idwtialsimmoedm-0.3.0+1.20
  [✔] indium-1.0.30+mc1.20.4
  [✔] inmis-2.7.2-1.20.1
  [✔] inmisaddon-1.0.4
  [✔] jumpoverfences-fabric-1.20.1-1.3.1
  [✔] justmobheads-1.20.1-7.5
  [✔] justplayerheads-1.20.1-3.3
  [✔] kubejs-fabric-2001.6.4-build.133
  [✔] lambdynamiclights-2.3.2+1.20.1
  [✔] lazydfu-0.1.3
  [✔] letmedespawn-fabric-1.20.x-1.2.0
  [✔] levelz-1.4.13
  [✔] libIPN-fabric-1.20-4.0.1
  [✔] libz-1.0.3
  [✔] lithium-fabric-mc1.20.1-0.11.2
  [✔] lithostitched-fabric-1.20.1-1.1.5
  [✔] lmft-1.0.2+1.20-fabric
  [✔] lunade-fastanim-1.6-1.20
  [✔] memoryleakfix-fabric-1.17+-1.1.5
  [✔] mixintrace-1.1.1+1.17
  [✔] mobs-attempt-parkour-0.5.2-1.20
  [✔] modelfix-1.14-fabric
  [✔] modernfix-fabric-5.13.0+mc1.20.1
  [✔] modmenu-7.2.2
  [✔] monsters-in-the-closet-1.0.3+1.20
  [✔] moonlight-1.20-2.9.10-fabric
  [✔] more_spawners-1.0.0
  [✔] moreculling-1.20.4-0.22.1
  [✔] moremobvariants-fabric+1.20-1.2.2
  [✔] nerb-1.20.1-0.3-FABRIC
  [✔] netherportalfix-fabric-1.20-13.0.1
  [✔] notenoughanimations-fabric-1.7.1-mc1.20.1
  [✔] notenoughcrashes-4.4.7+1.20.1-fabric
  [✔] nvidium-0.2.6-beta
  [✔] owo-lib-0.11.2+1.20
  [✔] passiveshield-1.20.1-3.4
  [✔] player-animation-lib-fabric-1.0.2-rc1+1.20
  [✔] potionring-fabric-1.20-1.0
  [✔] qu-enchantments-1.3.6-1.20
  [✔] quickrightclick-1.20.1-1.4
  [✔] radiantgear-fabric-2.1.0+1.20.1
  [✔] raised-fabric-1.20.1-3.1.1
  [✔] reds-more-structures-1.0.8R
  [✔] reeses_sodium_options-1.7.2+mc1.20.1-build.101
  [✔] resourcefullib-fabric-1.20.1-2.1.23
  [✔] rhino-fabric-2001.2.2-build.18
  [✔] scorched-1.1.3c
  [✔] seamless-2.2.2-fabric-1.20.1
  [✔] seamless-loading-screen-2.0.3+1.20.1-fabric
  [✔] separatedleaves-2.4.0-fabric-1.20.4
  [✔] shifting-wares-2.1.0+1.20.2
  [✔] sihywtcamd-1.8+1.20.1
  [✔] skeletonhorsespawn-1.20.1-3.8
  [✔] skinlayers3d-fabric-1.6.2-mc1.20.1
  [✔] smoothswapping-0.9.3.1-1.20.2-fabric
  [✔] sodium-extra-0.5.4+mc1.20.1-build.115
  [✔] sodium-fabric-0.5.8+mc1.20.1
  [✔] spark-1.10.53-fabric
  [✔] spelunkery-1.20.1-0.3.5-fabric
  [✔] stendhal-1.4.1-1.20
  [✔] swingthrough-1.0.4+1.19
  [✔] tectonic-mod-1.19.3-v2.2
  [✔] things-0.3.3+1.20
  [✔] threadtweak-fabric-1.20.2-0.1.1
  [✔] tia-1.20-1.1-fabric
  [✔] tntbreaksbedrock-1.20.1-3.2
  [✔] trashslot-fabric-1.20-15.1.0
  [✔] trinkets-3.7.1
  [✔] tru.e-ending-v1.1.0b
  [✔] trulytreasures-1.20-3.0.0
  [✔] unsafe-world-random-access-detector-1.1.0
  [✔] various-starting-loot-4.0
  [✔] villagerarmor-5.0.1
  [✔] wanderingcollector-1.2.1+mc1.20-pre5
  [✔] warrior-rage-1.20.1-fabric-1.0.0
  [✔] whats-that-slot-fabric-1.3.4+1.20.1
  [✔] wits-1.1.0+1.20.1-fabric
  [✔] wraith-waystones-3.3.2+mc1.20.1
  [✔] wso16-fabric-1.2
  [✔] yet-another-config-lib-fabric-3.2.1+1.20
  [✔] your-reputation-0.2.4+jade.1.20
  [✔] zombiehorsespawn-1.20.1-4.8
</pre>
</details>

**Screenshots:**
![Conk Fungus on the side of a village house](https://github.com/AstralOrdana/Spelunkery/assets/110127860/c944149b-b94d-4317-836e-6db27b3d849f)

**Comment by BugmanBugman** [comment]
Am getting this too. Maybe there could be a disabling of conk on logs not generated as trees?

**Comment by AstralOrdana** [comment]
working as intended + theres no way to detect whether the logs are part of a tree or a house

**Comment by thcrt** [comment]
Would it then be possible to add a config option to disable conk fungus generation above-ground? Since it's mostly useful as a wood substitute and wood isn't really lacking on the surface.

**Comment by SiverDX** [comment]
you can:

https://github.com/AstralOrdana/Spelunkery/blob/1.20.1/common/src/main/resources/data/spelunkery/worldgen/placed_feature/conk_fungus.json

https://github.com/AstralOrdana/Spelunkery/blob/1.20.1/common/src/main/resources/data/spelunkery/worldgen/placed_feature/conk_fungus_surface.json
