### ISSUE TITLE
[1.19.2] Support for new veins

### ISSUE THREAD

**Issue by 1ezekiil** [AstralOrdana/Spelunkery#185]
It would be great if we could create our own veins in addition to existing ones, because this opens up enormous possibilities for customizing the world and ore deposits, and it would be even better if such veins were compatible with any modded ores.

**Comment by SiverDX** [comment]
refer to #180

**Comment by 1ezekiil** [comment]
Okay, but how do I use the Noise system to create my own veins? It seems that I am creating the necessary files in the datapack (configured feature and placed feature), but the ore veins are not generated.
All settings are fine, they are almost identical to mod ones, except for the blocks inscribed there. I don't know, what i'm doing wrong.

**Comment by SiverDX** [comment]
you will need to add your feature to the biomes you want it to appear in
how you do this can be easier depending on your platform

for forge it would be a biome modifier, see

https://github.com/AstralOrdana/Spelunkery/blob/1.20.1/forge/src/main/resources/data/spelunkery/forge/biome_modifier/desert_modifier.json

fabric has a mod which allows you to do the same https://modrinth.com/mod/lithostitched

otherwise you'll have to modify the biome worldgen itself

**Comment by 1ezekiil** [comment]
Oh! I see. I'm new in the code and datapacks, so i can be stupid. )
Thank you!
I need some more necessary files, or only placed/configured feature and biome modifier? For creating my ore veins.

**Comment by SiverDX** [comment]
for forge that should be enough (might need a custom biome tag as well depending in which biomes you want your feature)

**Comment by 1ezekiil** [comment]
You are my savior, thank you very much! It's works!

And one last. Can you tell me, where config that controls ore veins generation frequency?
Or what parameter is responsible for it? Not the amount of ore in the structure, but the probability of generating the entire structure as a whole.

**Comment by SiverDX** [comment]
I haven't done much worldgen by myself but the generation frequency is usually handled by the configured feature

https://minecraft.wiki/w/Configured_feature

![image](https://github.com/AstralOrdana/Spelunkery/assets/22003703/6ab7a960-f7fe-4b4f-a95a-f924d30b8126)

https://minecraft.wiki/w/Custom_world_generation/block_state_provider

![image](https://github.com/AstralOrdana/Spelunkery/assets/22003703/e7fcc915-797b-461b-a9f0-f08b8e1eba18)
