### ISSUE TITLE
Alex's Caves Incompatability

### ISSUE THREAD

**Issue by HolidayTheRaptor** [AstralOrdana/Spelunkery#187]
From what I have heard from Alex, the way biomes, particularly the Primordial Caves, generate, is using a form of structure gen that Spelunkery does not allow to occur. i am not certain whether this has to do with spelunkery's cave generation, but suffice to say, even loading a chunk with a primordial cave in it causes the game to crash.

Minecraft version: 1.20.1
Spelunkery version: 1.20.1-0.3.5
Moonlight Lib version: 1.20-2.9.10
Forge 47.2.20

**Other mods:**
Alex's Caves

**Comment by SiverDX** [comment]
\> says game crashes
\> doesn't post log

**Comment by HolidayTheRaptor** [comment]
nvm, seems as though latest spelunk fixes itself.
