### ISSUE TITLE
Bugged Lava Lake Generation in Overworld

### ISSUE THREAD

**Issue by ghost** [AstralOrdana/Spelunkery#188]
**Describe the bug:**
Lava lakes sometimes fail to generate, with lava-free caves generating all the way down to bedrock in some cases.
![2024-02-22_01 19 11](https://github.com/AstralOrdana/Spelunkery/assets/112834430/9b3fe4da-6284-4fe1-b372-b22b4cfbd1ee)

Lava lakes, when they do generate, seem to generate 1 block lower than they do in vanilla, at Y=-56 instead of Y=-55 like in vanilla.
![2024-02-22_01 26 07](https://github.com/AstralOrdana/Spelunkery/assets/112834430/898ab6c4-15d6-4498-b0a9-f8f2a5aa02b1)

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version: 1.20.1
Spelunkery version: 0.3.5
Moonlight Lib version: 2.10.0
Fabric API / QSL / Forge version: Forge 47.2.0

**Other mods:**
No other mods

**Logs:**
[debug.log](https://github.com/AstralOrdana/Spelunkery/files/14371899/debug.log)
[latest.log](https://github.com/AstralOrdana/Spelunkery/files/14371903/latest.log)

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Install Spelunkery and its Moonlight lib for Forge 1.20.1 as outlined above.
2. Boot up the game and start a new world (Default world type, Creative mode, Hard).
3. Navigate to lava lake level (~Y=-55) in the overworld and roam around. Will likely be easier in Spectator mode.

**Expected behavior:**
Lava lakes should consistently spawn at Y levels -55 and below in the overworld.

**Screenshots:**
See above.

**Additional info:**
All of the testing was done with Prism Launcher.

**Comment by AstralOrdana** [comment]
working as intended
