### ISSUE TITLE
Handcrafted conflict 

### ISSUE THREAD

**Issue by Stuopid** [AstralOrdana/Spelunkery#189]
**Describe the bug:**
A clear and concise description of what the bug is. Include as much information as you can. Images are often helpful, especially screenshots of the F3 debug menu.

So I was playing on my hand-made modpack and I recently added spelunkery. 
I also included a furniture mod called handcrafted, and it included a feature where a player threw planks at a stonecutter and take them back as "boards".
I used the feature before but when I tried aftear adding the spelunkry, it didnt work.
I was confused as I saw nothing happened when I threw planks at a stonecutter.
I went to the github of the mod and posted the issue and logs to the bug report. 
They contacted me back in a day or so, saying the spelunkery mod is causing the bug.
They told that I either needed to remove spelunkery or update the modpack to 1.20.1 . Which is something I cant do because most of the mods I installed are not available on 1.20.1 . The only option left was to remove the mod. 
I find spelunkery extremely fun and it is unfortunate for me to remove it. It would be great if you guys update the 1.19.2 version and fix the bug. Wishing best for you guys, thank you. 

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version: 1.19.2
Spelunkery version: 0.2.6 
Moonlight Lib version: 2.3.6
Fabric API / QSL / Forge version: 43.3.5
Supplementaries: 2.4.20
Supplementaries Squared: 1.1.1

**Other mods:**
List all mods that you're using; could be in the form of a list of the filenames, a crash report list, a screenshot of
the mods folder, etc. Just make sure all mods used are known!

Not going to list them because I already know what is causing the bug. But if its necessary, it is included in the logs. 

**Logs:**
*Even if the game does not crash they may be useful!*
Please provide the following logs:
From .minecraft/logs :  "latest.log" as well as "debug.log" if it exists. From .minecraft : "launcher_log" as well as a
file that starts with "hs_err" if it exists. Note: Double check that the logs are from the correct time. ex, don't give
us a log from a month ago because you forgot to check the date.

](https://paste.atlauncher.com/view/07612a0c-316e-4b78-8441-72a7e6babb95)

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

**Expected behavior:**
Expected the boards when I thew planks at the stonecutter
**Screenshots:**
If applicable, add screenshots to help explain your problem. https://screenshot.help/

**Additional info:**
Add any other information that might be needed.

Contact me back via mail. Sheflolkq@gmail.com

**Comment by AstralOrdana** [comment]
this was fixed ages ago
