### ISSUE TITLE
Startup Crash with newest version

### ISSUE THREAD

**Issue by FrogBirdd** [AstralOrdana/Spelunkery#19]
Instant crash when attempting to load the game with latest version of Spelunkery

Minecraft version:1.19.2
Spelunkery version:0.1.5
Moonlight Lib version:2.2.2
Fabric API / QSL / Forge version:43.2.4

[latest.log](https://github.com/AstralOrdana/Spelunkery/files/10549403/latest.log)

**Comment by AstralOrdana** [comment]
that file isnt helpful, you need to show the crash log like the issue template says

**Comment by FrogBirdd** [comment]
There just isn't one, sorry for not mentioning that. Just a crash with an exit code of 1 before the game even starts

**Comment by Noxalas** [comment]
Also couldn't start with newest version in a medium-sized modpack. 
Updating to latest moonlight (v. 2.2.3 for 1.19.2) fixed the startup issue for me.

Only thing I noticed is the name of the portal fluid being fluid_type.unregistered_sadface

This was the crash I had before updating:
[crash-2023-01-31_20.21.42-fml.txt](https://github.com/AstralOrdana/Spelunkery/files/10550141/crash-2023-01-31_20.21.42-fml.txt)

**Comment by FrogBirdd** [comment]
https://www.curseforge.com/minecraft/mc-mods/majrusz-library
After some messing around it seems that this mod is somehow conflicting and causing the crash.

**Comment by AstralOrdana** [comment]
are you having this crash on fabric or forge?

**Comment by FrogBirdd** [comment]
forge

**Comment by AstralOrdana** [comment]
try out this spelunkery version and let me know if its resolved
https://www.dropbox.com/s/2al5dx7yg03r90r/spelunkery-1.19.2-0.1.6-forge.jar?dl=0

**Comment by AstralOrdana** [comment]
fixed
