### ISSUE TITLE
Much More Sculk Blocks generate compared to Vanilla

### ISSUE THREAD

**Issue by treg2** [AstralOrdana/Spelunkery#191]
**Describe the bug:**
A clear and concise description of what the bug is. Include as much information as you can. Images are often helpful, especially screenshots of the F3 debug menu.
Huge Bodies of sculk blocks generate around Ancient Cities. Sculk Sensors, Catalysts and Shriekers also generate at different locations compared to vanilla.

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version: 1.20.1
Spelunkery version: 1.20.1-0.3.5
Moonlight Lib version: 1.20-2.10.4
Fabric API / QSL / Forge version: 47.2.17

**Other mods:**
None

**Logs:**
*Even if the game does not crash they may be useful!*
Please provide the following logs:
From .minecraft/logs :  "latest.log" as well as "debug.log" if it exists. From .minecraft : "launcher_log" as well as a
file that starts with "hs_err" if it exists. Note: Double check that the logs are from the correct time. ex, don't give
us a log from a month ago because you forgot to check the date.

[latest.log](https://github.com/AstralOrdana/Spelunkery/files/14390357/latest.log)
[debug.log](https://github.com/AstralOrdana/Spelunkery/files/14390355/debug.log)
**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Deepdark biome with sculk around (eg: /tp @s -188 -3 84 on world seed: 8109923753392202505 (1.20.1 Default world type)
2. execute "/fill ~10 ~10 ~10 ~-10 ~-10 ~-10 minecraft:air replace minecraft:sculk"
3. observe how many sculk blocks got removed
4. repeat with spelunkery removed

**Expected behavior:**
Amount of sculk blocks should remain atleast similar and not increase by a factor greater than 20.

**Screenshots:**
![withoutspelunkery](https://github.com/AstralOrdana/Spelunkery/assets/92642789/9b1f1db8-88cd-486c-ac6e-84c0ab355af5)
![withspelunkery](https://github.com/AstralOrdana/Spelunkery/assets/92642789/3a1ad518-e4a2-40e8-b812-28de9cddb2a0)
needed.

**Additional info:**
Add any other information that might be needed.
-

**Comment by AstralOrdana** [comment]
please repost images with night vision on, its impossible to tell what youre trying to show

**Comment by treg2** [comment]
Sorry. I just wanted to show, that when I executed the /fill command from my how to reproduce steps on the exact same seed without spelunkery there were only 232 sculk blocks while with spelunkery there were 4887 sculk blocks in the same radius at the same coordinates. The game itself does not show anything useful anyway. I just wanted to show the coordinates, seed and how many sculk blocks were in that area

some more pictures to illustrate the issue:
without spelunkery installed:
Panorama
![2024-02-24_11 13 04](https://github.com/AstralOrdana/Spelunkery/assets/92642789/d7a43ee8-067f-46ce-b512-c54014d4a8ec)

Under Ancient City:
![2024-02-24_11 13 49](https://github.com/AstralOrdana/Spelunkery/assets/92642789/060bfd53-0376-44be-bcfa-95ef48d50b04)

with spelunkery installed:
Panorama:
![2024-02-24_11 08 24](https://github.com/AstralOrdana/Spelunkery/assets/92642789/2349dea7-28e3-44cd-b437-0a34217e75a6)

Under Ancient City
![2024-02-24_11 14 27](https://github.com/AstralOrdana/Spelunkery/assets/92642789/63636c9b-2066-47fd-b412-34e5e8210173)
![2024-02-24_11 15 15](https://github.com/AstralOrdana/Spelunkery/assets/92642789/b8caf089-21de-4448-bf78-bdfd26ba07b4)

the sculk generating with spelunkery is also multiple layers thick. Ores are still generated in the sculk.
In vanilla sculk usually generates only on the surface.

**Comment by SiverDX** [comment]
https://github.com/AstralOrdana/Spelunkery/blob/1.20.1/common/src/main/resources/data/spelunkery/worldgen/configured_feature/noise_stripes_sculk.json

\+

https://github.com/AstralOrdana/Spelunkery/blob/d06910226eab5086462138baf81f38abeb8893bd/common/src/main/java/com/ordana/spelunkery/reg/ModWorldgenFeatures.java#L51-L54


seems intentional

**Comment by treg2** [comment]
Okay I see. I had 'better_sculk_patches = false' and 'stone_stripe_features = true' which are the default values.

If this is intentional then I would like to give the feedback, that insta mining sculk with a mending hoe gives much more resources than normal mining. Since sculk also gives experience, mining sculk to expose ores is overall much more efficient than going caving (in my opinion). I installed spelunkery to make caving more worthwhile (which seems to be the goal of this mod?). At the moment im just running around with a diamond hoe with mending. There is no risk of wardens since the sculk generates even without any caves nearby so there are almost no sculk shriekers which could get triggered.

I was hesitant to create this issue since it feels more like a balancing issue than an actual bug. But I did not find a feedback section.

Lastly: Is there a way to configue the sculk spawning back to vanilla while keeping all the other great features of this mod (and if not: could a config option for this be added)? 
stone_stripe_featues = false prevents the sculk/nephrite stripes from generating (seems to be like vanilla) but also removes all other types of stripes.

**Comment by SiverDX** [comment]
setting the sculk patch config should disable one part

the other is the noise
(keep in mind this is also responsible for generating nephrite)

https://github.com/AstralOrdana/Spelunkery/blob/1.20.1/common/src/main/resources/data/spelunkery/worldgen/configured_feature/noise_stripes_sculk.json

which you can disable like any other feature (kinda depends on your modloader)

https://forge.gemwire.uk/wiki/Biome_Modifiers#Remove_Features

https://modrinth.com/mod/lithostitched
https://github.com/Apollounknowndev/lithostitched/wiki/Worldgen-Modifiers#remove_features

**Comment by AstralOrdana** [comment]
this is working as intended, obtaining xp in minecraft has never been balanced and this is just a concequence of the sculk and nephrite stripe generation
