### ISSUE TITLE
Magnetic Compass block tag support

### ISSUE THREAD

**Issue by soleilan** [AstralOrdana/Spelunkery#192]
**Feature:**

Implement a block tag for blocks that the Magnetic Compass will point to when in range to allow for easier mod support and customization for it.

**Alternatives:**

An alternative would be a line in the config that simply adds item IDs to the list of blocks the Magnetic Compass points to.

Another alternative would be to just hardcode the mod support into the mod, but that seems far from ideal.

**Additional info:**

Upon adding the mod to my modpack, I was hoping to make the Magnetic Compass work with other mods magnetic blocks and point to them, such as Alex's Caves neodymium nodes or Quark magnets. By utilizing a block tag it would be as simple as adding the tag to the blocks.

**Comment by AstralOrdana** [comment]
not feasible, in order for magnetite blocks to work they need to be a tile entity that pings the compass which cannot be done by simply other blocks to a tag
