### ISSUE TITLE
Spring Water turns yellow with Embeddium Fabric version 0.3.7

### ISSUE THREAD

**Issue by KeWHs** [AstralOrdana/Spelunkery#194]
**Describe the bug:**
Spring Water becomes yellow when using Embeddium. The color is right when using sodium.

**Versions**
Minecraft version: 1.20.1
Spelunkery version: 0.3.5
Moonlight Lib version: moonlight-1.20-2.10.8-fabric
Fabric API / QSL / Forge version: Fabric API 0.92.0-1.20.1

**Other mods:**
I've removed all other mods I loaded to test this bug.

**Screenshots:**

**Comment by KeWHs** [comment]
![20240229170421](https://github.com/AstralOrdana/Spelunkery/assets/71676400/24569d4c-598e-4536-99db-789f6cd933a8)
Here's the screenshot for the spring water.

**Comment by steve-the-player** [comment]
The Fluid display when using Create and REI (and also the Jade icon) have the same thing in reverse when using Sodium/Iris:  
![2024-03-05_16 07 37](https://github.com/AstralOrdana/Spelunkery/assets/61434698/09a5c67c-a012-4800-bf72-c8bf62c78ca8)
![2024-03-05_16 07 41](https://github.com/AstralOrdana/Spelunkery/assets/61434698/52460e31-bbbc-48c8-b7a0-a98e33d3dd63)

**Comment by AstralOrdana** [comment]
this is caused by sodium changing how the tint color is read, ive worked around it as best I can but the issue persists in places
