### ISSUE TITLE
Cauldron salt recipe behaves odd with stacks

### ISSUE THREAD

**Issue by RainbowSaber** [AstralOrdana/Spelunkery#203]
When throwing salt piles into a bubbling cauldron one by one, each salt pile is converted into one salt crystal. When throwing in stacks with more than one piece of salt, the output stack is seemingly twice as large as the input stack.

Minecraft version: 1.20,1
Spelunkery version: 0.3.5
Moonlight Lib version: 
Forge version: 47.2.19

**Comment by AstralOrdana** [comment]
unable to reproduce

**Comment by RainbowSaber** [comment]
Cant reproduce this on my instance anymore either, not sure whats up there, sorry for (apparenlty) wasting your time Im pretty sure I was quite diligent when submitting this bug report.
