### ISSUE TITLE
Config option to disable automatically applying resource pack

### ISSUE THREAD

**Issue by PolyframeX** [AstralOrdana/Spelunkery#205]
**Feature:**

It would be nice if there was a configuration option to disable automatically applying the resource pack when generating the resource pack list. This would help with certain modpacks that attempt to create a default list on startup. But then get some defaults overwritten with this.

**Alternatives:**

Another alternative would be to have resource packs just not enabled on default. However the 1st option is preferred.

**Comment by MFNmodding** [comment]
yes, either is preferable.

**Comment by AstralOrdana** [comment]
resource packs are no longer enabled by default for 0.3.10
