### ISSUE TITLE
[1.20.1] Spelunkery prevents Tectonic Lava Rivers from generating properly

### ISSUE THREAD

**Issue by ambientNexus** [AstralOrdana/Spelunkery#206]
**Describe the bug:**
Tectonic is supposed to generate specialty caves with lava rivers deep underground. However, with Spelunkery installed, the caves themselves generate properly but are missing the lava they're supposed to generate with. Tectonic developer confirmed the issue appears to be on your side. Images and more info provided in the issue post below.
https://github.com/Apollounknowndev/tectonic/issues/112

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version: 1.20.1
Spelunkery version: 0.3.5
Moonlight Lib version: 2.11.9
Fabric API / QSL / Forge version: Neoforge 47.1.103

**Other mods:**
Tectonic 2.2.1 (Datapack packaged as mod)

**Logs:**
*Even if the game does not crash they may be useful!*
Please provide the following logs:
[debug.log](https://github.com/AstralOrdana/Spelunkery/files/14786825/debug.log)
[latest.log](https://github.com/AstralOrdana/Spelunkery/files/14786826/latest.log)

**To Reproduce:**
1. Install Spelunkery (+ Moonlight Lib) alongside Tectonic.
2. Generate world and locate long tube-like cave at bedrock level (Lava River Cave)
3. Cave will generate without intended lava.

**Expected behavior:**
Said caves are intended to generate with a river of lava.

**Screenshots:**
Screenshots provided are on the same seed (1234), at the same coordinates (-527, -51, 157).
Cave as generated with Tectonic & Spelunkery:
![2024-03-28_02 02 02](https://github.com/AstralOrdana/Spelunkery/assets/53546918/ecd74770-021c-4d7b-a8b3-94e136b92e27)
Cave as generated with only Tectonic:
![2024-03-28_02 06 32](https://github.com/AstralOrdana/Spelunkery/assets/53546918/949d0348-182b-42f3-ae1d-84b22db468d3)

**Comment by emorydeer2** [comment]
Can confirm, thought that was normal, though, quite odd.

**Comment by AstralOrdana** [comment]
think this was fixed a couple updates ago, comment here and ill reopen if not

**Comment by ambientNexus** [comment]
Whoops yeah, forgot to close it, can confirm it was fixed.
