### ISSUE TITLE
[Quilt] Dimensional Tears fluid missing texture on north and south-facing source blocks

### ISSUE THREAD

**Issue by koppiki** [AstralOrdana/Spelunkery#209]
![image](https://github.com/AstralOrdana/Spelunkery/assets/96354498/46e884dd-38b7-4888-a914-3e3579f6314c)
see image above for issue. Doesn't occur with corners, only with edges.

Minecraft version: 1.20.1
Spelunkery version: 1.20.1-0.3.5
Moonlight Lib version: 1.20.1-2.11.12
Fabric API / QSL / Forge version: Quilt 0.25.0

**Comment by ClockworkCorvus** [comment]
Confirming an identical issue here on forge + neoforge
![2024-04-21_14 20 25](https://github.com/AstralOrdana/Spelunkery/assets/128114063/5c5e5171-023d-4800-8211-3b7d177b89fd)

**Comment by AstralOrdana** [comment]
duplicate of #135
