### ISSUE TITLE
[Feature Req] Make Magnetic Compass show your X and Z Coordinates just like the Depth Meter

### ISSUE THREAD

**Issue by Reshirou** [AstralOrdana/Spelunkery#21]
The right click function of the Magnetic Compass would need to be changed to Crouch Right Click, which would then make Crouch Right Click a toggle for pointing to Magnetite rather than just a Clear.
If that was done, then the Magnetic Compass could have a very useful feature in showing your X and Z Coordinates on regular Right Click. Toggle function would also make the "point North" more consistent as you'd have to be checking for Magnetite, rather than being jumpscared by it every time to break one block it it.

This would add to the "reduced F3 information" game atmosphere that seems to be cultivating with the Depth Meter, the buffed Death Compass, and the easier Lodestone recipe.

**Comment by AstralOrdana** [comment]
I really like this suggestion. I'm not going to make magnetite detection mode a toggle as its very intentionally designed to be interference with the compass's natural magnetic attraction. However, the idea of making it useful for locating your x and z coordinates is great and implemented for the next version
