### ISSUE TITLE
Bug textures

### ISSUE THREAD

**Issue by Bruskych** [AstralOrdana/Spelunkery#212]
All I want to say is you can see in the picture. Some parts of spatial tears spilled on the floor are buggy and the texture is not displayed
![2024-04-29_15 22 44](https://github.com/AstralOrdana/Spelunkery/assets/158246943/5b83cae0-5f73-45f9-ac58-a7d463ef3c92)

**Comment by AstralOrdana** [comment]
duplicate of https://github.com/AstralOrdana/Spelunkery/issues/135
