### ISSUE TITLE
[Forge 1.20.1] Multiple items are missing standard tags

### ISSUE THREAD

**Issue by vizthex123** [AstralOrdana/Spelunkery#215]
Mostly applies to item tags, but also some block tags.

All of the mushrooms are missing the `forge:mushrooms` tag.

All of the ores are missing the `forge:ores`  and `forge:ores/type` tags. I'm not sure why Spelunkery has its own item tag for ores, but it'd be nice to have standard ones (replacing the custom ones if they aren't used for anything special).

Raw Magnitite is missing both `forge:raw_materials` tags (that one and `/type`)

Would also be nice if all the Magnetite stuff had the `alexscaves:ferromagnetic_items` tag if Alex's Caves is loaded.

**Comment by AstralOrdana** [comment]
implemented for 0.3.10

**Comment by vizthex123** [comment]
noice, thanks.
