### ISSUE TITLE
Incompatibility with BetterTrims breaks Tuning Fork detection range

### ISSUE THREAD

**Issue by mintynoura** [AstralOrdana/Spelunkery#217]
**Describe the bug:**
When running Spelunkery with the mod BetterTrims, the range of Amethyst Tuning Forks is reduced to less than 8 blocks. Modifying the range value in Spelunkery's config does not seem to change anything. This makes Tuning Forks difficult to use.

**Versions:**
Minecraft version: 1.20.1
Spelunkery version: 1.20.1-0.3.5
Moonlight Lib version: 1.20-2.11.17
Fabric API / QSL / Forge version: Fabric API 0.92.1

**Other mods:**
BetterTrims version: 2.3.1

**Logs:**
The log does not seem to mention anything, but here is [latest.log](https://mclo.gs/3efkucb)

**To Reproduce:**
1. Create an instance with Spelunkery and BetterTrims installed
2. Test using a Tuning Fork to detect Budding Amethyst
3. Discover the reduced range of the item

**Expected behavior:**
The range would not be reduced and would follow the value in the config file.

**Video:**

https://github.com/AstralOrdana/Spelunkery/assets/107040228/f0e1d08b-8ac9-48c4-bb28-f1562336c46c

**Comment by AstralOrdana** [comment]
i have absolutely no clue why that mod would mess with that but it should be reported to them
