### ISSUE TITLE
[Feature Req] A Compass that can be linked to a living entity or player

### ISSUE THREAD

**Issue by Reshirou** [AstralOrdana/Spelunkery#22]
A Compass that always points towards a chosen player would make exploring or mining together much more fun, as well as letting you find the location of a Dungeon your friends wants you to explore with them, without needing to know coordinates, or having them backtrack around to come get you.

This compass could also have the feature of pointing towards any actively loaded entity as well, so that it has a use in Single Player. Perhaps you could use it to spot where you made your pet sit if you forgot, or where your wandering makeshift pet "mob" is.
(I for one made a Spider part of my "team" so that it is passive, but every once in a while it does go missing only to be found randomly later.)

To balance that feature, the compass would go haywire when the non-player entity is unloaded, and only relock when you're within ticking distance of them again. That way you can't just put a chicken in a 3x3 cube for a cheap Lodestone.

The quasi-lore for this could also be something that has to do with reversing a Recovery Compass; a Recovery Compass points towards death, and a ****** Compass points towards life.

Nephrite Compass?

**Comment by MehVahdJukaar** [comment]
You can use heartstone mod

**Comment by AstralOrdana** [comment]
I dont think that something like that would fit with Spelunkery very well, as suggested above the Heartstone mod does something similar very well
