### ISSUE TITLE
incompatibility with Galosphere (recovery compass dissapears)

### ISSUE THREAD

**Issue by Lucky-56** [AstralOrdana/Spelunkery#220]
[I am unaware which mod causes this bug so I'll cross report this.](https://github.com/0rc1nus/Galosphere-Main/issues/97)

**Describe the bug:**
The recovery compass (made soulbound by spelunkery) dissapears after death.

**Versions:**
Minecraft version: 1.20.1
Spelunkery version: 0.3.5
Moonlight Lib version: 2.11.17
Forge version: 47.2.30

**Other mods:**
Galosphere: 1.4.1

**Logs:**
https://pastebin.com/sPUJ2shn

**To Reproduce:**

1. join world
2. give recovery compass
3. use /kill
4. respawn

**Expected behavior:**
for me to keep the recovery compass

**Screenshots:**
*not neccessary*

**Additional info:**
*not neccessary*

**Comment by joprks** [comment]
same with soulbound enchant

**Comment by Lucky-56** [comment]
so this probably is a galosphere issue then eh?

**Comment by steve-the-player** [comment]
Probably. Gallosphere hasn’t been updated in a long time and wasn’t the most well-written mod to begin with, so there’s a lot of bug reports that have piled up. I think 0rc1nus has abandoned the project

**Comment by AstralOrdana** [comment]
issue should be left to them
