### ISSUE TITLE
Create Dimensional Tears craft broken

### ISSUE THREAD

**Issue by LeKripiY** [AstralOrdana/Spelunkery#223]
The output of Dimensional Tears makes it impossible to be crafted because it is bigger than the max fluid capacity of a bassin:
![image](https://github.com/AstralOrdana/Spelunkery/assets/77859121/ec196d1c-1d85-4831-834d-0c1835f31275)
Max is 1000mb = 1 bucket

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version: 1.20.1
Spelunkery version: 0.3.5
Moonlight Lib version: 2.11.22
Fabric API / QSL / Forge version: 47.2.17

**Other mods:**
Create and plenty others, also have Kubejs installed but I have not changed any recipes from Spelunkery.

**Logs:**
[latest.log](https://github.com/AstralOrdana/Spelunkery/files/15369112/latest.log)
debug log too heavy

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

![image](https://github.com/AstralOrdana/Spelunkery/assets/77859121/150fc6c3-8eba-44cd-a14e-e3204a724d2d)

**Expected behavior:**
get dimensional tears

**Screenshots:**
![image](https://github.com/AstralOrdana/Spelunkery/assets/77859121/552d2640-c570-457c-95f9-6f92dfbb0407)
Even the dimensional tears filling bottle recipe is broken, it costs way to much
**Additional info:**
Only the recipe of filling a bucket costs enough.

**Comment by AzrannAVANA** [comment]
I second this- Quite an oof.

Crying Obsidian also cannot be created due to this, the necessary amount of Dimensional Tears is far greater than what a spout can hold.

The Item Drain also cannot be used in this regard, the output being 7 buckets.

Bucket fill works because it was automatically generated by create.

**Comment by VelonacepsCalyxEggs** [comment]
Yeah, just encountered this problem, remember this working a while back though. Bump.

**Comment by VelonacepsCalyxEggs** [comment]
Just figured out a way to get dimensional fluid into the pipes in survival, place the dimensional fluid with dimensional fluid bucket using a deployer, suck it up with a pump, profit. Workaround for now...

**Comment by steve-the-player** [comment]
The problem is because Create Forge still uses droplets (the old small fluid unit) in its recipes; even though all the UI displays things in millibuckets now, it still does its calculations in droplets because it’s more precise. Create Fabric’s recipes use millibuckets, which are 27 times bigger.

**Comment by AstralOrdana** [comment]
fixed for 0.3.6
