### ISSUE TITLE
Unlit Redstone resource pack seemingly force-enabled

### ISSUE THREAD

**Issue by Lucky-56** [AstralOrdana/Spelunkery#224]
**Describe the bug:**
`Unlit Redstone Ores` is force enabled, causing it to, even if below `Better Vanilla Gems`, to display the default unlit redstone texture for `Redstone Ore` and `Deepslate Redstone Ore`.

**Versions:**
Minecraft version: 1.20.1
Spelunkery version: 0.3.5
Moonlight Lib version: 2.11.20
Forge version: 47.2.32

**Screenshots:**
![image](https://github.com/AstralOrdana/Spelunkery/assets/55949451/3b483ca5-fc93-4844-b975-bc11b71596b4)
![image](https://github.com/AstralOrdana/Spelunkery/assets/55949451/46fcc9f8-c48b-430c-850b-8dc6c4704066)
![image](https://github.com/AstralOrdana/Spelunkery/assets/55949451/7f2e20c8-d84e-495f-8fd3-01bc015f383f)

**Comment by AstralOrdana** [comment]
the "better vanilla" textures try to represent the redstone more as crystals to match the cinnabar colors so having them be unlit it wouldnt make as much sense

**Comment by Lucky-56** [comment]
gotcha

**Comment by Lucky-56** [comment]
why is it a required pack then tho?
![image](https://github.com/AstralOrdana/Spelunkery/assets/55949451/65a3abf6-60c6-417d-831a-a6cbf8b97704)

**Comment by AstralOrdana** [comment]
idk why its being marked as required, thats strange, you could probably try deleting it from the jar if you dont like it or just place "better vanilla" above it if you prefer that

**Comment by Lucky-56** [comment]
I have better vanilla placed above but it still shows...
![image](https://github.com/AstralOrdana/Spelunkery/assets/55949451/ba965116-3a92-4115-bb16-36395c54508a)

(placed it as close to the bottom as I could)
![image](https://github.com/AstralOrdana/Spelunkery/assets/55949451/a0eee005-e5e7-49fe-8f66-71fa63bee602)

**Comment by Lucky-56** [comment]
~~not looked into the pack yet but~~ it probably changes the model of the off state, thus always showing (cuz no other RP replaces it)
EDIT: yep exactly :p
![image](https://github.com/AstralOrdana/Spelunkery/assets/55949451/2d754289-6745-4822-9c64-37bac4edfd93)

**Comment by Lucky-56** [comment]
should we move this to another issue or not, since this is fixed easily?

**Comment by AstralOrdana** [comment]
reopened until the force-enabling is resolved

**Comment by AstralOrdana** [comment]
should be resolved for 0.3.10, leaving open until verified

**Comment by Cephelo** [comment]
Now I don't see the Unlit Redstone pack anywhere, it's not in the mod's resources either.  Also, the custom redstone dust texture in the "Better Vanilla Gems" pack isn't being applied - it's called redstone_dust.png, but it should be redstone.png

**Comment by AstralOrdana** [comment]
the other resource packs were removed from the base mod, they can be downloaded from my discord server now
