### ISSUE TITLE
[Feature Req] Make the Diamond Grindstone take damage like an Anvil, requiring new ones over time

### ISSUE THREAD

**Issue by Reshirou** [AstralOrdana/Spelunkery#23]
This would mean the vanilla Grindstone still has a place in your workshop, even with no other mods besides Spelunkery active, as you would generally want to polish as much as you can with the regular one and save your Diamond one for when you need it.

This would also add some balance to my other suggestion on grinding curses.

You could even make it so grinding enchantments at all on a Diamond Grindstone gives more XP back, as with this mechanic it is a limited tool and not something you can just set and forget.

**Comment by ChromaPIE** [comment]
Reasonable but please make it able to be mended with diamond shards, see what Mendable Anvils mod tweaks the anvil. It's kinda annoying if you have to craft that one polished deepslate slab, gather all the ingredients and make a new one.

**Comment by Reshirou** [comment]
Perhaps data driven mendable items, such that someone like me could disable it altogether

**Comment by AstralOrdana** [comment]
implemented in 0.1.11
