### ISSUE TITLE
Sluice?

### ISSUE THREAD

**Issue by GodDuckDuck** [AstralOrdana/Spelunkery#231]
Maybe add the Sluice to your wiki? I can't seem to find out how it works, I know a little what its meant to look like based of the one picture but that's about it

**Comment by steve-the-player** [comment]
A sluice behaves much like a channel. Right clicking a side with the relevant tool (axe for wood ones, pickaxe for stone ones) toggles that side’s state between wall, sluice filter, and open. Fluids flow through filter and open portions but are restrained by walled parts, so you can use them in conjunction with channels for fluid management. I believe to use a sluice, the fluid has to be able to travel downwards after exiting (in other words, put a sluice on the end of a channel and then let it flow out of the sluice to form a waterfall) 

Currently the only supported fluids are water, spring water, dimensional tears, and lava (requires stone sluice). The sluices have a small inventory about the size of a hopper that you can access by hand or with hoppers and other similar modded blocks. They slowly generate items dependent on randomTickSpeed and what type of fluid it is:  
Water: pebbles, sea grass, and coarse(?) dirt.  It might occasionally give raw iron nuggets. I can’t remember. 
Spring water: rock salt, saltpeter, sulfur, and occasionally raw copper nuggets. 
Dimensional tears: end stone pebbles, enderpearls, chorus fruit, and occasional endermites spawning out of the stream. Be aware of this! They have a small cooldown after spawning, but after that if they touch the fluid the get teleported to world spawn unless dealt with
Lava: netherrack pebbles, magma cream, magma blocks, raw gold nuggets. 

Pebbles can be thrown, and can also be crafted by 9 into their respective block and back. Normal pebbles form cobblestone

**Comment by GodDuckDuck** [comment]
Cool thank you

**Comment by AstralOrdana** [comment]
sluice tooltips added for 0.3.6
