### ISSUE TITLE
Dimensional Tears Bypass IguanaTweaks Reborn Portal Corner Requirement

### ISSUE THREAD

**Issue by CraftyZombie** [AstralOrdana/Spelunkery#233]
**Describe the bug:**
IguanaTweaks Reborn makes it so that there can be a specific requirement for the corners of Nether portals before they are lit. Spelunkery, the conflicting mod, adds a new item (The Bottle o' Dimensional Tears), which allows the lighting of Nether portals without flint and steel. However, lighting the portal in this manner bypasses the requirement to fill the portal corners.

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version: 1.20.1
Spelunkery version: 0.3.5
Moonlight Lib version: 2.11.33
Fabric API / QSL / Forge version: Forge 47.3.1

**Other mods:**
IguanaTweaks Reborn - 3.12.0
InsaneLib - 1.13.5
MaxHealthFix - 12.0.3

**Logs:**
*Even if the game does not crash they may be useful!*
(https://gist.github.com/CraftyZombie/f1aa0903fba073c8709a0afe554781f7)

**To Reproduce:**
1. Install listed mods.
2. Build Nether portal without required corners.
3. Activate using Dimensional Tears.

**Expected behavior:**
The portal should not have activated.

**Screenshots:**

![2024-06-09_17 35 21](https://github.com/Insane96/IguanaTweaksReborn/assets/70306455/dc2944f1-f01f-4228-b07a-b63e206312b2)

**Additional info:**
Original Bug Report: https://github.com/Insane96/IguanaTweaksReborn/issues/295
Comment from IguanaTweaks Reborn author: https://github.com/Insane96/IguanaTweaksReborn/issues/295#issuecomment-2157332997

**Comment by AstralOrdana** [comment]
its a crossplatform mod, i cant use the forge event, the mods will remain incompatible
