### ISSUE TITLE
Throwables crashes everyones game in the simulation radious

### ISSUE THREAD

**Issue by DaveTheMagicalKidWizard** [AstralOrdana/Spelunkery#235]
I'm playing on an Aternos server with my friends, and any throwable thing crashes our games if we are in the simulation radius. It only crashes our games, not the server.
I only experienced it in the Overworld, but I think it happens in other dimensions as well.
We're playing on the recommended version of Fabric on 1.20.1.
I'll attach the crash report.
[crash-2024-06-22_17.37.47-client.txt](https://github.com/user-attachments/files/15937318/crash-2024-06-22_17.37.47-client.txt)

**Comment by TippyToadXO** [comment]
This also happens on forge 1.20.1. I’m making my own server, so I have tested the mod pack I’ve made on two different computers to see if it runs smoothly. I tried throwing glow sticks and the explosive and it crashes instantly every time.

**Comment by DaveTheMagicalKidWizard** [comment]
I just found out that it crashes on singleplayer worlds as well

**Comment by Dylan4Jacks** [comment]
Just had the server crash when a Glow Sticks got thrown. Iv linked the server Report here.
[crash-2024-06-26_11.41.34-server.txt](https://github.com/user-attachments/files/15988308/crash-2024-06-26_11.41.34-server.txt)

I did also Crash on a local world as well. The second the glowstick is thrown it crashes.

**Comment by ALEILGOD** [comment]
The crash is a ticking entity. Singleplayer minecraft uses an integrated server that runs on a cpu and it has ping, ticks and every other thing of a minecraft server. A ticking entity is when the server or the integrated server is incapable of fixing the data of the entity, this means that all the throwables of this mod are broken and the author needs to fix it is not caused by any mods.

**Comment by ALEILGOD** [comment]
This is everything i have for this problem

**Comment by AstralOrdana** [comment]
this issue is caused by the Moonlight mod, while they work on a fix you can revert its version to prevent these crashes

**Comment by Dylan4Jacks** [comment]
Thank you @AstralOrdana.
I have reported the issue to moonlight Lib [Here (See issue/230)](https://github.com/MehVahdJukaar/Moonlight/issues/230) 

Rolling back Moonlight Lib to version moonlight-1.20-2.12.2 resolves the issue.

**Question:** is version `moonlight-1.20-2.12.2` the version of Moonlight Lib Spelunkery expects? _(I am unsure how mod dependencies work, EG: unsure if its expected for dependent mods to work at the latest version or if some mods depend on a specific version of another mod)_
