### ISSUE TITLE
Disabling Mores Breaks Vanilla Tags

### ISSUE THREAD

**Issue by Noobulus** [AstralOrdana/Spelunkery#236]
**Describe the bug:**
Disabling mores causes the game to be unable to load several vanilla tags due to missing references. Notable examples include `#minecraft:mineable/pickaxe` and `#minecraft:gold_ores` tag, which in turn breaks `#minecraft:guarded_by_piglins`.

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version: 1.20.1
Spelunkery version: 1.20.1-0.3.5
Moonlight Lib version: 1.20-2.12.4
Fabric API / QSL / Forge version: 0.92.2+1.20.1

**Other mods:**
None. Reproduced in a clean installation.

**Logs:**
https://mclo.gs/5cwPTqQ

**To Reproduce:**
1. Disable Mores in the Spelunkery common config.
2. Open the game, then load into a world.
3. Check the logs and see all the broken tags.

**Expected behavior:**
Spelunkery's additions to vanilla tags should be marked as required: false in the JSON files so that missing references like this don't prevent the tags from loading. This is a simple change, it just needs to be done on Spelunkery's side.

**Comment by AstralOrdana** [comment]
fixed for 0.3.6
