### ISSUE TITLE
Custom interactions for Handheld Compactor

### ISSUE THREAD

**Issue by gamrguy** [AstralOrdana/Spelunkery#239]
**Feature:**

Allow Handheld Compactor to utilize datapacks and/or tags for automatic compression.

**Alternatives:**

Configs, or other methods of allowing modpacks to add or remove custom compression interactions.

**Additional info:**

Many mods add custom ingots, nuggets, and blocks, or other compressible items. However, the Handheld Compactor functions off of a hardcoded list of interactions and is therefore incapable of interacting with them.

**Comment by AstralOrdana** [comment]
known issue, handheld compactor has been marked as WIP and its recipe removed while a better implementation for it is determined
