### ISSUE TITLE
Possible Adorn + Spelunkery incompat

### ISSUE THREAD

**Issue by ChromaPIE** [AstralOrdana/Spelunkery#24]
**Describe the bug:**
Game won't launch, the crash report mentioned the name of these two mods.

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version: 1.19.2
Spelunkery version: 0.1.7
Moonlight Lib version: 2.2.3
Fabric API / QSL / Forge version: 0.14.13

**Other mods:**
Shown in the crash report.

**Logs:**
https://mclo.gs/oCkD6Rv latest.log
https://mclo.gs/NtlB7ow CR

**Comment by AstralOrdana** [comment]
possibly fixed by recent pr, requires testing when next version releases

**Comment by ChromaPIE** [comment]
Game launches just fine with the latest version.
