### ISSUE TITLE
[Suggestion] Support for Tinker's Construct as well as generic Forge/Fabric item tagging

### ISSUE THREAD

**Issue by Bentcheesee** [AstralOrdana/Spelunkery#240]
**Feature:**

1: Support for Tinker's Construct being Magnetite can be melted into Molten Magnetite and used with various Tinker's tools.  Most likely a similar stat to that of which Iron grants (brings items closer to the player when holding).

2: Generic item/block tagging support for modpacks by using either the Forge/Fabric tag umbrella or the C tag umbrella to add in easier compatibility with other mods.  Especially for mods that add raw vanilla nuggets such as Progression Reborn (Fabric) and Create: Dreams & Desires (Forge/Fabric), or salt such as Salt (Forge)

**Alternatives:**

1: I suppose Tinker's Construct can instead reach out for the compat on their side, but I don't think they would tbh

2: I've been thinking of making an entirely data-side compat mod for modpacks and modpack makers so things that don't already have basic tagging support or tags built into recipes will and I'll add this into the list of mods to update with Forge/Fabric/C tags

**Additional info:**

Any other info should go here.  With more complicated features, it is geneally worth mentioning even the smallest of details you wish to see if the suggestion is approved and implemented.

**Comment by AstralOrdana** [comment]
magnetite turns into normal iron when smelted, having a unique forge-able material wouldnt make sense
