### ISSUE TITLE
[Forge 1.20.1] Placed Salt Causing Issues with Entity Pathfinding

### ISSUE THREAD

**Issue by iBryguy** [AstralOrdana/Spelunkery#241]
**Describe the bug:**
Placed salt lines and piles are intermittently causing problems for entities that are attempting to cross over them. However, it is unclear if the issue is from entities trying to pass the lines, or if it is caused by trying to stand on the lines. In any case, in each instance the entity simply stands on the line while spinning. Sometimes entities will walk past salt with no issues whatsoever, only to then walk back onto salt and start spinning. I've only seen the issue in the past with problems related to pathfinding (such as mobs becoming stuck spinning on slabs), so I assume that this is a related problem.

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version: 1.20.1
Spelunkery version: 0.3.5
Moonlight Lib version: 2.12.9
Fabric API / QSL / Forge version: Forge 47.3.0

**Other mods:**
None

**Logs:**
[latest.log](https://github.com/user-attachments/files/16405132/latest.log)

**To Reproduce:**
1. Using Salt or a Salt Bucket, create lines on the ground.
2. Have, or spawn in, entities near the salt. (Preferably, within an area contained by salt lines and piles.)
3. Observe entities periodically becoming stuck spinning while standing on lines of salt.

**Expected behavior:**
Non-zombies and non-slimes should experience no difficulty crossing the lines of salt, or standing on the salt. 

**Screenshots:**
Video, as a screenshot does not suitably display the issue
https://github.com/user-attachments/assets/4a81c9fb-47e7-489f-8cff-c79fd4c0bcab

**Additional info:**
None at this time.

**Comment by AstralOrdana** [comment]
minecraft mobs just kinda be like that, sorry
