### ISSUE TITLE
[Suggestion] Spring Water Color Compatibility with Embeddium

### ISSUE THREAD

**Issue by KeWHs** [AstralOrdana/Spelunkery#243]
**Feature:**

The latest version of embeddium concludes a pack "sodium" to make it compatible with iris and else. This will make spring water using sodium's render color and it'll turn yellow in game.
Could you just make a mod check of embeddium to solve this problem?

**Comment by AstralOrdana** [comment]
done for 0.3.10

**Comment by etherealgears** [comment]
Spring water is still yellow on 0.3.10 using the latest version of Embeddium (0.3.30).

**Comment by AstralOrdana** [comment]
i added an exception for embeddium's namespace, report it to them

**Comment by embeddedt** [comment]
Spelunkery explicitly uses a yellow spring water fluid color with Embeddium installed.

https://github.com/AstralOrdana/Spelunkery/blob/568030e68152cfd1c05c8ab677b8149bf83ce524/common/src/main/java/com/ordana/spelunkery/fluids/SpringWater.java#L40

I cannot comment on the Sodium 0.6 alphas, but this should not be necessary for Embeddium.
When compiling a version of Spelunkery with this logic removed, there is no issue with the latest version of Embeddium for 1.20.1 (0.3.30). I tested this in a standalone instance with no additional mods installed except ModernFix (which I know does not affect fluid colors).

![2024-08-17_21 04 41](https://github.com/user-attachments/assets/42349712-431e-4cb4-ba19-7130d15a7793)

**Comment by AstralOrdana** [comment]
`|| PlatHelper.isModLoaded("embeddium")` was only added in the latest version, they reported this issue prior to it being added. sodium uses a different RGBA hex order for some reason, thats why the exception exists

**Comment by embeddedt** [comment]
I've just tried Spelunkery 0.3.9 from CurseForge, still seems to have the correct color.

**Comment by AstralOrdana** [comment]
@Dantigator ??

**Comment by AstralOrdana** [comment]
when i put out the next version, ill remove the exception for embeddium then i guess

**Comment by KeWHs** [comment]
@AstralOrdana I've made a PR to solve this problem. I guess this will work. https://github.com/Dantigator/Spelunkery

**Comment by KeWHs** [comment]
Embeddium doesn't render as sodium does(just using vanilla color 0xff43D5EE), but it includes a pack(only name just the same as sodium) to make it compatible with other mods(like iris, sodium extra).  So it will using sodium's render color(yellow 0xffEED543).

**Comment by Dantigator** [comment]
> Embeddium doesn't render as sodium does(just using vanilla color 0xff43D5EE), but it includes a pack(only name just the same as sodium) to make it compatible with other mods(like iris, sodium extra). So it will using sodium's render color(yellow 0xffEED543).

this problem just occurs in fabric version.

**Comment by embeddedt** [comment]
Personally, I would remove the Sodium check on Spelunkery's side entirely. It should not be content mods' job to be working around performance mods aside from exceptional circumstances where it's impossible to support a use case cleanly. Fluid colors are well standardized.

**Comment by AstralOrdana** [comment]
alright
