### ISSUE TITLE
spelunkery-1.20.1-0.3.6-forge minecraft crashes when loading or creating a world.

### ISSUE THREAD

**Issue by maximogta** [AstralOrdana/Spelunkery#244]
**Describe the bug:**
Minecraft crashes when loading or creating a world, does not happen with spelunkery-1.20.1-0.3.5-forge

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version: 1.20.1
Spelunkery version: 0.3.6
Moonlight Lib version: 2.12.11
Fabric API / QSL / Forge version: Forge 47.3.5

**Other mods:**
[crash-2024-08-11_23.00.31-client.txt](https://github.com/user-attachments/files/16576150/crash-2024-08-11_23.00.31-client.txt)

**Logs:**
[latest.log](https://github.com/user-attachments/files/16576159/latest.log)

**To Reproduce:**

1. Start minecraft with spelunkery 0.3.6.
2. Create a new world or load a existing one.
3. Minecraft crashes.

**Expected behavior:**
World loads.

**Screenshots:**
![image](https://github.com/user-attachments/assets/33b5ba26-f636-4948-ac6b-da71dbfe147d)

**Additional info:**
Add any other information that might be needed.

**Comment by Altay5704** [comment]
Seems to be an incompatibility with Create: Dreams and Desires.

**Comment by AstralOrdana** [comment]
yeah apparently theyve removed tin from some versions? no idea what they have going on over there tbh, for now just consider create_dd and spelunkery incompatible

**Comment by LopyLuna** [comment]
> yeah apparently theyve removed tin from some versions? no idea what they have going on over there tbh, for now just consider create_dd and spelunkery incompatible

tin has been removed from the main mod but move to Create: Unify modid is "unify"

**Comment by LopyLuna** [comment]
id suggest moving the support to Create: Unify instead
