### ISSUE TITLE
crying obsidian is no longer harvestable with glass bottles

### ISSUE THREAD

**Issue by kuba26038** [AstralOrdana/Spelunkery#245]
**Describe the bug:**
i tried harvesting dimensional tears from some crying obsidian, but unfortunately doing so doesn't do anything in the latest update. it was completely fine when i played on the previous version, though.

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version: 1.20.1
Spelunkery version: 1.20.1-0.3.6-forge
Moonlight Lib version: 1.20-2.12.11-forge
Fabric API / QSL / Forge version: 47.3.5

**Other mods:**
all of them are listed not too far into the latest.log file by puzzles lib

**Logs:**
*Even if the game does not crash they may be useful!*
Please provide the following logs:
From .minecraft/logs :  "latest.log" as well as "debug.log" if it exists. From .minecraft : "launcher_log" as well as a
file that starts with "hs_err" if it exists. Note: Double check that the logs are from the correct time. ex, don't give
us a log from a month ago because you forgot to check the date.

[debug.log](https://github.com/user-attachments/files/16579073/debug.log)

[latest.log](https://github.com/user-attachments/files/16579081/latest.log)

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1.find a crying obsidian block
2. right-click it with a normal glass bottle,
3.observe as nothing happens

**Expected behavior:**
in all previous versions, these steps would result in the creation of a normal obsidian block and a bottle of dimensional tears. since the removal of this feature wasn't mentioned in the changelog, i assume it's an oversight

**Comment by AstralOrdana** [comment]
not a bug, the config option is just disabled by default now for balance reasons
