### ISSUE TITLE
Incompatbility with Mixins, Levelz and Spelunkry

### ISSUE THREAD

**Issue by TheShadyyOneYT** [AstralOrdana/Spelunkery#246]
**Describe the bug:**

Game crashes automatically when levelz and the latest release of Spelunkery are installed. 

**Versions:**

(THIS IS WITH SUPPLEMENTARIES INSTALLED, shows whether with or without.)
Minecraft version: 1.20.1
Spelunkery version: 0.3.6
Moonlight Lib version: 2.12.11
Fabric API / QSL / Forge version: 0.92.2
Supplementaries (optional): 2.8.17

**Other mods:**

Levelz: 1.4.13
Mixin Conflict helper: 1.2.0

**Logs:**
*Even if the game does not crash they may be useful!*
Please provide the following logs:
From .minecraft/logs :  "latest.log" as well as "debug.log" if it exists. From .minecraft : "launcher_log" as well as a
file that starts with "hs_err" if it exists. Note: Double check that the logs are from the correct time. ex, don't give
us a log from a month ago because you forgot to check the date.

Can't show log due to not even starting up, automatic crash.

**To Reproduce:**

1. Download up above, download levelz and mixin conflict helper as well.
2. Launch the game
3. crashes and comes up with this (with mixin conflict helper installed): https://imgur.com/a/cD8g9oL

**Expected behavior:**

Game crashes and Image above will show you what happens.

**Screenshots:**

Once again: https://imgur.com/a/cD8g9oL

**Additional info:**

Make sure you have Mixin Conflict Helper installed to see this issue, otherwise it might be a code error 1.

**Comment by AstralOrdana** [comment]
crashes still generate logs, without one i cant do anything about this

**Comment by TheShadyyOneYT** [comment]
Well how do I get the logs if I can’t even boot up the game. With exit code error 1 logs don’t generate at all. Is there an alternative way that this could be achieved to retrieve the logs? Within the crash logs folder? To be honest I have no idea.

**Comment by TheShadyyOneYT** [comment]
There is no crash report when its an exit code error 1 that I'm aware of. I have no Idea how else to get the logs other than through Mixin conflict helper. that is the closet I can get to giving you the logs, because the logs will not generate. I've check numerous times waiting for the logs to generate in my crash-reports folder. Unless there is a more complex way of receiving them, would be loved to be enlightened. 

Logs from mixin conflict helper: https://pastebin.com/vESJhwgV

If you are still looking for Minecraft's crash report logs. I guess this issue won't be resolved. Because there is literally no other way that I see to receive the logs when getting an error when logs don't generate under exit **code error 1.** That is why I downloaded mixin conflict helper, as somewhere within the code the mixins or something are injecting and causing an issue between the mods preventing them to be playable with each other.

**Comment by TheShadyyOneYT** [comment]
If you are referring to `latest.log` here you go: https://pastebin.com/JbtUTXnF

**Comment by TheShadyyOneYT** [comment]
![Screenshot 2024-08-16 150100](https://github.com/user-attachments/assets/61be4e8f-39c4-49c9-94e8-d200582f770d)
![Screenshot 2024-08-16 150113](https://github.com/user-attachments/assets/5df481f0-546e-4882-99fe-182c238186d5)
![Screenshot 2024-08-16 150121](https://github.com/user-attachments/assets/fdfcff6b-8c85-436e-9354-a52656ce34df)
![Screenshot 2024-08-16 150130](https://github.com/user-attachments/assets/0eb9454e-e7c9-4963-baeb-bebbd5a13770)

full modlist

**Comment by TheShadyyOneYT** [comment]
and before you mention it, I do see other incompatibles which I will fix now and re-update my `latest.log`

**Comment by AstralOrdana** [comment]
fixed for 0.3.10

**Comment by TheShadyyOneYT** [comment]
Thank you and sorry for the misunderstanding.

**Comment by TheShadyyOneYT** [comment]
It seems to be fine, glad to hear it will fixed next update, thank you.
