### ISSUE TITLE
Raw nugget tags

### ISSUE THREAD

**Issue by HolidayTheRaptor** [AstralOrdana/Spelunkery#250]
Generally, instead of making raw nuggets for ores from individual mods, just make the nuggets for the ore itself. There are many silvers in the modern modding meta, such as oreganized and galosphere and caverns n chasms. I feel it'd be simpler to just make a raw silver nugget that drops from any forge:silver_ore block, rather than specifically oreganized's silver.

**Comment by AstralOrdana** [comment]
not how it works, the individual loot tables from each mods ores need to be altered
