### ISSUE TITLE
"Better Vanilla Gems resource pack is no longer enabled by default" configurable in configs?

### ISSUE THREAD

**Issue by PinkLasagna03** [AstralOrdana/Spelunkery#252]
You've removed the feature where the resource pack is enabled by default, but could you consider making it an option in the config settings? This would be really helpful for us modpack creators.

**Comment by AstralOrdana** [comment]
no, there are plenty of existing tools for that kind of thing already

**Comment by PinkLasagna03** [comment]
> no, there are plenty of existing tools for that kind of thing already

How tho? The resourcepack isn't within the folder. so mods like globalpacks can't access it.
