### ISSUE TITLE
Incompability with newest versions of Moonlight 

### ISSUE THREAD

**Issue by Kallixer** [AstralOrdana/Spelunkery#256]
**Describe the bug:**
Cannot start game due to Spelunkery being incompatible with newest version of Moonlight Lib. (See screenshot)

**Versions:**
Minecraft version: 1.20.1
Spelunkery version: 1.20.1-0.3.10
Moonlight Lib version: fabric_1.20-2.12.16
Fabric API  version: 0.92.2+1.20.1

**Other mods:**
None, I tested it with only Spelunkery + dependents.

**Logs:**
[latest.log](https://github.com/user-attachments/files/16721355/latest.log)

**To Reproduce:**
1. Install newest versions for Spelunkery, MoonlightLib and Fabric API
2. Start the game

**Expected behavior:**
For the game to start up and Spelunkery being compatible with newest version of Moonlight

**Screenshots:**
![Screenshot 2024-08-23 044717](https://github.com/user-attachments/assets/3bc1b96c-e2c1-4bfc-99ce-b115f6444164)

**Additional info:**
-

**Comment by TheShadyyOneYT** [comment]
yep it doesn't work.

**Comment by Eletoast** [comment]
Forge version works fine with Moonlight, this only effects the Fabric version of Spelunkery. Really hoping for an update soon due to the buggy nature of Moonlight version Spelunkery uses right now with servers 🙃.

**Comment by edralzar** [comment]
FIY I edited the jar to force the newest version of Moonlight to be marked as compatible, and it seems to work, so the dependency version can be configured to be `>=1.20.2.12.11`

**Comment by forgettableaccount123** [comment]
> FIY I edited the jar to force the newest version of Moonlight to be marked as compatible, and it seems to work, so the dependency version can be configured to be `>=1.20.2.12.11`

can I please have it?

**Comment by AstralOrdana** [comment]
fixed for 0.3.11
