### ISSUE TITLE
Can't get Bottle O' Dimensional Tears from Crying Obsidian

### ISSUE THREAD

**Issue by Proxillus** [AstralOrdana/Spelunkery#258]
Describe the bug:
The Bottle O' Dimensional Tears describes as being able to be obtained by right clicking Crying Obsidian with an Empty Bottle. As I try to do that, nothing happens. There is no interaction with it. Going back to version 0.3.5 of Spelunkery fixes the issue.

Versions:
Minecraft version: 1.20.1
Spelunkery version: 0.3.10
Moonlight Lib version: 2.12.16
Fabric API / QSL / Forge version: 47.2.32

Other mods:
None

Logs:
Please provide the following logs:
[latest.log](https://github.com/user-attachments/files/16739143/latest.log)

To Reproduce:
1. Open the game with the three mods installed.
2. Grab an empty bottle and right click crying obsidian
3. See it not work

Expected behavior:
Obtain Bottle O' Dimensional Tears and revert the crying obsidian to regular obsidian.

Screenshots:
![image](https://github.com/user-attachments/assets/e3bd5cec-815e-4e17-9107-c7b3499bf039)

Additional info:
None

**Comment by AstralOrdana** [comment]
not a bug, check changelog. config was moved to disabled by default due to the utility of the dimensional tears
