### ISSUE TITLE
[Suggestion] Compatible with Tiny Coal for deepslate coal ore drop

### ISSUE THREAD

**Issue by ChromaPIE** [AstralOrdana/Spelunkery#26]
**Feature:**

If Tiny Coal is present, make deepslate coal ores drop some tiny coals additionally.
This will make deepslate coal ores fit better with the deepslate ore bonus.
(plus i don't know why raw copper nugget is unused. is it intended or not?)

**Alternatives:**

Spelunkery introduces its own item, say coal shards (together with charcoal shards maybe but that'd be kinda off the track) as the secondary drop from deepslate coal ores, each will be enough for smelting 1 item.

**Additional info:**

Tiny Coal: https://www.curseforge.com/minecraft/mc-mods/tiny-coal

**Comment by AstralOrdana** [comment]
1. Good idea, Lumps of Coal implemented for next version
2. raw copper nuggets are only enabled when the create mod is loaded because neither vanilla nor spelunkery add copper nuggets of their own
