### ISSUE TITLE
Item compactor compact non-ores

### ISSUE THREAD

**Issue by TheWitherer** [AstralOrdana/Spelunkery#261]
**Feature:**

On the all mode, the item compactor could use the ability to compact all items that have 2x2 and 3x3 recipes, not just ore blocks
(bamboo, clay, glowstone, hay bales, melons, snow, nether bricks?, slime, rabbit hide, if theres any more i cant think of)

**Alternatives:**

Rename it to ore compactor
Make it data driven (if its hard to code then dont, i'm not your boss)

**Comment by AstralOrdana** [comment]
not planned
