### ISSUE TITLE
Disable lodestone recipe if Tinker's Construct is installed

### ISSUE THREAD

**Issue by MarioSMB** [AstralOrdana/Spelunkery#262]
**Feature:**

Tinker's Construct lets you melt down lodestones to get a netherite ingot. Spelunkery adds a recipe to craft Lodestones way cheaper by using raw magnetite in place of the netherite ingot, making lodestones a super cheap way to get a lot of netherite.  
I'd like to suggest that the recipe check if Tinker's Construct is installed and automatically disable itself, thanks!

**Alternatives:**

N/A

**Additional info:**

None.

**Comment by AstralOrdana** [comment]
no, that should be done on the modpacker's side

**Comment by MarioSMB** [comment]
Not everyone plays with modpacks, this newly added recipe by Spelunkery causes a compatibility issue where one can now obtain infinite netherite easily…  

Lodestones are made with netherite, maybe magnetite should have its own uses?  
Otherwise I suppose I’ll see if Tinker’s Construct is willing to solve this on their end.
