### ISSUE TITLE
Hammer and Chisel breaks non-silk-touchable blocks.

### ISSUE THREAD

**Issue by mortuusars** [AstralOrdana/Spelunkery#264]
Hammer and Chisel breaks (and drops as an item) Budding Amethyst and Mob Spawner. Potentially others, haven't checked all.

Minecraft version: 1.20.1
Spelunkery version: 0.3.10
Moonlight Lib version: 2.12.17
Forge version: 47.3.0

No other mods installed.

Addendum:
You can also dupe pretty much any `#minecraft:mineable/pickaxe` multiblock block (blocks that break together when one part is broken) with Hammer and Chisel. Iron Doors in vanilla. Doors from other mods. Create Large Water Wheel. Etc.

**Comment by AstralOrdana** [comment]
fixed for 0.3.11, but certain modded multiblocks will have to be supported by modpackers cause i cant account for them all
