### ISSUE TITLE
Spelunkery 0.3.10 breaks certain recipes with mushroom tags

### ISSUE THREAD

**Issue by Vipibolt** [AstralOrdana/Spelunkery#266]
The newest version of Spelunkery when used with a couple certain mods will break particular tags and render recipes/functions not working. Mainly has to do with mushroom tags it seems.

Minecraft version: 1.20.1
Spelunkery version: 0.3.10
Moonlight Lib version: 2.12.17
Fabric API / QSL / Forge version: Forge 47.3.0

**Other mods:**
Quark 4.0-460
Zeta 1.0-24
JEI 15.12.2.51

**Logs:**
[latest.log](https://github.com/user-attachments/files/16846862/latest.log)

**To Reproduce:**
1. Install aforementioned mods, alongside most recent spelunkery version 0.3.10
2. Run a Singleplayer world, or join a server even
3. Look at the recipe, try to craft, or even try to put seeds in the pouch

**Expected behavior:**
That the tag wouldn't break

**Screenshots:**
![2024-09-03_02 45 50](https://github.com/user-attachments/assets/6c6644cf-c704-44f8-8b2e-695a48774f34)

**Additional info:**
As expected with a tag breaking, other mods that utilize the tag in their recipes/functions will end up not working as well which is a huge issue

**Comment by erisdev** [comment]
Yep, this bit me too. Looks like `inkcap` and `white_inkcap` were renamed to `inkcap_mushroom` and `white_inkcap_mushroom` but the tag was not updated.

**Comment by AstralOrdana** [comment]
fixed for 0.3.11
