### ISSUE TITLE
Crash Client 1.20.1

### ISSUE THREAD

**Issue by Eriuis** [AstralOrdana/Spelunkery#267]
**Describe the bug:**
When I enter the END dimension and defeat the dragon after the portal back to the overworld is generated, only my client crashes and not the server. (Apologies if I posted the crash report and it wasn't Spelunkry but when I remove the mod and do exactly the same my client doesn't crash :s)

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version: 1.20.1
Spelunkery version: -spelunkery-1.20.1-0.3.10-forge
Moonlight Lib version: -moonlight-1.20-2.12.17-forge / supplementaries-1.20-2.8.17
Fabric API / QSL / Forge version: -forgeVersion, 47.3.0

**Other mods:**
[crash-2024-09-05_13.16.18-client.txt](https://github.com/user-attachments/files/16911572/crash-2024-09-05_13.16.18-client.txt)

**Logs:**

[latest.log](https://github.com/user-attachments/files/16911599/latest.log)
[debug.log](https://github.com/user-attachments/files/16911602/debug.log)

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1.I enter the dimension of the end
2.I finished defeating the dragon
3.After the portal is generated, about 15 seconds later, the client crashes

**Expected behavior:**
Play normally without the client crashing.

**Screenshots:**
If applicable, add screenshots to help explain your problem. https://screenshot.help/

**Additional info:**
I decided to open the problem in Spelunkry because the latest update of the mod in curseforge in the version changeslog: spelunkery-1.20.1-0.3.10-forge.jar

It is mentioned that they fixed a bug regarding 
"fixed portal fluid cauldron bug with amendments mod"

And I relate it to the crash that happens to the client

**Comment by AstralOrdana** [comment]
i dont think this is an spelunkery issue

**Comment by Quarkrus** [comment]
Judging by the logs, you have the latest version of Embedium, I advise you to install an older version (I use 0.3.17), because the new one conflicts a little in rendering with some mods.

**Comment by viidsn** [comment]
> Judging by the logs, you have the latest version of Embedium, I advise you to install an older version (I use 0.3.17), because the new one conflicts a little in rendering with some mods.

I'm having the same issue. Installing an older version of Embedium don't help me

**Comment by viidsn** [comment]
never mind, it was a Radium issue. I replaced it with Canary and crashes stopped
