### ISSUE TITLE
 The "nephrite_charm" makes the experience become 1.2 times

### ISSUE THREAD

**Issue by MonkingRui** [AstralOrdana/Spelunkery#270]
When I storage exp in the "nephrite_charm" and then put it out,my exp becomes 1.2 times

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version:1.19.2
Spelunkery version:0.2.6
Moonlight Lib version:2.2.43
Fabric API / QSL / Forge version: forge43.4.2
![Uploading 2024-09-10_14.21.06.png…]()

**Comment by AstralOrdana** [comment]
"BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries"
