### ISSUE TITLE
Can't use empty bottle on Crying Obsidian, despite the tooltip saying it should work. 

### ISSUE THREAD

**Issue by megatrook** [AstralOrdana/Spelunkery#272]
**Describe the bug:**
I do not get a Bottle o' Dimensional Tears by using an Empty Bottle on a block of Crying Obsidian, despite it's description mentioning that this is how you are supposed to obtain it. It does however work with Respawn Anchors.

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version: 1.20.1
Spelunkery versions: tested on 1.20.1-0.3.11, 1.20.1-0.3.10, and 1.20.1-0.3.6 
Moonlight Lib version: 1.20-2.12.20
Fabric API / QSL / Forge version: 0.92.2+1.20.1

**Other mods:**
This happens with just Spelunkery on its own.

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Obtain Empty Bottle
2. Find or Place Crying Obsidian
3. Right-click on the block of Crying Obsidian with the Empty Bottle in your hand

**Expected behavior:**
I get a Bottle o' Dimensional Tears

**Comment by AstralOrdana** [comment]
can you send a screenshot of the tooltip as im quite sure i fixed that for 0.3.11

**Comment by AstralOrdana** [comment]
also, its a config now, you get the bottles from respawn anchors now by default

**Comment by megatrook** [comment]
oh alright, cool! sorry, i dont have a screenshot handy, but i can confirm that it did say that on the versions i tested i'm pretty sure...
