### ISSUE TITLE
Change to Fungus Fanatic advancement

### ISSUE THREAD

**Issue by Kelpiesaurus** [AstralOrdana/Spelunkery#274]
It's not so much a bug as a slight inconvenience and inconsistency, but the every_fungus advancement should follow the same format as the every_ore advancement so players can see how many items to collect and what progress they've made.

I reworked the every_fungus.json file to match the every_ore.json structure and tested that it works in spelunkery-1.20.1-0.3.12-forge. It works alongside Better Advancements as well as Advancements Tracker and Overview.

Here is the reworked file:

`{
  "display": {
    "icon": {
      "item": "spelunkery:phosphor_fungus"
    },
    "title": {
      "translate": "advancements.spelunkery.every_fungus.title"
    },
    "description": {
      "translate": "advancements.spelunkery.every_fungus.description"
    },
    "frame": "challenge",
    "show_toast": true,
    "announce_to_chat": true,
    "hidden": false
  },
  "parent": "spelunkery:spelunkery/conk_fungus",
  "criteria": {
    "red_mushroom": {
      "trigger": "minecraft:inventory_changed",
      "conditions": {
        "items": [
          {
            "items": [
              "minecraft:red_mushroom"
            ]
          }
        ]
      }
    },
    "brown_mushroom": {
      "trigger": "minecraft:inventory_changed",
      "conditions": {
        "items": [
          {
            "items": [
              "minecraft:brown_mushroom"
            ]
          }
        ]
      }
    },
    "crimson_fungus": {
      "trigger": "minecraft:inventory_changed",
      "conditions": {
        "items": [
          {
            "items": [
              "minecraft:crimson_fungus"
            ]
          }
        ]
      }
    },
    "warped_fungus": {
      "trigger": "minecraft:inventory_changed",
      "conditions": {
        "items": [
          {
            "items": [
              "minecraft:warped_fungus"
            ]
          }
        ]
      }
    },
    "conk_fungus": {
      "trigger": "minecraft:inventory_changed",
      "conditions": {
        "items": [
          {
            "items": [
              "spelunkery:conk_fungus"
            ]
          }
        ]
      }
    },
    "milly_bubcap": {
      "trigger": "minecraft:inventory_changed",
      "conditions": {
        "items": [
          {
            "items": [
              "spelunkery:milly_bubcap"
            ]
          }
        ]
      }
    },
    "inkcap_mushroom": {
      "trigger": "minecraft:inventory_changed",
      "conditions": {
        "items": [
          {
            "items": [
              "spelunkery:inkcap_mushroom"
            ]
          }
        ]
      }
    },
    "white_inkcap_mushroom": {
      "trigger": "minecraft:inventory_changed",
      "conditions": {
        "items": [
          {
            "items": [
              "spelunkery:white_inkcap_mushroom"
            ]
          }
        ]
      }
    },
    "phosphor_fungus": {
      "trigger": "minecraft:inventory_changed",
      "conditions": {
        "items": [
          {
            "items": [
              "spelunkery:phosphor_fungus"
            ]
          }
        ]
      }
    },
    "mushgloom": {
      "trigger": "minecraft:inventory_changed",
      "conditions": {
        "items": [
          {
            "items": [
              "spelunkery:mushgloom"
            ]
          }
        ]
      }
    },
    "button_mushroom": {
      "trigger": "minecraft:inventory_changed",
      "conditions": {
        "items": [
          {
            "items": [
              "spelunkery:button_mushroom"
            ]
          }
        ]
      }
    },
    "crimini": {
      "trigger": "minecraft:inventory_changed",
      "conditions": {
        "items": [
          {
            "items": [
              "spelunkery:crimini"
            ]
          }
        ]
      }
    },
    "portabella": {
      "trigger": "minecraft:inventory_changed",
      "conditions": {
        "items": [
          {
            "items": [
              "spelunkery:portabella"
            ]
          }
        ]
      }
    }
  },
  "requirements": [
    [
      "red_mushroom"
    ],
    [
      "brown_mushroom"
    ],
    [
      "crimson_fungus"
    ],
    [
      "warped_fungus"
    ],
    [
      "conk_fungus"
    ],
    [
      "milly_bubcap"
    ],
    [
      "inkcap_mushroom"
    ],
    [
      "white_inkcap_mushroom"
    ],
    [
      "phosphor_fungus"
    ],
    [
      "mushgloom"
    ],
    [
      "button_mushroom"
    ],
    [
      "crimini"
    ],
    [
      "portabella"
    ]
  ]
}`

**Comment by Kelpiesaurus** [comment]
[every_fungus.json](https://github.com/user-attachments/files/17006737/every_fungus.json)

Wow, the markdown does not keep the structure, huh? Here's an attachment of the actual file. Hope that actually works.

**Comment by AstralOrdana** [comment]
cool, thank you, will implement for 0.3.13
