### ISSUE TITLE
loot tables adjustment issue

### ISSUE THREAD

**Issue by Nuclear-Smile** [AstralOrdana/Spelunkery#275]
Hello, we have recently been editing a minecraft integrations pack which included your mod.

We're dealing with the problem that Sluices getting netherite scrap from lava, which involves a balance tweak to our integration pack. 

Unfortunately, a config file does not seem to exist that allows us to change the way how Sluices handling of lava.

We'd like to know how to adjust the loot tables in your mod, or change it in some other way.

regards

**Comment by SiverDX** [comment]
https://github.com/search?q=repo%3AAstralOrdana%2FSpelunkery%20scrap&type=code

-> 

https://github.com/AstralOrdana/Spelunkery/blob/c69ff703e5940fb3ec446cdb89e802162c7db5ac/common/src/main/resources/data/spelunkery/loot_tables/gameplay/sluice/lava/passive.json#L20
