### ISSUE TITLE
[Suggestion] Delete related items, blocks and recipes when features are disabled

### ISSUE THREAD

**Issue by rafaelkai** [AstralOrdana/Spelunkery#276]
**Feature:**

It would be nice  if disabling mores, rough gems or raw nuggets disabled the related items of those features (rough gems blocks, raw ore nuggets, diamond grindstone, etc). This would help declutter creative inventories of blocks and items that are not really used ingame if those features are disabled.

**Comment by AstralOrdana** [comment]
not planned
