### ISSUE TITLE
Farmers Delight Food Compatibility Broken Code

### ISSUE THREAD

**Issue by ShikiTochi** [AstralOrdana/Spelunkery#278]
**Describe the bug:**
A couple food recipes with some broken code
Vegetable noodles, Dumplings and Hamburger

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version:1.20.1
Spelunkery version:1.20.1-0.3.13
Moonlight Lib version:
fabric_1.20-2.13.2
Fabric API / QSL / Forge version:0.92.2+1.20.1

**Other mods:**
Farmers Delight
Create

**Expected behavior:**
Just some broken code for food compatibility with Farmers delight
Vegetable noodles- noodles tag was "c:foods/pasta" instead of "c:foods/pastas"
Dumplings- dumplings tag was "c:crops/doughs" instead of "c:foods/doughs"
Hamburger- tag was "c:foods/bread" instead of "c:foods/breads"

**Comment by NicoNekoDev** [comment]
Had the same issue. Luckily removing the mod didn't break my world too much.

**Comment by xenia-foxtrot** [comment]
For anyone else having this issue, I've created a datapack that fixes this: https://github.com/ILikePizza555/spelunkery-farmers-delight-fix

**Comment by AstralOrdana** [comment]
fixed for 0.3.14
