### ISSUE TITLE
Spring Water Texture

### ISSUE THREAD

**Issue by ShikiTochi** [AstralOrdana/Spelunkery#279]
**Describe the bug:**
Sodium causes spring water to become a yellow color instead of the light blue its supposed to be naturally

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version:1.20.1
Spelunkery version:1.20.1-0.3.13
Moonlight Lib version:fabric_1.20-2.13.7
Fabric API / QSL / Forge version:0.92.2+1.20.1

**Other mods:**
All mods were added AFTER troubleshooting what mod caused the texture bug
Jade
Sodium

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1.Install Spelunkery and Sodium
2.Place spring water anywhere

**Expected behavior:**
Texture to match the spring water in the bucket

**Screenshots:**
![spring water texture](https://github.com/user-attachments/assets/ad057f0d-bfbb-4b66-b91a-ef2f36043957)

**Comment by SiverDX** [comment]
see https://github.com/AstralOrdana/Spelunkery/issues/243#issuecomment-2295273358

**Comment by AstralOrdana** [comment]
should be reported to sodium
