### ISSUE TITLE
Config Option To Disable Individual Ore Features

### ISSUE THREAD

**Issue by Blunder-G** [AstralOrdana/Spelunkery#28]
**Feature**

1. Config option to enable/disable large Emerald, Lapis, Gold, Diamond, Coal veins
2. Config option to enable/disable Andesite Emerald, Smooth Basalt Diamond, Sandstone Lapis and Calcite Redstone ores
3. Config option to enable/disable Smooth Basalt stripes

**Alternatives:**

1. Changing data files in the Spelunkery mod to make a datapack that removes ore veins and stripes
2. Using Block Swap mod to swap the ores with their stone types (like andesite emeald with andesite)
3. No alternative ways other than disabling the whole stripe feature

**Comment by AstralOrdana** [comment]
The andesite emerald etc ores only generate within their respective large veins which can already be disabled via datapack
There's already a config to enable the basalt stripes, it is not feasible to make each type of stone stripe independently configurable at this time

**Comment by Blunder-G** [comment]
> The andesite emerald etc ores only generate within their respective large veins which can already be disabled via datapack There's already a config to enable the basalt stripes, it is not feasible to make each type of stone stripe independently configurable at this time

Are there any istructions how to disable them?
