### ISSUE TITLE
[suggestion] Link nether portals lit with dimensional tears to the nether coords of its original respawn anchor

### ISSUE THREAD

**Issue by TheBearodactyl** [AstralOrdana/Spelunkery#283]
**Feature:**

When a Bottle 'o Dimensional Tears is used to ignite a nether portal, have that nether portal link to the corresponding nether coords of the respawn anchor it was originally linked to

for example:
if i had a Bottle 'o Dimensional Tears and it was linked to -1500 64 800 and lit a nether portal with it, that nether portal should be linked to the nether coords -188 64 100

**Comment by SiverDX** [comment]
Just to note but the coordinate logic is handled in `NetherPortalBlock` on the fly (i.e. it's not a location being stored)
Considering it's just a normal block you cannot story any unique information in it
(The creation of the destination portal might be but every time it will try to find the correct portal you'd need to modify the coordinates it's looking for)

You'd have to store it in some world or chunk data storage (forge has support for sth. like that, don't now if fabric has too) for all portal blocks created (which even in vanilla might be up to 441 blocks)

And once a block is destroyed (i.e. portal deactivates) you'd have to remove all linked blocks you have stored as well
(should be doable by removing them in the `updateShape` call of `NetherPortalBlock`)

So technically possible just unsure if the devs would want to bother with it

**Comment by AstralOrdana** [comment]
not planned

**Comment by TheBearodactyl** [comment]
why not close it as not planned then...?

**Comment by TheBearodactyl** [comment]
oki that makes a lot more sense.
if i were to open a PR that added what i described without any major bugs, would that be merged or not?
