### ISSUE TITLE
[Suggestion] Config option for magnetic compass to point to true north in other dimensions

### ISSUE THREAD

**Issue by Cephelo** [AstralOrdana/Spelunkery#284]
**Feature:**
A config option for the Magnetic Compass to point to True North in other dimensions would be great - currently, in the nether, it wobbles around like any other compass.  This would be a great alternative to Quark's "Compasses work everywhere" feature, and would grant the Magnetic Compass more versatility.

**Comment by AstralOrdana** [comment]
not planned
