### ISSUE TITLE
sluice crawl glitch

### ISSUE THREAD

**Issue by tetrazine14** [AstralOrdana/Spelunkery#289]
Describe the bug:
weird sluice hitbox interaction makes the player crawl into sluice

Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)
Minecraft version: 1.20.1
Spelunkery version: 1.20.1-0.3.13
Moonlight Lib version: 1.20-2.13.14
Fabric API / QSL / Forge version: 0.92.2+1.20.1

Other mods:
no other mods

Logs:
https://mclo.gs/iA6SezA

To Reproduce:
Steps to reproduce the behavior. Format it as a numbered list of steps.

1.open game
2.place sluice
3.walk at sluice's diagonal
4.crawl

Expected behavior:
not do that

Screenshots:
![image](https://github.com/user-attachments/assets/875f9d1f-a224-4a6c-86b0-390ac4235c3d)

Additional info:
low priority
kinda funny ngl

**Comment by AstralOrdana** [comment]
wont fix
