### ISSUE TITLE
Old Custom Grindstone Recipes Don't Work

### ISSUE THREAD

**Issue by Lonemind** [AstralOrdana/Spelunkery#290]
Data driven grindstone recipes from as far back as 0.3.9 no longer seem to function. Trying to use them just opens the grindstone GUI. Looking through the data files that come with the mod didn't seem to have any examples I could use to create new recipes. Is this being discontinued?

Minecraft version: 1.20.1
Spelunkery version: 0.3.13
Moonlight Lib version: 2.13.14
Supplementaries: 2.8.17
Fabric API / QSL / Forge version: 47.3.11

**Other mods:**
https://postimg.cc/5jChbjZR

**Comment by CraftyZombie** [comment]
The old recipe system has been replaced with loot tables. 
See here: https://github.com/AstralOrdana/Spelunkery/tree/1.20.1/common/src/main/resources/data/spelunkery/loot_tables/gameplay/grindstone_polishing

**Comment by Lonemind** [comment]
When making a grindstone loot table how do I specify a modded item _to use as the ingredient_? I don't see a spot in the loot_table to tell the grindstone that I want to, for instance, grind twilightforest:raw_ironwood into another item.

Edit in italics.

**Comment by SiverDX** [comment]
> her item.
> 
> Edit in italics.

the path of the item resource is used to look up the grindstone recipe (`twilightforest` is the namespace)
e.g. for your item it would be a file named `raw_ironwood.json` instead of `andesite.json` like here:
https://github.com/AstralOrdana/Spelunkery/blob/1.20.1/common/src/main/resources/data/spelunkery/loot_tables/gameplay/grindstone_polishing/andesite.json

**Comment by Lonemind** [comment]
> > her item.
> > Edit in italics.
> 
> the path of the item resource is used to look up the grindstone recipe (`twilightforest` is the namespace) e.g. for your item it would be a file named `raw_ironwood.json` instead of `andesite.json` like here: https://github.com/AstralOrdana/Spelunkery/blob/1.20.1/common/src/main/resources/data/spelunkery/loot_tables/gameplay/grindstone_polishing/andesite.json

I must be doing something wrong. After your comment I restructured how I was doing my folder structure. It's now `data/twilightforest/loot_tables/gameplay/grindstone_polishing/`. I then put `raw_ironwood.json` into that folder and reload but the grindstone does not seem to recognize the item and opens it's default GUI.

Here's a copy of the json I'm using: https://pastebin.com/tFG1exv6
To be safe I just copied rough_azurite.json and changed the output item to ironwood_ingot but to no avail. I can only assume I'm not understanding something crucial.

**Comment by SiverDX** [comment]
I probably confused you with the mention of the namespace
those grindstone recipes / loot tables need to be in the `spelunkery` namespace

so it's always:
`/spelunkery/loot_tables/gameplay/grindstone_polishing/<path_of_item_resource>.json`
or
`/spelunkery/loot_tables/gameplay/diamond_grindstone_polishing/<path_of_item_resource>.json`

**Comment by Lonemind** [comment]
Grr... now I am stumped. That's how I had it beforehand and it wasn't working then either. I just now tried it again from within the spelunkery folder instead and still no luck.

I did a test to see if I could overwrite one of the default recipes (rough lazurite to produce bedrock instead of lapis) and no change occured. Rough lazurite continued to produce lapis. It's as if it doesn't register my changes at all.

I am using kubejs to load the datapack. That wouldn't possibly affect it, would it? I wouldn't think it would...

**Comment by SiverDX** [comment]
if it doesn't register any changes (even to the current data) then it sounds like an issue how your datapack is being applied
did you try it with a normal datapack to check?

**Comment by Lonemind** [comment]
I admit I'm inexperienced in making datapacks the normal way so here's the structure I used to make a test datapack:

`.minecraft\saves\testworld\datapacks\testpack\data\spelunkery\loot_tables\gameplay\grindstone_polishing\`
I added an pack.mcmeta and a pack.png. I'm using 1.20.1 so I set the pack_format to 15.

I then used the default `rough_lazurite.json` file from the spelunkery.jar and changed lapis to bedrock as a test. No change took place.

I then tried making a new file, "raw_ironwood.json". It's a copy of the rough_lazurite.json, still using bedrock as the result. I reloaded and tried the raw ironwood on the grindstone. The recipe was ignored and it opened the grindstone GUI.

Do you happen to have a custom datapack that is currently working to add/change Spelunkery grindstone recipes? If you send me a copy I could study it and see what I'm doing wrong.

Also, is there a discord I could use for all this? I feel bad for spamming github issues.

**Comment by SiverDX** [comment]
ah wait bedrock is not an actual output, it's the depletion chance
(same way how experience bottle is not an actual item output but rather the amount of experience you'll get)

in this pack i modified rough emerald to give wheat instead
[test_datapack.zip](https://github.com/user-attachments/files/17532564/test_datapack.zip)

**Comment by Lonemind** [comment]
Ugh. Please ignore my last post. I made a mistake in making the datapack and also one in the kubejs pack I was using earlier.

It was indeed all user error. My fault. Everything is working as intended now. My apologies and I appreciate all the help and patience you have given me today!
