### ISSUE TITLE
Galosphere 1.4+ cause Recovery Compass disappears after death

### ISSUE THREAD

**Issue by tr1kright** [AstralOrdana/Spelunkery#291]
**Describe the bug:**
Recovery Compass disappears after death

**Versions:**
Minecraft version: 1.20.1
Spelunkery version: 0.3.13
Moonlight Lib version: 2.13.14
Forge version: 47.3.10

**Other mods:**
![mods1](https://github.com/user-attachments/assets/17b9533a-576e-46f7-b15c-9638020be71e)
![mods2](https://github.com/user-attachments/assets/50710dbc-d001-47c8-b52d-91bf156b463e)
![mods3](https://github.com/user-attachments/assets/798fe33c-b2a9-4200-a08d-32def61ae81e)
![mods4](https://github.com/user-attachments/assets/2bfb726a-e7f7-4ef3-a090-41962fe68258)
![mods5](https://github.com/user-attachments/assets/880de317-a42d-40c2-8ade-93fba7b8d94b)
![mods6](https://github.com/user-attachments/assets/5ee218a2-1471-4919-bea5-8b71d1ca4167)
![mods7](https://github.com/user-attachments/assets/67a42523-460e-47c0-bf45-906bc3b492b0)
![mods8](https://github.com/user-attachments/assets/6dd25848-0b97-4350-bde6-b43ab7d2f569)

**Logs:**
[latest.log](https://gist.github.com/tr1kright/0ec7631a04c6ddec22dec442b928f7ac)
[debug.log](https://gist.github.com/tr1kright/d5d167c3e796088994af375ff892cf28)

**To Reproduce:**
1. Dies
2. Respawn and realize that there is no compass

**Expected behavior:**
Recovery compass should appear

**Additional info:**
I don't know English very well, I hope it's clear

**Comment by K0rS1z** [comment]
Hello from the developers of FreshCraft

**Comment by K0rS1z** [comment]
And you don't have a compass, because everything and everything is mixed up + Galosphere 1.4.1 (Which caused the issue itself.)

**Comment by tr1kright** [comment]
I wasn't totally sure what the message meant, but yeah, Galosphere 1.4+ does mess with the compass. Thanks Lavash)

**Comment by tr1kright** [comment]
And yeah, sorry about the delay.

**Comment by K0rS1z** [comment]
> And yeah, sorry about the delay.

I've seen your nickname somewhere, but I don't remember where. Can I write to you in the discord? I would like your ID
