### ISSUE TITLE
End covered in Dimensional Tears

### ISSUE THREAD

**Issue by PinkLasagna03** [AstralOrdana/Spelunkery#292]
**Describe the bug:**
It seems like the whole "floor" of the end is covered in Dimensional Tears

![2024-10-29_16 23 09](https://github.com/user-attachments/assets/f2bd1bbd-c3a6-4072-a7a1-eb53f6d6952a)
![2024-10-29_16 23 42](https://github.com/user-attachments/assets/17166856-2a38-4da4-92cd-e88763cda936)

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version: 1.20.1
Spelunkery version: 0.3.13
Moonlight Lib version: 2.13.18
Forge version: 47.3.0

**Other mods:**
See Log

**Logs:**
*Even if the game does not crash they may be useful!*

[latest.log](https://github.com/user-attachments/files/17559380/latest.log)

**Expected behavior:**
The End not to be covered with Dimensional Tears

**Comment by AstralOrdana** [comment]
this is a feature of the mod, why you would assume this is a bug baffles me

**Comment by PinkLasagna03** [comment]
@AstralOrdana The reason why I assume this is a bug, is because this feature feels very out of place. It isn't mentioned on the Wiki. Also, it takes the whole idea of the End being an empty void and the dangers of falling in the void away.

Is there a way to disable this feature?

**Comment by SiverDX** [comment]
yes, see common configs

![grafik](https://github.com/user-attachments/assets/4c6d5eeb-5ece-4c5b-9edd-931002ebcb39)
