### ISSUE TITLE
incompatibility with large ore veins deluxe 

### ISSUE THREAD

**Issue by Killeronduty1** [AstralOrdana/Spelunkery#298]
**Describe the bug:**
when spelunkery is present with large ore veins deluxe, diamond, redstone and lapis large ore veins appear to be removed from generation however vanilla generation is the same. 

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version:1.20.1
Spelunkery version:1.20.1-0.3.13
Moonlight Lib version:1.20.2-2.13.26
Large Ore Veins Deluxe:1.2.2
Forge version:47.3.11

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

place mods large ore veins deluxe, moonlight, and spelunkery into mods folder. (I recommend using the X-ray texture pack to better see the issue) 
start the game and load into new world
go to bottom of the world (Y -50 to Y 15) and look around with texture pack to see results.

**Expected behavior:**
large deposits of diamond, lapis and redstone

**Screenshots:**

(whats expected)

![2024-11-17_17 56 31](https://github.com/user-attachments/assets/eceb358d-4fb9-44fb-bf01-190cd8865573)

![2024-11-17_17 56 52](https://github.com/user-attachments/assets/9c02c1e1-b8ab-4679-9f13-548b853a1521)

(not proper)

![2024-11-17_17 54 16](https://github.com/user-attachments/assets/9c930b01-a052-4db5-be18-4cddc920e136)

![2024-11-17_17 54 53](https://github.com/user-attachments/assets/4b6455ae-e6b8-4192-953c-3f3be2255e8b)

**Comment by AstralOrdana** [comment]
unfixable without bespoke compat created. spelunkery has its own large ore veins so this is not planned from my end
