### ISSUE TITLE
[Feature Request] Compatibility with Mining Master

### ISSUE THREAD

**Issue by Tsunamori74** [AstralOrdana/Spelunkery#30]
It would be really nice to see, if it’s not in the books that’s perfectly fine but I think it’s the most polished gem-based mod out there from a reputable modding team.

**Comment by AstralOrdana** [comment]
I can't see any viable way for this to work, given that MM has so many different crystal types and there's no real reason you'd want to divide them down into shards and adding rough forms of them would be an unnecessary extra step for something with one use
