### ISSUE TITLE
Dimensional tears ocean in End causes any naturally spawning flying entities to crowd at End spawn

### ISSUE THREAD

**Issue by flynnvali** [AstralOrdana/Spelunkery#300]
If any mod is installed that adds mobs that float around the end (major example being Alex's Mobs with the Endergrade and Cosmic Cod), these entities will enter the dimensional fluid ocean and crowd End spawn as long as any chunks are loaded in the End.

A simple solution would be adding a config option to make it so entities cannot enter the ocean or dimensional tears fluid as a whole.

**Comment by AstralOrdana** [comment]
theres an entity tag for precisely this purpose
