### ISSUE TITLE
[Crash with Sullys Mod]

### ISSUE THREAD

**Issue by Git-Reternos** [AstralOrdana/Spelunkery#307]
**Describe the bug:**
A clear and concise description of what the bug is. Include as much information as you can. Images are often helpful, especially screenshots of the F3 debug menu.

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version: 1.20.1
Spelunkery version: 0.3.13
Moonlight Lib version: 2.13.37
Fabric API / QSL / Forge version: 47.3.12

**Other mods:**
List all mods that you're using; could be in the form of a list of the filenames, a crash report list, a screenshot of
the mods folder, etc. Just make sure all mods used are known!

**Logs:**
*Even if the game does not crash they may be useful!*
Please provide the following logs:
From .minecraft/logs :  "latest.log" as well as "debug.log" if it exists. From .minecraft : "launcher_log" as well as a
file that starts with "hs_err" if it exists. Note: Double check that the logs are from the correct time. ex, don't give
us a log from a month ago because you forgot to check the date.
[crash-2024-12-14_14.14.01-client.txt](https://github.com/user-attachments/files/18134565/crash-2024-12-14_14.14.01-client.txt)

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Installing spelunkery and sullys(3.2.0) mod
2. Generating new world
3. Game crash 

**Expected behavior:**
not crash
**Screenshots:**
If applicable, add screenshots to help explain your problem. https://screenshot.help/

**Additional info:**
Add any other information that might be needed.
https://www.curseforge.com/minecraft/mc-mods/sullys-mod

**Comment by Not-February** [comment]
I've reproduced this with a minimal instance and no other mods installed, just for the sake of being thorough. Steps to reproduce are the same, it occurs on generating a new world.

Sully's Mod removed some of its jade variants with its most recent update, so the fact that this crash report is complaining about polished jade tracks.

[crash-2024-12-14_03.52.42-client.txt](https://github.com/user-attachments/files/18135659/crash-2024-12-14_03.52.42-client.txt)
[latest.log](https://github.com/user-attachments/files/18135663/latest.log)

**Comment by Uraneptus** [comment]
This is caused by sullys mod changing some registry names in 3.2.0. Spelunkery has some recipes that still use the old registry names, that's what's causing the crash.
The registry name in question is `polished_jade` which was renamed to `jade`
I already mentioned this to Ordana yesterday!
