### ISSUE TITLE
Spring water has the same color as urine.

### ISSUE THREAD

**Issue by dotCatshark** [AstralOrdana/Spelunkery#311]
**Describe the bug:**
Spelunkery spring water has an unfortunate color. It looks suspiciously like urine.

**Versions:**
Minecraft version: 1.20.1
Spelunkery version: 1.20.1-0.3.13
Moonlight Lib version: Fabric_1.20-2.13.40
Fabric API / QSL / Forge version: 0.92.2+1.20.1

**Other mods:**
![image](https://github.com/user-attachments/assets/f656385b-70c1-4924-82d6-c1d159bf7d0f)
![image](https://github.com/user-attachments/assets/e4cb95b9-4799-4c6a-908d-7d74115fc9a4)
![image](https://github.com/user-attachments/assets/0f7ff02b-26db-4595-9cff-3bfe8d67031e)
![image](https://github.com/user-attachments/assets/a508ed88-571b-413b-9c85-dc8b9d5ea870)
![image](https://github.com/user-attachments/assets/3e90e824-c142-4c36-9f76-64287c251ab0)
![image](https://github.com/user-attachments/assets/c1e896af-9b0e-4373-8c95-50435da14abd)

**Logs:**
[latest.log](https://github.com/user-attachments/files/18255246/latest.log)

**To Reproduce:**
1. Launch game and load into a world
2. Get bucket of spring water from the creative inventory or find some naturally
3. Place it down and look at it
4. Notice that it is yellow, and not blue

**Expected behavior:**
Spring water is beautiful bright blue, and not dehydrated dry yellow.

**Screenshots:**
![image](https://github.com/user-attachments/assets/8b168402-ed69-4c7b-8807-f6ab2ee4d4bb)

**Additional info:**
I strongly suspect this is geophilic messing with the biome color and messing things up. I will remove it to check and update this post once that is done.
Update: Removed geophilic. Water still piss colored. It also might be Blooming Nature.

**Comment by AstralOrdana** [comment]
caused by sodium

**Comment by theDerxu** [comment]
> caused by sodium @AstralOrdana 

I understand this isn't a problem on the mod's end, but I cannot change sodium version if it gets fixed and was wondering if this was maybe something that could be fixed via resourcepack? or changing the fluid to use a custom texture over the default and recoloured
