### ISSUE TITLE
Portal Fluid Crash

### ISSUE THREAD

**Issue by Blunder-G** [AstralOrdana/Spelunkery#32]
**Describe the bug:**
Client crash related to Portal Fluid. It happens when Forge finishes mod loading

**Versions**
Minecraft version: 1.19.2
Spelunkery version: 0.1.8
Moonlight Lib version: 2.2.5
Fabric API / QSL / Forge version: 43.2.4

**Other mods:**
Mod list in the crash report

**Logs:**
Crash Report: [crash-2023-02-04_17.07.45-client.txt](https://github.com/AstralOrdana/Spelunkery/files/10608806/crash-2023-02-04_17.07.45-client.txt)
Log: 
[latest.log](https://github.com/AstralOrdana/Spelunkery/files/10608808/latest.log)

Debug log: 
[debug.log](https://github.com/AstralOrdana/Spelunkery/files/10608809/debug.log)

**Additional Info**

Doesn't crash with Spelunkery 0.1.6

**Comment by DigitalPopsicle** [comment]
I'm also getting this same crash with no other mods installed besides Moonlight Lib.

[Crashlog](https://pastebin.com/aJQdvMcv)

**Comment by AstralOrdana** [comment]
new version has been released, lmk if the crash persists

**Comment by hw111s** [comment]
> new version has been released, lmk if the crash persists

I just experienced the same crash after the update.

**Comment by AstralOrdana** [comment]
update moonlight lib?

**Comment by hw111s** [comment]
tried a reinstall of moonlight, no luck

**Comment by AstralOrdana** [comment]
can anyone else replicate this with Spelunkery 0.1.9 and Moonlight 2.2.5? Using the newest version of those mods I have been unable to replicate this issue

**Comment by hw111s** [comment]
just saying new version no longer crashes :) excited to try the mod

**Comment by AstralOrdana** [comment]
thank you
