### ISSUE TITLE
The tooltip issue never comes to an end.

### ISSUE THREAD

**Issue by ChromaPIE** [AstralOrdana/Spelunkery#36]
**Describe the bug:**
I got a pretty strange ketbind for all the games I play. I crouch/sneak with Space. So yes, I need to hold space and use gems on the grindstone to polish a whole stack at once. The tooltip has no problem with this.

But the thing is, you still need to hold Shift, not Space (not anything else too, it seems to be hardcoded), for more info when hovering the cursor over Spelunkery items. Since the two placeholders share one value: The name of the key you bound to Sneak, the tooltip let me hold Space for extra info, which is actually not the case.

The mod version is 0.1.10, the latest. No need to provide more info about the bug, i guess. If it's needed, rememeber to hold Shift, no matter how your keybind is.

**Comment by AstralOrdana** [comment]
Yes, i know that's happening, it's a limitation of how tooltips work that we are currently working on

**Comment by ChromaPIE** [comment]
The once and for all solution is to simply change it to "Shift", replacing the placeholder. It's hardcoded and can't be changed after all. But if you want to just take ur time.

**Comment by AstralOrdana** [comment]
resolved, latest update supports configurable keybinds and the tooltip automatically matches
