### ISSUE TITLE
Unregistered Fluid

### ISSUE THREAD

**Issue by soup587** [AstralOrdana/Spelunkery#37]
Dimensional Fluid is unregistered, causing various issues, including a broken name when displayed in various methods (fluid_type.unregistered_sadface) and not being an applicable fluid for storage.

Minecraft version: 1.19.2
Spelunkery version: 0.1.11
Moonlight Lib version: 2.2.6
Fabric API / QSL / Forge version: Forge 43.2.4

**Other mods:**
N/A, I think?

**Logs:**
N/A?

**To Reproduce:**

1. Try storing Dimensional Fluid in a container and or view fluid in item viewer mod

**Expected behavior:**

Dimensional fluid can be stored in and transferred to modded tanks

**Comment by ThugPug43** [comment]
I got the same thing on Forge 43.2.0
Moonlight Lib 2.2.6
Spelunkery 0.1.11
1.19.2

![2023-02-11_16 35 25](https://user-images.githubusercontent.com/31190716/218283993-b470edfa-2aa1-4598-966e-20320bc1b72a.png)

On Fabric when I tested it worked fine
Spelunkery 0,1.11
Fabric 0.14.14
MoonlightLib 1.19.2-2.2.6
1.19.2

![2023-02-11_16 45 40](https://user-images.githubusercontent.com/31190716/218284223-55aaf028-80e8-4386-95d6-2f908bb7c21e.png)

**Comment by AstralOrdana** [comment]
fixed via update to Moonlight Lib 2.2.7 
(still missing translation string, dw about it I've already fixed that for the next version)

**Comment by f0rttnite** [comment]
awesome, thanks

**Comment by f0rttnite** [comment]
okay it seems semi-fixed?
i had to replace the create pump i was using and i can't manually store fluid in tanks in creative mode but otherwise it does seem to work?

**Comment by AstralOrdana** [comment]
issue has been determined to be related to the bucket item itself, working on a fix

**Comment by AstralOrdana** [comment]
does this persist in latest version of the mod?
