### ISSUE TITLE
How to obtain redstone?

### ISSUE THREAD

**Issue by OnesAndZer0s** [AstralOrdana/Spelunkery#38]
- To get redstone, you crush cinnabar with the crushing wheels
- the crushing wheels are crafted with the mechanical crafters
- mechanical crafters require electron tubes
- electron tubes require polished rose quartz
- polished rose quarts requires rose quartz
- rose quartz requires quartz and redstone.

It is incredibly painful to get redstone ( killing witches, silk touch and furnace, etc ) otherwise. Is this intentional.

**Comment by AstralOrdana** [comment]
redstone is obtained by polishing rough cinnabar on a grindstone
