### ISSUE TITLE
Strips of tuff, andesite, granite, and diorite do not generate in the Forge version of the mod unlike the Fabric version

### ISSUE THREAD

**Issue by WitheredWasabi** [AstralOrdana/Spelunkery#4]
**Describe the bug:**
Strips of tuff, granite, andesite, and diorite do not generate in the Forge version of the mod.

**Versions:**
Latest versions of spelunkery and moonlight lib on Minecraft 1.19.2, Forge 43.1.25

**Other mods:**
No other mods installed

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Install only Moonlight Lib and Spelunkery
2. Load a new world
3. Notice how caves only generate purely in stone and deepslate without any of the other stone types.

**Expected behavior:**
Strips of stone types generate like in the Fabric version of the mod.

**Comment by AstralOrdana** [comment]
fixed for 0.1.4
