### ISSUE TITLE
End portal fluid pools

### ISSUE THREAD

**Issue by Nekkok** [AstralOrdana/Spelunkery#47]
**Feature:**
I thought that it would be cool that some pools of portal fluid could spawn there **_extremely rarely_**. It could serve players with limited resources to return to the overworld. And somehow, lorewise talking, could explain the method of endermen travelling through dimensions.

**Additional info:**
With that said, that would make portal fluid unbucketable for obvious reasons. (Or maybe not, who knows.)

**Comment by AstralOrdana** [comment]
implemented for upcoming version

**Comment by ThatB0i** [comment]
wait what happened to the "extremely rarely" part?

**Comment by AstralOrdana** [comment]
i implemented the suggestion how i saw fit, i made them as rare as i wanted them to be

**Comment by ThatB0i** [comment]
ok
