### ISSUE TITLE
[Feature Req] More Mod Compatbilities

### ISSUE THREAD

**Issue by Redgi110** [AstralOrdana/Spelunkery#48]
**Feature:**

How about add compatbility with Galosphere(add raw silver nugget to Galosphere deepslate silver ore drop). Also how about disable Spelunkery copper nuggets when Copper Equipment/Copper Overhaul/any other mod what adds copper nugget instaled.

**Comment by AstralOrdana** [comment]
there are no plans for modded ore support beyond the existing support for sully's mod, create and oreganized
