### ISSUE TITLE
[1.19.2] Replaces all vanilla diamond ore loot tables?

### ISSUE THREAD

**Issue by itsdinkd** [AstralOrdana/Spelunkery#5]
in 0.1.3 it seems that all diamonds that drop from diamond ore have been replaced with Spelunkerys version of diamond.

Not sure if this is a feature or a bug... same with most of the other vanilla ores, lapis, redstone, etc.

![image](https://user-images.githubusercontent.com/35115304/211683765-a9a87f9e-f81e-482f-bbd8-35744c642168.png)

**Comment by AstralOrdana** [comment]
that's one of the main features of the mod

**Comment by itsdinkd** [comment]
Right. where is the grinding recipe?
![image](https://user-images.githubusercontent.com/35115304/211692620-7175dff5-3269-40ea-90b3-e0131d2f3229.png)


There is no grindstone block, so is the type meant for Minecraft grinding? 
![image](https://user-images.githubusercontent.com/35115304/211692662-2dfe7dc3-d0a8-4332-a3e4-174a36cf058a.png)

No recipe using your mod or vanilla mechanics to convert to diamond. the recipe only exists through Create,

**Comment by AstralOrdana** [comment]
I'm assuming you deleted your follow-up question in embarrassment? For anyone else looking at this issue, the tooltip says "use on a grindstone to polish" so use the rough gem on a grindstone and it becomes polished.

**Comment by itsdinkd** [comment]
> I'm assuming you deleted your follow-up question in embarrassment? For anyone else looking at this issue, the tooltip says "use on a grindstone to polish" so use the rough gem on a grindstone and it becomes polished.

Sure did. But since youre being a dick ill go ahead and remove your mod from my pack. Oof there goes 2k downloads a week.

**Comment by AstralOrdana** [comment]
I point people to my issues page when they have a problem someone else has had before, if people keep having the same issue, I'll change how the thing works. My intent wasn't to imply you were dumb, I wanted to give context to my reply that now seemed to be replying to nobody in case anyone else searches for this issue.

**Comment by itsdinkd** [comment]
Thank you for the clarification.
