### ISSUE TITLE
Lack of support for Allurement's level-scaling removal

### ISSUE THREAD

**Issue by donkeyrat** [AstralOrdana/Spelunkery#50]
Allurement has a configurable setting that allows you to remove vanilla's experience level-scaling. You can set a static amount of experience needed, and it will never scale. However, even with this setting active, Nephrite operates based on Vanilla level calculations.

This creates problems when you take levels away from yourself and add them back; you'll get back more levels than you put in.

**Comment by AstralOrdana** [comment]
this is not the case, nephrite operates in experience points rather than levels so level scaling should never be an issue

**Comment by donkeyrat** [comment]
well idk, i remove levels with nephrite and then add them back and i get way more back (especially at higher levels)

**Comment by AstralOrdana** [comment]
closed unless shown issue persists
