### ISSUE TITLE
Disabling raw nuggets does nothing

### ISSUE THREAD

**Issue by donkeyrat** [AstralOrdana/Spelunkery#51]
**Describe the bug:**
A clear and concise description of what the bug is. Include as much information as you can. Images are often helpful, especially screenshots of the F3 debug menu.

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version: 1.19.2
Spelunkery version: 0.1.13
Moonlight Lib version: 2.2.14
Fabric API / QSL / Forge version: 43.2.6

**Other mods:**
![image](https://user-images.githubusercontent.com/41966410/222943346-df4eb819-e6cc-4b39-951b-ce39aa81bf60.png)

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Change the "enable_raw_nuggets" setting in the Spelunkery config to false.
2. Restart the game.
3. Observe that it does nothing.

**Expected behavior:**
I expected the raw nuggets to not drop from deepslate, or for their crafting recipes to be removed. Neither happen.

**Comment by AstralOrdana** [comment]
fixed for 0.2.0
