### ISSUE TITLE
[Feature Req] Some QoL for the Magnetic Compass

### ISSUE THREAD

**Issue by Reshirou** [AstralOrdana/Spelunkery#52]
Currently, it's impossible to ever use the Magnetic Compass for telling your location, because it points towards magnetite clusters from too far away, and clearing the Compass has no cooldown for linking again, so you can't ever see your coordinates out in the wild. Even after mining the clusters interfering, it immediately points to the next closest cluster.

There are multiple potential ways to go about making the Compass useable while maintaining the interference:

1. Add a cooldown after clearing the compass before it links up again, so you can right click for your coords
2. Reduce the spawn rate of magnetite clusters
3. Add a method of reducing the distance an individual compass catches interference, such as "waxed magnetic compass," or some smithing table upgrade using a rare material
5. Make the compass show your location when right clicked above or below showing where it's pointing to

EDIT: I know there is a config for the interference default itself

**Comment by AstralOrdana** [comment]
resolved for Spelunkery 0.2.1
