### ISSUE TITLE
Having the mod installed makes chunk generation noticeably slower

### ISSUE THREAD

**Issue by Trepppy** [AstralOrdana/Spelunkery#53]
Been making a small modpack on my free time and it's in its earlier stages, I noticed once I add spelunkery the chunks load in slower, like the little generating world square is even slower, I dont have any frame drops the chunks just struggle to keep up with me while flying (elytra or creative). Tested it without spelunkery and it went back to normal, here are the other mods I had installed:

Blueprint
TeamAbnormals
blueprint-1.19.2-6.1.0.jar

AI Improvements
QueenOfMissiles
AI-Improvements-1.19.2-0.5.2.jar

Autumnity
TeamAbnormals
autumnity-1.19.2-4.0.0.jar

Building Blocks Overhaul (Forge)
SoulCrystalStudio
BuildingBlocksOverhaul-2.0.0-Forge1.19.2.jar

Clumps
Jaredlll08
Clumps-forge-1.19.2-9.0.0+14.jar

Entity Culling Fabric/Forge
tr9zw
entityculling-forge-1.6.1-mc1.19.2.jar

Environmental
TeamAbnormals
environmental-1.19.2-3.0.0.jar

FerriteCore (Forge)
malte0811
ferritecore-5.0.3-forge.jar

Glazed ReSymmetry
Lethosos
glazedresymmetry-1.19.2-1.2.jar

Magnesium/Rubidium Extras
TeamDeusVult
rubidium_extras-1.19.2_v1.3.2.jar

Rubidium
Asek3
rubidium-0.6.2.jar

**Comment by AstralOrdana** [comment]
its a known issue that spelunkery causes slower world creation, disable the stone stripes in the config if this is an issue
