### ISSUE TITLE
[Possible Mod Conflict] Very loud Magnetic Compass

### ISSUE THREAD

**Issue by Samarai** [AstralOrdana/Spelunkery#55]
**Describe the bug:**
Simply put, the Magnetic Compass is extremely loud upon finding a new magnetite cluster to be drawn towards on its own, or manually 'refreshed' by the player. It seems like the sound effect might be playing more than once simultaneously. This might be being caused/exacerbated by the Sound Physics Remastered mod 

**Versions:**
Minecraft version: 1.19.2
Spelunkery version: 0.1.13
Moonlight Lib version: 2.2.19
Fabric API version: 0.75.1

**Other mods:**

![Screenshot (3355)](https://user-images.githubusercontent.com/5153958/225212208-5d1f0f1c-b7cd-4ce0-8696-a1a21a8a0871.png)

**Logs:**
[latest.log](https://github.com/AstralOrdana/Spelunkery/files/10976204/latest.log)
[launcher_log.txt](https://github.com/AstralOrdana/Spelunkery/files/10976208/launcher_log.txt)

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1.Smith or cheat-in a Magnetic Compass.
2.Shift + Use to refresh it, and notice that the sound effect for being drawn to a new magnetic influence is a bit louder than it should be.

**Expected behavior:**
The cool sound effect for the Magnetic Compass playing at a reasonable volume, and not jumpscaring me when I manage to clear out a Magnetite geode.

**Comment by mintynora** [comment]
Yeah seems like it's a sound physics remastered thing. I have it on forge, and the magnetite compass sound is very loud.

**Comment by AstralOrdana** [comment]
regardless of potential mod conflict, compass ping sound volume has been reduced for upcoming version
