### ISSUE TITLE
Generation crash while exploring

### ISSUE THREAD

**Issue by Sunconure11** [AstralOrdana/Spelunkery#59]
https://pastebin.com/F6cMmfmS

Minecraft version: 1.19.2
Moonlight lib build: 1.19.2-2.2.27
Quilt build: 0.18.6
Quilt Fabric API: QFAPI 4.0.0-beta.30 and QSL 3.0.0-beta.29

**Comment by AstralOrdana** [comment]
disable improved sculk features in the config as temporary fix, we will look into the crash

**Comment by AstralOrdana** [comment]
resolved for Spelunkery 0.2.1
