### ISSUE TITLE
Experience duplication glitch with Nephrite charm

### ISSUE THREAD

**Issue by pointwoods** [AstralOrdana/Spelunkery#6]
When using a stack of nephrite charms to store experience, the experience is given to all charms in the stack.  Upon unstacking the charms, you can collect the experience from each individual charm, duplicating the original amount of experience put in.

Minecraft version: 1.19.2
Spelunkery version: 0.1.2
Moonlight Lib version: 2.1.25
Fabric API version: 0.72.0

Other mods:
![image](https://user-images.githubusercontent.com/111038136/212122134-9a8a2bdb-13ac-492f-9f2b-5ea92395cf4b.png)

**Comment by AstralOrdana** [comment]
good catch, fixed for next release
