### ISSUE TITLE
Spelunkery Disables Shimmers Default Coloured Light Render

### ISSUE THREAD

**Issue by TheQuantumTantrum** [AstralOrdana/Spelunkery#61]
Placing light blocks such as Lanterns or Sea Lanterns does not have the added coloured lighting/bloom with Spelunkery installed. Removing Spelunkery solves and returns the coloured lighting.

MC: 1.19.2
Forge : 43.2.8
Mods:
- JEI 11.6.0.1013
- Moonlight 2.2.28
- Shimmer 0.1.14
- Spelunkery 0.2.0

**Comment by AstralOrdana** [comment]
should be resolved for next release, reopen if issue persists
