### ISSUE TITLE
When I disable stone stripes it auto turns back on after re-creating a world

### ISSUE THREAD

**Issue by Trepppy** [AstralOrdana/Spelunkery#62]
title says all of it, I usually recreate this one world again and again to test modpack world gen but after turning off stone stripes cause of gen issue they cause, when I create the new world they still generate and when I check the mod configs its on again

**Comment by MehVahdJukaar** [comment]
send the game log

**Comment by Trepppy** [comment]
do I just start the game or do I go through disabling it then creating a world? sorry never had to sedn it before

**Comment by Trepppy** [comment]
I swear to god it did this two times but now its not doing it

**Comment by Trepppy** [comment]
well sorry I guess if the issue shows up again I'll try send a log
