### ISSUE TITLE
Config/Datapack option for Secondary Stone Types/Stone Variant Seams

### ISSUE THREAD

**Issue by UmbralSurvivor** [AstralOrdana/Spelunkery#63]
**Feature:**

There should be a way for modpack makers to add variant stone "seams", like Granite, Diorite, Andesite, etc. 
(Wiki page **[Here](https://github.com/AstralOrdana/Spelunkery/wiki/Vanilla-Alterations#stone-variants-worldgen)**)

**Alternatives:**

Either datapacks or a seperate config file.

**Additional info:**

There should also be ways to make the "encased seams" (like in Lush Caves and the Deep Dark). There should also be biome tags/Y-level limiters for these, so you can make them generate in specific biomes or at specific heights (like Salt and how Lush Cave ones swap between a Calcite outer layer or a Tuff one.)

I also feel like there should be an example on how to change it in the wiki (or a "commented out" version if in a seperate config file).

**Comment by AstralOrdana** [comment]
this is already doable with the mod, the existing stone stripes are data driven and you can add more with datapacks
