### ISSUE TITLE
Spelunkery disables Stonecutter recipe from Handcrafted

### ISSUE THREAD

**Issue by katubug** [AstralOrdana/Spelunkery#64]
**Describe the bug:**
I am so sorry to be relaying a second/third-hand bug, but here I am. I'm the developer of the Cottage Witch modpack, and the mod Handcrafted has a recipe where you throw planks onto a Stonecutter to get a modded item for crafting. However, as of the last modpack update, this no longer works. According to my user, they asked in the Handcrafted discord and another user reported that reverting Spelunkery to 1.1.3 fixes the issue.

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version: 1.19.2
Spelunkery version:  0.2.0
Moonlight Lib version: 2.2.29
Forge version: 43.2.6
Supplementaries: 2.3.2
Handcrafted: 2.0.6

**Other mods:**
https://www.curseforge.com/minecraft/modpacks/cottage-witch/files/4483167

**Logs:**
It literally doesn't say anything, but here:
[latest.log](https://github.com/AstralOrdana/Spelunkery/files/11193138/latest.log)

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Attempt to throw Acacia planks onto a Stonecutter
2. Fail miserably
3. Try not to cry
4. Cry a lot

**Expected behavior:**
Normally, the planks will be turned into Boards.

**Comment by AstralOrdana** [comment]
Could you verify if any other stonecutter recipes are broken? Its all recipes or only recipes added by other mods?

**Comment by katubug** [comment]
The recipe in question isn't one that you put into the stonecutter - those all seem fine. It's an in-world interaction where you use Q to throw the planks on top of the Stonecutter block, and the planks disappear and Boards spawn in their place. That is what doesn't seem to happen.

**Comment by AstralOrdana** [comment]
Okay, so the issue is that both mods add a new method to the stonecutter block class. I'm not aware of a way to bake-in compatibility for this, is there a reason that the other mod doesn't just use a normal stonecutter recipe type? You could create a datapack to add that as a potential fix

**Comment by katubug** [comment]
I'm not sure why they do it this way, but I'm happy to make compatibility on my end. And it does still work with the Create Sawmill, which frankly makes more sense anyway than a Stonecutter does.

**Comment by katubug** [comment]
Yes it does

**Comment by AstralOrdana** [comment]
Ok thank you

**Comment by newtrogicNexus** [comment]
This issue still persists, is there any intention of fixing it?

**Comment by AstralOrdana** [comment]
this issue was closed because it cant be fixed from my end, ask the handcrafted mod to add normal recipes for the stonecutter items
