### ISSUE TITLE
[1.19.2, Forge] Issue with falling blocks in deserts

### ISSUE THREAD

**Issue by katubug** [AstralOrdana/Spelunkery#65]
**Describe the bug:**
Hi! I seem to be having an issue in my modpack where venturing near deserts causes massive amounts of `minecraft:falling_block`s to spawn, and they just build up forever until you leave the area or timeout.

I initially reported this here, thinking it was IDAS: https://www.curseforge.com/minecraft/mc-mods/idas/issues/79

However, since then, I have done more testing and have isolated it to Spelunkery - when it is disabled, the falling blocks issue does not happen. And when it is enabled (tested on 1.11-0.2.0), it does. This occurs when Spelunkery and BYG (and dependencies) are the only mods installed. In fact, it's WAY WORSE with just those! I haven't tested with only Spelunkery because I think it's a conflict between the two mods, but of course let me know if you need it tested with only Spelunkery.

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version: 1.19.2
Spelunkery version: 1.11 - 2.0
Moonlight Lib version: 2.2.29
Fabric API / QSL / Forge version: 43.2.6

**Other mods:**
https://i.imgur.com/k0avYwy.png

**Logs:**
[latest.log](https://github.com/AstralOrdana/Spelunkery/files/11205914/latest.log)

Debug.log and other mentioned files do not exist.

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Load up modpack with listed mods
2. Create new world using seed -764017785885797307
3. Fly south until you reach the desert
4. Do /forge entity list

**Expected behavior:**
I am not sure I expect falling blocks at all unless there's been a block update, which in this case there shouldn't have been. But if so, I expect the falling blocks to despawn once they've landed.

**Screenshots:**
I barely got into the desert before I started lagging, and it took me 30 seconds to type this command and get the response: https://i.imgur.com/bOo65Qr.png

**Comment by AstralOrdana** [comment]
So, spelunkery has underground strata features and in deserts. These stripes can be made of sand and if that sand has air below it and it gets updated by flowing water or a growing plant, it can fall and cause a significant chain reaction. Its possible this is the main cause of your issue, I will look into it on my end. In the meantime you can create a datapack that modifies the configured feature responsible for the desert stripes to remove the sand as a temporary fix.

**Comment by katubug** [comment]
noise_stripes_desert.json, right?

**Comment by AstralOrdana** [comment]
correct, you could just replace any instance of `minecraft:sand` with `minecraft:sandstone` for an easy fix, no changes needed to the placed feature

**Comment by katubug** [comment]
Perfect, I'll do that for now. Thanks for the quick response! :)

**Comment by AstralOrdana** [comment]
np, this fix will be implemented into a new spelunkery version most likely in the next week or two

**Comment by AstralOrdana** [comment]
tysm, really glad to hear it!

**Comment by AstralOrdana** [comment]
resolved for Spelunkery 0.2.1
