### ISSUE TITLE
[1.19.2 Forge] Server times out, console spammed with "Detected setBlock in a far chunk"

### ISSUE THREAD

**Issue by katubug** [AstralOrdana/Spelunkery#66]
**Describe the bug:**
So for over a week now, my server keeps hanging on something. People aren't able to connect, but the server never fully crashes. Today I noticed this in the logs, spammed well over 100 times:

```
[14Apr2023 01:55:53.973] [Worker-Main7/ERROR] [net.minecraft.Util/]: Detected setBlock in a far chunk [-213, -1873162], pos: BlockPos{x=-3393, y=-24, z=-29970581}, status: minecraft:features, currently generating: ResourceKey[minecraft:worldgen/placed_feature / minecraft:sculk_patch_deep_dark]
```
I know this mod touches that, I'm wondering if it's something you might have an idea how to fix? I'm not able to test the server without the mod, because it's part of my modpack and I'd have to fully remove it, which I'd prefer not to do. So any help would be great!

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version: 1.19.2
Spelunkery version: 0.2.0
Moonlight Lib version: 2.2.29
Fabric API / QSL / Forge version: 43.2.6

**Other mods:**
Modpack version: https://www.curseforge.com/minecraft/modpacks/cottage-witch/files/4486488

**Logs:**
[latest.log](https://github.com/AstralOrdana/Spelunkery/files/11228167/latest.log)
[debug.log](https://github.com/AstralOrdana/Spelunkery/files/11228168/debug.log)

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Load up modpack on a server
2. Explore world

**Comment by AstralOrdana** [comment]
I'd already found this, it is already fixed for the next release. For now, it should go away if you disable the improved sculk patch config

**Comment by katubug** [comment]
Thanks!
