### ISSUE TITLE
Mine-o-mite creates explosion damage under water at certain angles.

### ISSUE THREAD

**Issue by EdrikP** [AstralOrdana/Spelunkery#67]
**Describe the bug:**
A clear and concise description of what the bug is. Include as much information as you can. Images are often helpful, especially screenshots of the F3 debug menu.
When submerged in water, thrown Mine-o-mite still does explosion damage on blocks if the impact is on the north, west or bottom face of a block.

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version: 1.19.2
Spelunkery version: 0.2.0
Moonlight Lib version: 2.2.29
Fabric API / QSL / Forge version: Forge 43.2.6

**Other mods:**
List all mods that you're using; could be in the form of a list of the filenames, a crash report list, a screenshot of
the mods folder, etc. Just make sure all mods used are known!
JEI
MouseTweaks
Patchouli

**Logs:**
*Even if the game does not crash they may be useful!*
Please provide the following logs:
From .minecraft/logs :  "latest.log" as well as "debug.log" if it exists. From .minecraft : "launcher_log" as well as a
file that starts with "hs_err" if it exists. Note: Double check that the logs are from the correct time. ex, don't give
us a log from a month ago because you forgot to check the date.
[latest.log](https://github.com/AstralOrdana/Spelunkery/files/11237940/latest.log)

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Flint & Steel in off-hand
2. Mine-o-mite Selected on hotbar
3. Aim at north, west or bottom face of a block surrounded/submerged by water.
4. Throw Mine-O-Mite

**Expected behavior:**
Suppressed explosions from all sides.

**Screenshots:**
If applicable, add screenshots to help explain your problem. https://screenshot.help/

**Additional info:**
Add any other information that might be needed.

**Comment by AstralOrdana** [comment]
fixed for 0.2.2
