### ISSUE TITLE
Large, noticable chunk generation lag with Spelunkery installed

### ISSUE THREAD

**Issue by SuspiciousMango** [AstralOrdana/Spelunkery#7]
**Describe the bug:**
I'm putting together a personal pack of about 75 mods or so, and when I threw in Spelunkery I noticed that chunks were taking a noticeably longer time to load than they were before. It happened on both the world generation screen (it took the game about 2 minutes to load the spawn area, as opposed to 15-30 or so seconds without the mod) and flying around a world in creative (I was reaching the edge of the loaded world far more often than I had prior). I didn't want to immediately assume a single mod was the culprit, so I tried loading up a world in an instance with just Moonlight and Spelunkery, and found the same lag. The logs aren't giving any errors, and flying around in spectator I can't even see any Spelunkery stuff generating, other than a couple mushrooms, so I'm not sure exactly whats causing it. But I do know that worldgen seems to be significantly slower with Spelunkery installed. I don't really expect anything to be done about this, because its nearly impossible to just tell a mod dev "hey make your mod faster", but I figured it was worth getting on your radar in case other people come complaining about it later.

**Versions:**
Minecraft version: 1.19.2
Spelunkery version: 0.1.3 and 0.1.4
Moonlight Lib version: 2.1.26
Forge version: 43.2.0

**Other mods:**
Issue happens in both my personal modpack of about 80 mods  (list of mods below) and in a fresh instance with only Moonlight and Spelunkery installed.

![mods](https://user-images.githubusercontent.com/32881537/212427349-c3c2a858-cd41-4487-86e7-cd1485181e5f.PNG)

**Logs:**
The only errors I can see in the logs are http timeout issues (which I assume is my internet acting up lol). Nothing at all related to Spelunkery. But I'll post them anyway because your eyes are probably more keen than mine.

[debug.log](https://github.com/AstralOrdana/Spelunkery/files/10415679/debug.log)
[latest.log](https://github.com/AstralOrdana/Spelunkery/files/10415680/latest.log)

**To Reproduce:**

1. Install Moonlight and Spelunkery into a fresh instance
2. Create a new world
3. Notice that the world load time is significantly longer than vanilla

**Expected behavior:**
Like I said earlier, it sounds super rude to just say "make your mod faster", but if the culprit could be found and the mod could be made to run faster it would be such a joy to use!

**Additional info:**
I hope nothing I've said here comes off as rude. Code optimization is my least favorite thing to do and I realize how ridiculous this report sounds. Its just that the worldgen lag was noticable enough that it made me take a step back and wonder what was up, so I figured I should make you aware of the issue

**Comment by AstralOrdana** [comment]
I'm aware that spelunkery takes a long time to load. This is almost certainly due to the large stone stripes it generates underground but unless someone with a lot more knowledge of MC worldgen and noise code comes along, there's nothing I can do about it. Playing in survival, the worldgen times have been passable enough to be playable but i would advise against using it alongside other large lag contributors like Terralith.

**Comment by SuspiciousMango** [comment]
Ohh the stone strips arent documented on the wiki yet THATS why I didnt notice them before! Thanks. And yeah I totally understand. Thanks for the quick response!
