### ISSUE TITLE
weird not matching Redstone Ore item textures

### ISSUE THREAD

**Issue by asdasdasadg** [AstralOrdana/Spelunkery#72]
https://imgur.com/a/Jvwwehf

**Comment by mintynora** [comment]
pretty simple fix, the block models for those redstone ores use the "off" texture. you can use a resource pack to let them use the "on" texture easily

**Comment by asdasdasadg** [comment]
yeah but shouldn't both the on and off texture to be the same? + I'm not looking for a solution, juuuust reporting the inconsistency :]

**Comment by asdasdasadg** [comment]
> 

not saying this mod is inconsistent btw, just to clear up the misreadable tone haha

**Comment by AstralOrdana** [comment]
resolved for next update. this was intended to only be active when the Unlit Redstone Ores resource pack was enabled
