### ISSUE TITLE
Conk Fungus placing bug

### ISSUE THREAD

**Issue by asdasdasadg** [AstralOrdana/Spelunkery#73]
when trying to place it on the ground it only attaches to blocks facing south.
also why does it have a floor state??

**Comment by mintynora** [comment]
i don't think it can be placed on the ground. not sure what floor state you're referring to

**Comment by asdasdasadg** [comment]
> i don't think it can be placed on the ground. not sure what floor state you're referring to

https://imgur.com/a/R26KMti

**Comment by AstralOrdana** [comment]
that blockstate is intentionally unused, it exists because of shared code with the other types of fungi. Conks arent intended to be placeable on the ground
