### ISSUE TITLE
Granite Lapis Ore loot table override for rough gems drops Diorite Lapis Ore when mined with silk touch

### ISSUE THREAD

**Issue by mintynora** [AstralOrdana/Spelunkery#75]
The loot tables are identical to each other, even though Granite Lapis Ore shouldn't drop Diorite Lapis Ore. Hammer & Chisels work fine on it though. This is the only ore block i could find with this bug.

Versions:
Minecraft version: 1.19.2
Spelunkery version: 0.2.2
Moonlight Lib version: 2.2.31
Forge version: 43.2.3

Logs: Not necessary

To Reproduce:

1. Use a pickaxe enchanted with silk touch
2. Mine Granite Lapis Lazuli Ore
3. Obtain Diorite Lapis Lazuli Ore

Expected behavior: It should drop Granite Lapis Lazuli Ore.

Additional Info: https://github.com/AstralOrdana/Spelunkery/blob/main/common/src/main/resources/data/spelunkery/overrides/loot_tables/granite_lapis_ore.json

**Comment by AstralOrdana** [comment]
fixed
