### ISSUE TITLE
Setting deplete chance to zero causes a game crash when polishing gems

### ISSUE THREAD

**Issue by riley-9054** [AstralOrdana/Spelunkery#76]
**Describe the bug:**
I set the diamond grindstone deplete chance to zero in the config and then tried to polish a rough diamond and my game crashed.

**Versions:**
Minecraft version: 1.19.2
Spelunkery version: 0.2.2-forge
Moonlight Lib version: 2.2.26-forge
Fabric API / QSL / Forge version: 43.1.43

**Other mods:**
Adaptive Performance Tweaks
Allurement
Appleskin
Armor Damage Scale
Artifacts
AutoRegLib
Balm
Better Block Sounds
Berry Good
BE Style Wither
Better Combat
Biomes O'Plenty
Blueprint
Camera Overhaul
Cave Enhancements
Cloth Config
CofH Core
Collective
Combat Roll
Copper Drops
Copperized
Creative Core
Curios
Enchanting Infuser
Endergetic Beta
End's Phantasm
Enlightend
Entity Culling
Explorer's Compass
FallingTree
Farmer's Delight
Ferrite Core
Galosphere
Gardens of the Dead
GeckoLib
Iceberg
Immersive Weathering
Improved Mobs
In Control
Infernal Expansion
Infinite Trading
Inventorio
Item Borders
Just Enough Items
Kiwi
Kotlin
Lazy DFU
Mining Master
Mob Compack
Moonlight
Music Duration Reducer
MUtil
Nature's Compass
Optifine
Placebo
Player Animation Library
Pluto
Prism
PuzzlesLib
Quark
Quark Oddities
Radon
Redstone Arsenal
Regions Unexplored
Resourceful Config
Saturn
Savage And Ravage
Shut Up Experimental Settings
Smooth Chunk
Sophisticated Backpacks
Sophisticated Core
Spelunkery
Starlight
Subterrestrial
Supplementaries
Surface Mushrooms
TenshiLib
TerraBlender
Tetra
Tetratic Combat
Thermal Dynamics
Thermal Expansion
Thermal Foundation
Thermal Integration
Traveler's Titles
Upgrade Aquatic
Volcanic Caverns
Waystones
Wither Skeleton Tweaks
Xaero's Minimap
Xaero's Worldmap
Yung's API
Yung's Better Nether Fortresses
Yung's Better Strongholds
Yung's Extras

**Logs:**
[latest.log](https://github.com/AstralOrdana/Spelunkery/files/11348284/latest.log)
[debug.log](https://github.com/AstralOrdana/Spelunkery/files/11348287/debug.log)

**To Reproduce:**
1. Set the diamond grindstone deplete chance to 0 in the config.
2. Attempt to polish a rough gemstone on the diamond grindstone.
3. Your game will freeze up for a few seconds, then display the "Saving World..." screen and then close.

**Expected behavior:**
The game does not crash and the gemstone is polished.

**Screenshots:**
Not necessary

**Additional info:**
Here is the crash report
[crash-2023-04-27_16.40.06-client.txt](https://github.com/AstralOrdana/Spelunkery/files/11348305/crash-2023-04-27_16.40.06-client.txt)
This was tested with rough diamond and rough lapis with the deplete chance at zero, and then tested with rough lapis and rough cinnabar with the deplete chance at one. It crashed on both diamond and lapis when the deplete chance was at zero. I did not test to see if removing any other mods would fix it, however.

**Comment by AstralOrdana** [comment]
resolved and disable depletion config option added
