### ISSUE TITLE
Nephrite Siphon stops working when sneaking instead of going faster

### ISSUE THREAD

**Issue by riskable** [AstralOrdana/Spelunkery#77]
**Describe the bug:**
Playing the Cottage Witch modpack (1.19-1.14.2), when you sneak on a Nephrite Siphon to make it drain faster it stops draining entirely.

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version: 19.2
Spelunkery version: 0.2.2
Moonlight Lib version: 2.2.31
Fabric API / QSL / Forge version: 43.2.8

**Other mods:**
appleskin-forge-mc1.19-2.4.2.jar
beenfo-1.19.1-forge42.0.1-1.2.jar
Entity_Collision_FPS_Fix-forge-1.19-2.0.0.0.jar
FastLeafDecay-30.jar
findme-3.1.0-forge.jar
glassential-forge-1.19-1.2.4.jar
gravelminer-forge-1.19-13.0.0.jar
Infinity-Water-Bucket-1.19-2.0.0.jar
itemzoom-1.19-2.7.0.jar
MissingWilds-forge-1.19-1.1.1.jar
MouseTweaks-forge-mc1.19-2.23.jar
MyServerIsCompatible-1.19-1.0.jar
portablejukebox-forge-1.19-2.2.0.jar
QuarkOddities-1.18.jar
radon-0.8.2.jar
SkyVillages-1.0.1-1.19-forge-release.jar
spawnermod-1.19.0-1.9.1+Forge.jar
starlight-1.1.1+forge.cf5b10b.jar
supermartijn642configlib-1.1.6b-forge-mc1.19.jar
time-in-a-bottle-3.0.1-mc1.19.jar
advancementframes-1.19.2-2.0.0.jar
BetterAdvancements-1.19.2-0.2.2.142.jar
BowInfinityFix-1.19.x-forge-2.5.1.jar
caelus-forge-1.19.2-3.0.0.6.jar
charginggadgets-1.9.0.jar
Decorative Blocks-forge-1.19.2-3.0.0.jar
EasierSleeping-1.19.2-2.1.2.jar
FinalKobold-1.19.2-1.1.4.jar
ftb-essentials-1902.1.10-build.47.jar
inventorysorter-1.19.2-21.0.4.jar
MagicMirror-1.19.2-1.0.3.608.jar
mcw-paintings-1.0.4-mc1.19.2.jar
Notes-1.19.2-1.2.5.jar
ObsidianBoat-1.11.0-build.20+mc1.19.2.jar
personality-1.19-3.0.1.jar
smoothchunk-1.19.1-2.0.jar
snad-1.3.1.jar
swingthroughgrass-1.19.2-1.10.0.jar
trade-cycling-forge-1.19.2-1.0.5.jar
betterlily.jar
BetterTags-1.19.2-1.0.jar
cloth-config-8.2.88-forge.jar
GildedNetherite-CJ-forge-mc1.19.2-0.9.2.jar
jumpoverfences-forge-1.19.2-1.1.0.jar
lootbeams-1.19.2-beta-sept1322.jar
mcwfencesbyg-1.19.2-1.0.jar
NethersDelight-1.19-3.0.jar
RingOfEnderchest-Forge-1.19.2-1.5.5.jar
SilveroakOutpost-Forge-1.19.2-2.0.0-Beta.jar
solsweetpotato-1.19.2-2.0.0.jar
theoneprobe-1.19-6.2.2.jar
AI-Improvements-1.19.2-0.5.2.jar
Apple Crates-forge-1.19.2-2.9.0.jar
Contact-Forge-1.19.2-2.0.0-Beta.jar
CosmeticArmorReworked-1.19.2-v1a.jar
deepslatecutting-forge-1.5.0.jar
DiagonalFences-v4.2.3-1.19.2-Forge.jar
Display Case-forge-1.19-1.0.3.jar
effective_fg-1.3.4.jar
ExplorersCompass-1.19.2-1.3.0-forge.jar
farsight-1.19.2-2.1.jar
goblintraders-1.8.0-1.19.2.jar
NekosEnchantedBooks-1.19-1.8.0.jar
OldCombatMod_1.19.2.jar
SpawnBalanceUtility-1.19-41.1.11.1.jar
ToastControl-1.19.2-7.0.0.jar
FarmersDelight-1.19-1.2.0.jar
FastFurnace-1.19.2-7.0.0.jar
Patchouli-1.19.2-77.jar
YungsBetterMineshafts-1.19.2-Forge-3.2.0.jar
YungsBetterWitchHuts-1.19.2-Forge-2.1.0.jar
1.19.2-betteramethyst-1.0.2.jar
another_furniture-forge-2.1.2-1.19.2.jar
beautify-1.4.3.jar
bigfish-1.19.2-1.0.0.jar
block_variants-1.19.2-4.4.jar
Controlling-forge-1.19.2-10.0+7.jar
endrem_forge-5.2.1-R-1.19.X.jar
EnigmaticGraves-1.19.2-1.7.6.jar
item-filters-forge-1902.2.9-build.46.jar
moredragoneggs-3.2.jar
questsadditions-1.19.2-1.4.1.jar
ametrin-1.19.2-0.0.26.jar
babyfat-forge-1.19.2-1.1.2.jar
maenchants-1.19.2-6.0.0.jar
nightlights_1.19.2_1.1.jar
NoChatReports-FORGE-1.19.2-v1.5.1.jar
sprout-1.4.4-forge.jar
AutoRegLib-1.8.2-55.jar
bwncr-forge-1.19.2-3.14.1.jar
customizableelytra-1.19.0-1.7.4.jar
FarmersRespite-1.19-2.0.jar
ferritecore-5.0.3-forge.jar
Forgiveness-1.19.2-1.3.3.jar
NaturesCompass-1.19.2-1.10.0-forge.jar
plushies-1.2-1.19.2.jar
YungsBetterDungeons-1.19.2-Forge-3.2.2.jar
Better Fishing Rods 1.0.0 - 1.19.2.jar
casting_crystals-1.0.3.jar
Chimes-1.1.4-1.19.jar
duckling-2.0.8-forge.jar
fairylights-6.0.0-1.19.2.jar
mavapi-1.0.1-mc1.19.2.jar
mavm-1.2.0-mc1.19.2.jar
mcw-paths-1.0.2forge-mc1.19.2.jar
pitg-1.19.1-2.1.2.jar
polymorph-forge-0.46.1+1.19.2.jar
SBM-Jukebox-forge-1.19.2-1.0.7.jar
calmmornings-1.19.3-2.0.2.jar
CreativeCore_FORGE_v2.9.3_mc1.19.2.jar
konkrete_forge_1.6.0_MC_1.19-1.19.2.jar
smoothboot(reloaded)-mc1.19.2-0.0.2.jar
AxolotlBucketFix-1.3.0+forge-mc1.19.jar
catalogue-1.7.0-1.19.2.jar
domesticationinnovation-1.6.1-1.19.2.jar
ExperienceBugFix-1.19-1.41.2.3.jar
extendedmushrooms-1.19.2-3.0.1.4.jar
ecologics-forge-1.19.2-2.1.11.jar
mermod-forge-1.11.jar
fantasyfurniture-1.19.2-6.7.0.jar
observable-3.3.1.jar
soundphysics-forge-1.19.2-1.0.18.jar
create_crystal_clear-0.1.2e-1.19.2.jar
mcw-fences-1.0.7-mc1.19.2forge.jar
mcw-windows-2.1.1-mc1.19.2forge.jar
TerraBlender-forge-1.19.2-2.0.1.136.jar
clickadv-1.19.2-3.0.jar
EnchantmentDescriptions-Forge-1.19.2-13.0.14.jar
Fastload-Reforged-2.6.9+1.19.2.jar
Tips-Forge-1.19.2-8.0.27.jar
alexsdelight-1.4.1.jar
deepslatetweaks-1.0-1.19.2.jar
EquipmentCompare-1.19.2-forge-1.3.2.jar
Strawgolem-forge-1.19.2-2.0.0-beta.5.jar
ars_creo-1.19.2-3.1.3.jar
connectedglass-1.1.6-forge-mc1.19.jar
HealthOverlay-1.19.2-7.2.1.jar
rubidium_extras-1.19.2_v1.3.2.jar
GatewaysToEternity-1.19.2-3.1.1.jar
betterf3plus-1.0.jar
Disenchanting-forge-1.19-2.2.2.jar
Iceberg-1.19.2-forge-1.1.4.jar
oculus-mc1.19.2-1.2.8a.jar
scaffoldingdropsnearby-1.19.2-3.0.jar
dismountentity-1.19.2-3.0.jar
functionalstorage-1.19.2-1.1.3.jar
lazydfu-1.19-1.0.2.jar
Paxi-1.19.2-Forge-3.0.1.jar
adaptive_performance_tweaks_player_1.19.2-6.5.0.jar
betterfpsdist-1.19.2-1.8.jar
charmofundying-forge-6.1.1+1.19.2.jar
DarkPaintings-Forge-1.19.2-13.1.5.jar
flywheel-forge-1.19.2-0.6.8.a.jar
MagnumTorch-v4.2.1-1.19.2-Forge.jar
overloadedarmorbar-1.19.3-7.1.jar
prefab-1.9.2.5.jar
snailmail-1.19.2-1.1.0-forge.jar
moyai-1.19.2-2.0.1.jar
TF_Lost_Blocks-1.19.2-1.1.jar
AkashicTome-1.6-23.jar
crittersandcompanions-1.19.2-1.1.2.jar
culturaldelights-1.19.2-0.15.1.jar
experienceobelisk-v1.3.8-1.19.2.jar
MPE 1.1.0.jar
sculktransporting-1.19.2-1.1.jar
astikorcarts-1.19.2-1.1.2.jar
BetterTridents-v4.0.2-1.19.2-Forge.jar
Ding-1.19.2-Forge-1.4.0.jar
elytraslot-forge-6.1.0+1.19.2.jar
itemcollectors-1.1.7-forge-mc1.19.jar
VillagersPlus_1.2_(FORGE)_for_1.19.2.jar
chalk-1.19-1.4.0.jar
deeperdarker-forge-1.1.6-forge.jar
followersteleporttoo-1.19.2-2.1.jar
heartstone-1.19.2-1.1.1.jar
overweightfarming-1.19.2-2.0.1-forge.jar
usefulslime-1.9-1.19.2.jar
convenientcurioscontainer-1.12-1.19.2.jar
cryingghasts-1.19.2-3.1.jar
alexsmobs-1.21.1.jar
entityculling-forge-1.6.1-mc1.19.2.jar
forgivingworld-1.19.2-4.0.jar
shorkmod-1.0.jar
alternate-current-mc1.19-1.5.0.jar
crashutilities-6.2.jar
create-1.19.2-0.5.0.i.jar
Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.0.13.jar
serverconfigupdater-3.2.jar
EasyMagic-v4.3.3-1.19.2-Forge.jar
ftbbackups2-forge-1.19.2-1.0.18.jar
geckolib-forge-1.19-3.1.40.jar
CNB-1.19-1.5.2.jar
craftingtweaks-forge-1.19-15.1.6.jar
defaultoptions-forge-1.19-15.0.1.jar
shetiphiancore-forge-1.19.0-3.11.3.01.jar
sliceanddice-2.0.3.jar
adaptive_performance_tweaks_items_1.19.2-6.6.0.jar
buildinggadgets-3.16.2-build.22+mc1.19.2.jar
inventoryessentials-forge-1.19-5.0.2.jar
netherportalfix-forge-1.19-10.0.1.jar
trashslot-forge-1.19-12.0.2.jar
abnormals_delight-1.19.2-4.0.2.jar
CorgiLib-forge-1.19.2-1.0.0.32.jar
cyclepaintings-1.19.2-3.2.jar
majruszs-accessories-1.19.2-1.1.4.jar
starterkit-1.19.2-5.2.jar
chefs-delight-1.0.1-forge-1.19.2.jar
ColorfulAzaleas-forge-1.19.2-2.2.1.jar
Lexicon-1.19.2-(v.1.4.2).jar
ars_elemental-1.19.2-0.5.8.2.jar
Bookshelf-Forge-1.19.2-16.2.18.jar
YungsBetterNetherFortresses-1.19.2-Forge-1.0.5.jar
JustEnoughProfessions-forge-1.19.2-2.0.2.jar
snuffles-1.0.4.jar
twilightforest-1.19.2-4.2.1518-universal.jar
chunksending-forge-1.19-2.5.jar
environmental-1.19.2-3.0.0.jar
majrusz-library-1.19.2-3.3.0.jar
mcw-trapdoors-1.0.9-mc1.19.2forge.jar
artifacts-1.19.2-5.0.2.jar
AttributeFix-Forge-1.19.2-17.2.6.jar
collective-1.19.2-6.53.jar
integrated_stronghold_forge-1.0.1+1.19.2.jar
JustEnoughResources-1.19.2-1.2.2.200.jar
lootintegrations-1.19-3.0.jar
mcw-roofs-2.2.3-mc1.19.2forge.jar
mysticaloaktree-1.19.2-1.8.jar
ftb-ultimine-forge-1902.4.0-build.77.jar
Structory_Towers_1.19.3_v1.0.2.jar
YungsApi-1.19.2-Forge-3.8.9.jar
balm-forge-1.19.2-4.5.7.jar
CreateTweaker-1.19.2-3.0.0.5.jar
handcrafted-forge-1.19.2-2.0.6.jar
Structory_1.19.3_v1.3.1a.jar
waystones-forge-1.19.2-11.3.1.jar
blueprint-1.19.2-6.1.2.jar
mcw-bridges-2.0.7-mc1.19.2forge.jar
resourcefulconfig-forge-1.19.2-1.0.20.jar
creeperoverhaul-2.0.9-forge.jar
integrated_api_forge-1.2.7+1.19.2.jar
JeiTweaker-forge-1.19.2-4.0.11.jar
mcw-doors-1.0.9forge-mc1.19.2.jar
tarotcards-1.19.2-1.2-release.jar
VisualWorkbench-v4.2.4-1.19.2-Forge.jar
configured-2.1.1-1.19.2.jar
lootr-1.19-0.4.23.60.jar
luggage-1.19-1.6.jar
netherdepthsupgrade-2.0.3-1.19.2.jar
rubidium-0.6.2a.jar
BrewinAndChewin-1.19-2.0.jar
memoryleakfix-forge-1.17+-1.0.0.jar
swampier_swamps-1.19-1.2.0.jar
CraftTweaker-forge-1.19.2-10.1.41.jar
kotlinforforge-3.11.0-all.jar
pluto-mc1.19.2-0.0.9.jar
toms_storage-1.19-1.5.4.jar
architectury-6.5.77-forge.jar
citadel-2.1.3-1.19.jar
macawsbridgesbyg-1.19.2-1.2.jar
macawsroofsbyg-1.19.2-1.3.jar
ftb-teams-forge-1902.2.13-build.100.jar
starbunclemania-1.19.2-1.0.6.jar
caupona-1.19.2-0.2.7.jar
immersive_aircraft-0.4.2+1.19.2-forge.jar
resourcefullib-forge-1.19.2-1.1.24.jar
adaptive_performance_tweaks_core_1.19.2-6.7.0.jar
backpacked-2.1.12-1.19.2.jar
hexerei-0.3.0.jar
mcsa-forge-3.1.4+1.19.jar
ars_instrumentum-1.19.2-3.3.1.jar
curiotiab-1.19.2-1.5.1.jar
FramedBlocks-6.8.3.jar
extremesoundmuffler-3.37-forge-1.19.2.jar
seedpouch-1.4.jar
supermartijn642corelib-1.1.7-forge-mc1.19.jar
titanium-1.19.2-3.7.3-27.jar
idas_forge-1.7.0+1.19.2.jar
ars_nouveau-1.19.2-3.13.2.jar
FastSuite-1.19.2-4.1.0.jar
collectorsreap-1.19-1.2.3.jar
friendsandfoes-forge-mc1.19.2-1.8.1.jar
ImmediatelyFastReforged-1.19.2-1.1.12.jar
reaping-forge-2.2.0+no-pehkui.jar
Delightful-1.19.2-3.2.4.jar
polylib-forge-1900.0.2-build.73.jar
CraftPresence-2.0.0-rc.2+1.19.2.jar
structure_gel-1.19.2-2.7.2.jar
davespotioneering-1.19.2-1.1.4.jar
dungeons_plus-1.19.2-1.3.1.jar
moonlight-1.19.2-2.2.31-forge.jar
Quark-3.4-397.jar
curios-forge-1.19.2-5.1.4.0.jar
kiwiboi-1.19.2-1.1.0.jar
Xaeros_Minimap_23.4.0_Forge_1.19.1.jar
XaerosWorldMap_1.30.0_Forge_1.19.1.jar
comforts-forge-6.0.5+1.19.2.jar
ftb-chunks-forge-1902.3.21-build.266.jar
jei-1.19.2-forge-11.6.0.1015.jar
MobLassos-v4.0.0-1.19.2-Forge.jar
pipez-1.19.2-1.1.0.jar
Placebo-1.19.2-7.1.8.jar
PuzzlesLib-v4.4.0-1.19.2-Forge.jar
saturn-mc1.19.2-0.0.3.jar
sootychimneys-1.19.2-1.1.0.jar
EasyAnvils-v4.0.11-1.19.2-Forge.jar
ftb-library-forge-1902.3.18-build.208.jar
BalloonBox1.19.2(Forge)vs.1.0.2.jar
spelunkery-1.19.2-0.2.2-forge.jar
fancymenu_forge_2.14.7_MC_1.19-1.19.2.jar
AmbientSounds_FORGE_v5.2.13_mc1.19.2.jar
biomesinjars_forge_1.1.3_MC_1.19-1.19.2.jar
Cluttered-2.0.1-1.19.2.jar
endsdelight-1.19.2-1.1.jar
miners_delight-1.19.2-1.1.1.jar
Portfolio-1.19.2-1.1.0-forge.jar
spark-1.10.37-forge.jar
voicechat-forge-1.19.2-2.4.5.jar
connectivity-1.19.2-3.5.jar
create_central_kitchen-1.19.2-for-create-0.5.0.i-1.3.4.jar
ftb-quests-forge-1902.4.13-build.219.jar
ctov-3.2.0.jar
drippyloadingscreen_forge_2.2.1_MC_1.19.1-1.19.2.jar
FastWorkbench-1.19.2-7.1.2.jar
supplementaries-1.19.2-2.3.4.jar
DramaticDoors-Forge-1.19.2-2.3.2.jar
morediscs-1.19.2-27-forge.jar

**Logs:**
Please provide the following logs:
From .minecraft/logs :  latest.log: https://mclo.gs/sNQmB2t

**To Reproduce:**
In a local world the problem doesn't happen.  It only seems to happen on servers.  Quickest way to reproduce this is to run the Cottage Witch modpack server and join it using the Cottage Witch modpack (client).

**Expected behavior:**
XP should drain faster when sneaking/crouching.

**Screenshots:**
Not relevant.

**Additional info:**
Would be nice to have a faster way to drain XP into Carve Nephrite *in general*.  Example: Right-clicking on it with a Nephrite Charm.

**Comment by AstralOrdana** [comment]
does this persist in latest version of the mod?

**Comment by AstralOrdana** [comment]
closed unless shown issue persists
