### ISSUE TITLE
Dirt and Coarse dirt strips can spawn in some stony biome such as windswept hills and frozen peaks

### ISSUE THREAD

**Issue by WitheredWasabi** [AstralOrdana/Spelunkery#8]
**Describe the bug:**
An intentional change by mojang was made to prevent any dirt from spawning in some of the mountain biomes, but the dirt strips from this mod bypass that.
**Versions: **
Minecraft version: 1.19.2
Spelunkery version: Latest
Moonlight Lib version: Latest 
Fabric API / QSL / Forge version: 43.1.25

**Other mods:**
None

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Load World
2. Go to Frozen Peaks or Windswept Hills
3. Find strips of dirt

**Expected behavior:**
Dirt cannot generate in stony biomes.

**Comment by AstralOrdana** [comment]
fixed for next version
