### ISSUE TITLE
Fabric - Fluid amounts incorrect

### ISSUE THREAD

**Issue by soup587** [AstralOrdana/Spelunkery#83]
**Describe the bug:**
The mod's datapack on Fabric has incorrect values for Dimensional Fluid recipes (namely draining and spilling from Create) which results in a massively decreased amount of fluid made and used (recipes use 3mb in-game, Create Fabric defines its fluids as 20250 instead of 250)

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Spelunkery, Moonlight Lib and Supplementaries)**
Minecraft version: 1.19.2
Spelunkery version: 0.2.2
Moonlight Lib version: 2.2.38
Fabric API / QSL / Forge version: Fabric 0.14.21

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Load game with Spelunkery and Create installed
2. Check recipes (either with a recipe viewer or manual testing)

**Expected behavior:**
Fluids output/require 250mb of fluid

**Additional info:**
A datapack with values set to 20250 solves the issue. Dunno why it happens, does Fabric define fluid values differently?

**Comment by AstralOrdana** [comment]
which create version are you using?

**Comment by f0rttnite** [comment]
oh, 0.5.0i patch 6

**Comment by AstralOrdana** [comment]
with the current version of spelunkery, the crushing recipes will be invalid but see if the fluid issue persists in 0.5.1
