### ISSUE TITLE
FORGE: Crushed ore recipes don't give crushed ores

### ISSUE THREAD

**Issue by CamKablam** [AstralOrdana/Spelunkery#85]
All recipes added by spelunkery in which it should produce crushed raw ores do not. The recipe jsons have the wrong item ids in them
If the mods list is needed I can provide it, but to my current knowledge it isn't needed, and it would take a while to name then all off

Minecraft version: 1.19.2
Spelunkery version: 0.2.2-forge
Moonlight Lib version: 2.2.40-forge
Forge version: 43.2.13

![2023-06-30_13 48 54](https://github.com/AstralOrdana/Spelunkery/assets/47013387/f63676a8-27df-467c-b748-d832d92ea7e6)

**Comment by AstralOrdana** [comment]
this is due to the create mod changing the name of some of its items, will be fixed in the next version
