### ISSUE TITLE
Instant crash when attempting slime alchemy

### ISSUE THREAD

**Issue by ThatSmartGuy21** [AstralOrdana/Spelunkery#87]
When I attempted to summon a slime by throwing a slime block into a cauldron, the moment the block touched the water in the cauldron my game crashed.

Minecraft version: 1.19.2
Spelunkery version: Fabric 0.2.2
Moonlight Lib version: 2.2.43
Fabric API version: 0.14.21

List all mods that you're using; 
- Fabric API
- Moonlight
- Spelunkery

**Logs:**
[latest.log](https://github.com/AstralOrdana/Spelunkery/files/11992406/latest.log)

Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Open a new superflat world
2. Place a cauldron
3. Fill cauldron with water
4. Throw in a slime block

**Expected behavior:**
I expected the water in the cauldron and slime block to vanish, leaving a baby slime in its place.

**Comment by AstralOrdana** [comment]
fixed for next update
