### ISSUE TITLE
Doesn't function well with other mods

### ISSUE THREAD

**Issue by ereese99** [AstralOrdana/Spelunkery#9]
Any other mod that has diamond/emerald/redstone ores do not have their loot tables effected. This is an issue, but moreso a request. The mods I can note (the ones I'm using) that could use some compatibilities are:
- Ad Astra! 
- Universal Ores (especially this one!!!!)
- Deeper Darker

I appreciate all your hard work!

**Comment by AstralOrdana** [comment]
there's no reasonable way for me to have automatic support for any mod that might add new gemstone ores, that would need to be handed by the other mod creator or the person managing the modpack. For Universal Ores, I believe the loot tables are generated via data files so I don't know how I would even begin to alter that. For now, support for this from my end is a no
