### ISSUE TITLE
Add a data fixer for updating from 0.2.x to 0.3.x

### ISSUE THREAD

**Issue by Abbie5** [AstralOrdana/Spelunkery#96]
**Feature:**

In the 0.3.0 update, Magnetite Blocks, Raw Magnetite, and Nephrite Fountains were renamed, causing them to disappear in existing worlds. Rather than letting these blocks just disappear, a data fixer from Mojang's DFU library could be used to convert them to the new name.

**Alternatives:**

Just let them disappear.

**Additional info:**

After doing some research, it seems that the documentation on this subject is sparse and/or outdated. This might be more work than it is worth.

**Comment by AstralOrdana** [comment]
not planned
