### ISSUE TITLE
[Fabric 1.19.2] Game crashes if parachute is used in third person

### ISSUE THREAD

**Issue by koppiki** [AstralOrdana/Spelunkery#99]
Functions as normal in first person. I don't have shaders on or anything. Using most recent version of the mod.

**Comment by Moomallowz** [comment]
Having the same issue on Forge 1.19.2. crash.txt and latest.log are attached below:
[crash-2023-07-30_21.41.23-client.txt](https://github.com/AstralOrdana/Spelunkery/files/12211043/crash-2023-07-30_21.41.23-client.txt)
[latest.log](https://github.com/AstralOrdana/Spelunkery/files/12211044/latest.log)

**Comment by AstralOrdana** [comment]
fixed for 0.2.5
